### ISSUE TITLE
Change of track (path) color

### ISSUE THREAD

**Issue by navitraspi** [navit-gps/navit#1016]
Hey everyone. I’ve been trying to change the default green navigation color on an Android layout, but I changed every color that seemed to be green to blue, but there’s still a green, wide path. I want to change the width too, but found no solution on the web. Can anyone please help me with this? Changing the cursor color succeed, but the path - no...

**Comment by navitraspi** [comment]
It’s me again to tell that it helped! I successfully changed the color of route path to nice, soft blue thing. Thank you so much for your help!

**Comment by metalstrolch** [comment]
Glad I could help. Closing this.
