### ISSUE TITLE
FTBFS with new gpsd 3.21

### ISSUE THREAD

**Issue by david-geiger** [navit-gps/navit#1033]
Hi,

I tried on Mageia Linux (Cauldron) to build latest navit against new gpsd 3.21 but it fails to build due to:

> /home/iurt/rpmbuild/BUILD/navit-0.5.4/navit/vehicle/gpsd/vehicle_gpsd.c: In function 'vehicle_gpsd_callback':
/home/iurt/rpmbuild/BUILD/navit-0.5.4/navit/vehicle/gpsd/vehicle_gpsd.c:169:28: error: 'struct gps_data_t' has no member named 'status'
  169 |         priv->status = data->status;
      |                            ^~
gmake[2]: *** [navit/vehicle/gpsd/CMakeFiles/vehicle_gpsd.dir/build.make:85: navit/vehicle/gpsd/CMakeFiles/vehicle_gpsd.dir/vehicle_gpsd.c.o] Error 1
gmake[2]: Leaving directory '/home/iurt/rpmbuild/BUILD/navit-0.5.4/build'
gmake[1]: *** [CMakeFiles/Makefile2:1386: navit/vehicle/gpsd/CMakeFiles/vehicle_gpsd.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....

Attached full build log:
[build.0.20200807124116.log](https://github.com/navit-gps/navit/files/5041490/build.0.20200807124116.log)

Regards,
David

**Comment by jkoan** [comment]
I can confirm that gpsd 3.21 has removed gps_data_t->status. Need to look into it to find the optimal solution.

**Comment by jkoan** [comment]
Hi @david-geiger, could you please try this patch:
[navit-gpsd_3_21.zip  (its only a zip so Github allowes to upload)](https://github.com/navit-gps/navit/files/5047759/navit-gpsd_3_21.zip)

**Comment by david-geiger** [comment]
The proposed patch fixes build against gpsd 3.21.
