### ISSUE TITLE
Android Playsatore: Update from 0.5.1 to 0.5.4

### ISSUE THREAD

**Issue by jkoan** [navit-gps/navit#1035]
Currently I receive a lot of mails that users are not able to update from Navit 0.5.1 to 0.5.4. I haven't had this issue, so i don't know where its coming from. The old playstore version was 1804161521 and the new one is 2007021541 (git: g8f45131)

. The "only" difference i can see is that we now support the following architectures: arm64-v8a, armeabi-v7a, x86, x86_64 but before it was only armeabi.

I also attached the corresponding apk files:
[playstore_apk_files.zip](https://github.com/navit-gps/navit/files/5045238/playstore_apk_files.zip)

Currently i don't have a trace whats going on, because nobody provided a logcat logfile.

**Comment by jandegr** [comment]
hi,

minSDK went from 9 to 10 and the old armeabi is obsolete.

This can affect some devices but maybe there is someting else affecting other devices.

**Comment by jkoan** [comment]
I also got report for Android 10 and Android 6 so the android version don't seem to be the cause

**Comment by jandegr** [comment]
the version on playstore is now `v0.5.4-fdroid.3-39-g8f45131`

I suppose you have a good reason to work with fdroid but it might be interesting to have a link to that build log.

The old version is `navit 0.5.1-1804161521`

Both versions as I found them in the xml in the apk's

A test to install the newer one over the old one from the zip you posted gives `Package name null is not an installed package`

If you can post a recent release signed version from circleci I can try to upgrade with that one.

**Comment by jkoan** [comment]
the current release version (as of trunk) can be found here: http://download.navit-project.org/#build_android
For me it gives:
```
adb: failed to installandroid-release.apk: Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Package org.navitproject.navit tried to change user org.navitproject.navit]
```
Tried on Oneplus 3t (LineageOS)

**Comment by jkoan** [comment]
@jandegr the old AndroidManifest.xml had `android:sharedUserId="org.navitproject.navit"` defined. The current one doesn't.
Diff both files:
[1804161521.txt](https://github.com/navit-gps/navit/files/5046167/1804161521.txt)
[2007021541.txt](https://github.com/navit-gps/navit/files/5046168/2007021541.txt)

**Comment by jandegr** [comment]
I wanted to test with some older versions but since ci deletes artifacts after a while now that was a no-go....

**Comment by jkoan** [comment]
> I wanted to test with some older versions but since ci deletes artifacts after a while now that was a no-go....

Google Play Keeps all Nighties that we upload, so if you need something in specific i can grab it

**Comment by jandegr** [comment]
If I did not mix-up the apk's, then 31037 works but that is strange, see https://developer.android.com/guide/topics/manifest/manifest-element#uid

**Comment by jkoan** [comment]
I have seen the deprecated-warning as well, but probably its because we had it set within earlier builds. Are you okay with merging #1037?

**Comment by jandegr** [comment]
looks like ther is no other way than to re-add it, it has never been usefull for navit but nevertheless you're stuck with it.
https://stackoverflow.com/questions/33282246/android-app-cannot-update-from-market-after-shareduserid-added

Maybe you can add a note about that trivial entry in #1037, somebody may wonder about it in the future.

**Comment by jkoan** [comment]
Thx for your support, going to merge #1037 and do release 0.5.5, and promote it as soon as possible

**Comment by gefin** [comment]
Just got an error while updating to 5.5 via Playstore on LG K9 7.1.2
After removing 5.4 and empty app trash the installation worked well. 

I use a custom map and config storage.

**Comment by jkoan** [comment]
> Just got an error while updating to 5.5 via Playstore on LG K9 7.1.2
> After removing 5.4 and empty app trash the installation worked well.
> 
> I use a custom map and config storage.

You probably are a beta participant, right? Then reinstalling is the only solution as of current limitations withing the android os itself

**Comment by gefin** [comment]
5.4 was installed via playstore without fail.
Before this i used a self compiled version 5.4.

**Comment by jkoan** [comment]
> 5.4 was installed after clean up via playstore without fail.
> Before this i used a self compiled version 5.4.  

Yes, this is more or less the same. Very version between ~2018 and before the fix is affected. But its needed to get playstore fixed
