### ISSUE TITLE
Altitude in metric with imperial defined.

### ISSUE THREAD

**Issue by Budman1758** [navit-gps/navit#1036]
I know this may be an old issue and I did see the long closed one but that did not help me here.  I have navit installed on a RPI4 with the latest version of Buster.  Navit was installed exactly as described in this article from Ozzmaker
[https://ozzmaker.com/navigating-navit-raspberry-pi/](https://ozzmaker.com/navigating-navit-raspberry-pi/)

As stated in the title the altitude in the lower left corner is displayed in metric units and the speed in the left bottom corner is displayed in imperial. I see in the old issue that it may be displayed in yards but do not think that is true here. Navit displays the position very accurately so if it were yards it would be way off if that was the case.

Again the install is exactly as described in the above link.
Let me know what other info you may need.  Thanks.

Old issue link
[https://github.com/navit-gps/navit/issues/535](https://github.com/navit-gps/navit/issues/535)

**Comment by jkoan** [comment]
This issue is only related to GTK, right? Or is it a osd item that's wrong? (If you don't know it you might also upload a screenshot with some description)

**Comment by JohnK-sljkrr** [comment]
The problem is on OSD. I  have a fix that I will upload tomorrow.

**Comment by jkoan** [comment]
That would be really nice :-)

**Comment by JohnK-sljkrr** [comment]
Sorry been busy
I can send the change and someone can apply it

**Comment by JohnK-sljkrr** [comment]
Here is the file 
[osd_core.c.zip](https://github.com/navit-gps/navit/files/5070522/osd_core.c.zip)

**Comment by Budman1758** [comment]
No idea what to do with your fix.

**Comment by jkoan** [comment]
> Here is the file
> [osd_core.c.zip](https://github.com/navit-gps/navit/files/5070522/osd_core.c.zip)

Thx

> No idea what to do with your fix.

Its for us maintainers ;-)

**Comment by Budman1758** [comment]
OK.  I get that.  How about pushing the newest version to the repositories for us regular folks. :)  Debian version is 2 years old. 5.3

**Comment by jkoan** [comment]
> OK. I get that. How about pushing the newest version to the repositories for us regular folks. :) Debian version is 2 years old. 5.3

We are not able to do this, debian (and because of that ubuntu) have a really stable but slow release workflow, so you usually only get updates on major releases of debian.

**Comment by Budman1758** [comment]
> We are not able to do this, debian (and because of that ubuntu) have a really stable but slow release workflow, so you usually only get updates on major releases of debian.

So.  I ask again.  I have 5.3 on my Raspberry PI.  Is there an upgrade path?

**Comment by mvglasow** [comment]
Bullseye has 0.5.4 (https://packages.debian.org/bullseye/navit), Sid also does; the previous stable release (Buster) has 0.5.3.

The latest version is 0.5.5, released 5 days ago. @aerostitch does most of the Debian packaging; he can probably give you the most accurate information on how long it takes a new release to make it into the Debian repo.

Getting the latest fixes as soon as the project releases them is always difficult for software packages obtained through the latest distribution channels—distro maintainers have to strike a balance between keeping thing stable and rolling out new versions quickly. As jkoan said, that is up to the distro maintainers and therefore beyond our influence.

If you know your way around things, you can of course always try building Navit from source—it takes some more work but will give you the latest version as soon as we add it to the repo. If you prefer a prebuilt package, Debian Sid (being the unstable, aka cutting-edge, release) will give you the latest version the Debian maintainers have packaged.

**Comment by jkoan** [comment]
TODO:

1. Look at the patched File provided ( https://github.com/navit-gps/navit/issues/1036#issuecomment-673611324 )
2. Look for whats changed
3. Redo the same with the now up to date version from the repo
4. Commit the work (leave a thx for @JohnK-sljkrr )
5. push and open a PR
6. Profit
