### ISSUE TITLE
cmake: Stop on first error

### ISSUE THREAD

**Issue by mvglasow** [navit-gps/navit#1042]
Currently, when cmake encounters an error in any of the C source files, it keeps going and going, spitting out pages and pages of warning, and finding the error that needs to be fixed is like finding a needle in a haystack.

Is there a way to get cmake to stop immediately upon detecting a condition which will prevent the build from completing? Following some advice from the net, I tried

    add_compiler_flag_if_available("-Wfatal-errors")

as well as

    add_definitions("-Wfatal-errors")

in CMakeLists.txt, but to no avail.

**Comment by metalstrolch** [comment]
This is because on parallel build, the other runnung instances continue to build even if one of them errored out. Make doesn't kill them on error.
Try disabling parallel building (-j1) and you get sequential output. But lower overall build performance.

**Comment by mvglasow** [comment]
Where would I set `-j1`? And would I need any of the options I mentioned above?

Lower performance is a bummer. Gradle solves that by repeating the error that caused the build to fail at the end—any way to accomplish that on cmake?

**Comment by metalstrolch** [comment]
"-j 1" is a option of "make", so add it to the make step on the command line. if you are building using "cmake --build" you can add it as well, as  make passes the option. 
You should not need the other vales added to the compilrt flat.

Unfortunately, I don't know any means for make to repeat the error message or cancel all remainung tasks

**Comment by mvglasow** [comment]
Thanks, I'll give it a try

**Comment by jkoan** [comment]
I think we shouldn't do anything here as it only costs time and the effect is "minimal"
