### ISSUE TITLE
Build failure converting svg to png on Debian Bullseye

### ISSUE THREAD

**Issue by fortysixandtwo** [navit-gps/navit#1065]
Hey, 
I'm currently trying to build navit (current trunk) on both my Pinephone (arm64 Debian) and my Debian VM (x86_64) and I've encountered some issues related to the generating the png icon files.

Both the VM and the pinephone run Debian Bullseye and are currently using
 the `convert` tool provided by `imagemagick-6.q16 (8:6.9.11.24+dfsg-1)`.

I've examined the generated makefiles and tried running some of the `convert` commands by hand:

country_KY.png:
```
mobian@mobian:~/git/navit/build/navit/icons$ /usr/bin/convert -background none /home/mobian/git/navit/navit/icons/country_KY.svgz -resize 32x32 /home/mobian/git/navit/build/navit/icons/country_KY.png
convert: non-conforming drawing primitive definition `polygon' @ error/draw.c/RenderMVGContent/4408.
```
gui_map.png
```
mobian@mobian:~/git/navit/build/navit/icons$ /usr/bin/convert -background none /home/mobian/git/navit/navit/icons/gui_map.svg /home/mobian/git/navit/build/navit/icons/gui_map.png
convert: unable to open image `#linearGradient4873': No such file or directory @ error/blob.c/OpenBlob/2924.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/566.
convert: non-conforming drawing primitive definition `image' @ error/draw.c/RenderMVGContent/4408.
```

country_SB.png (the convert call never seems to exit)
```
/usr/bin/convert -background none /home/mobian/git/navit/navit/icons/country_SB.svgz -resize 32x32 /home/mobian/git/navit/build/navit/icons/country_SB.png
``` 

If anyone has any idea how to get the current trunk to build on Debian, it'd be much obliged :)

**Comment by jkoan** [comment]
I got 8:6.9.2.10+dfsg-2 installed in the Pinetab, that worked. SVGs are converted with inkscape when installed, do you have this installed?

**Comment by fortysixandtwo** [comment]
D'oh!
I didn't have inkscape installed and now it's building! Thanks a lot.

I do wonder however why a lot of the other svg were being processed without inkscape.

Closing the issue
