### ISSUE TITLE
Example: receiving GEO intent sent by NAVIT on Android

### ISSUE THREAD

**Issue by mensch21** [navit-gps/navit#1073]
Hello,

is there an example (written in java, including manifest.xml) how to reveice a GEO intent sent by  NAVIT on Android?

I like to receive the lat/lon values in an Andoid app sent out by NAVIT.

Best regards
mensch21

**Comment by jkoan** [comment]
The Navit geo intent isn't special at all, it's just the geo intent from standard android like here: https://developer.android.com/guide/components/intents-common#ViewMap

For the example I didn't found anything immediately. But if you keep searching for it if hasn't anything to do with navit at this point. From my memory in the manifest if should be a intent filter for the geo protocol. And on the java side it's receiving and parsing the geo protocol like described in the link above.

**Comment by mensch21** [comment]
Great...
This is easy to implement and it works fine.

In manifest:
<intent-filter
...
        <data android:scheme="geo" />
        <category android:name="android.intent.category.DEFAULT" />
</intent-filter>

In MainAcitvity.java:
        ...
        Intent Geointent = getIntent();
        Uri UriIintentData = Geointent.getData();
        if(UriIntentData != null)
        {
            String IntentData = UriGeointentData.toString();
            // do something with geo data

And now it is really convenient and fast. In Navit I do a long click on map. After menu window pops up
I click "Ansicht" choose my application an see PDF content immediately. After I click Android back key
PDF vanishes and Navit map is back because after starting PDF (intent) I finish my application.

So now I see information about my POI directly from Navit, more or less.

Many thanks for the hints.

**Comment by mensch21** [comment]
Correction, some text got lost.
(Perhaps there is something wrong with three dots.)

            <intent-filter
                android:icon="@drawable/ic_launcher"
                android:label="@string/label"
                >
                <action android:name="android.intent.action.VIEW" />
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />

                <data android:scheme="geo" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
