### ISSUE TITLE
Build fail on RPi 4b

### ISSUE THREAD

**Issue by Budman1758** [navit-gps/navit#1080]
Attempting to install on an RPI 4.  Latest Raspberry OS. (Buster)  After installing all the dependencies (which was a challenge in and of itself) I get the following errors running cmake...  Using instructions from [here](https://navit.readthedocs.io/en/latest/development/linux_development.html).  These instructions seem a bit dated also...
Log files mentioned are attached.
It would be nice to get the latest version installed.  Any and all help here would be appreciated. 

Merry Christmas!

[CMakeError.log](https://github.com/navit-gps/navit/files/5740653/CMakeError.log)
[CMakeOutput.log](https://github.com/navit-gps/navit/files/5740654/CMakeOutput.log)

`pi@TruckPi:~/navit-build $ cmake ~/navit
-- Building with CMake V3.13.4
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- LIBDIR variable is not defined. It will be autodetected now.
-- You can set it manually with -DLIBDIR=<value>
--    LIB_DIR (highest subdirectory if LIBDIR) is set to 'lib/navit'
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
-- Checking for module 'gmodule-2.0'
--   Found gmodule-2.0, version 2.58.3
-- Checking for module 'glib-2.0>=2.10'
--   Found glib-2.0, version 2.58.3
-- Checking for module 'fontconfig >= 2.2.0'
--   Found fontconfig , version 2.13.1
-- Checking for module 'dbus-1 >= 1.4'
--   Found dbus-1 , version 1.12.20
-- Checking for module 'dbus-glib-1'
--   No package 'dbus-glib-1' found
-- Checking for module 'liblocation'
--   No package 'liblocation' found
-- Checking for module 'libosso'
--   No package 'libosso' found
-- Checking for module 'libgps'
--   Found libgps, version 3.17
-- Checking for module 'libgps>=2.90'
--   Found libgps, version 3.17
-- Checking for module 'libgps>=3.1'
--   Found libgps, version 3.17
-- Checking for module 'libgarmin'
--   No package 'libgarmin' found
-- Checking for module 'imlib2'
--   Found imlib2, version 1.5.1
-- Checking for module 'libgeoclue-2.0'
--   No package 'libgeoclue-2.0' found
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.11")
-- Found Freetype: /usr/lib/arm-linux-gnueabihf/libfreetype.so (found version "2                              .9.1")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found SDL: /usr/lib/arm-linux-gnueabihf/libSDLmain.a;/usr/lib/arm-linux-gnuea                              bihf/libSDL.so;-lpthread (found version "1.2.15")
-- Found SDL_image: /usr/lib/arm-linux-gnueabihf/libSDL_image.so (found version                               "1.2.12")
-- Found OpenGL: /usr/lib/arm-linux-gnueabihf/libGL.so
-- Found GLUT: /usr/lib/arm-linux-gnueabihf/libglut.so
-- Found GTK2_GTK: /usr/lib/arm-linux-gnueabihf/libgtk-x11-2.0.so
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1")
-- Found PNG: /usr/lib/arm-linux-gnueabihf/libpng.so (found version "1.6.36")
-- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.7m.so (found versio                              n "3.7.3")
CMake Warning at CMakeLists.txt:236 (find_package):
  By not providing "FindQt5Positioning.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5Positioning", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Positioning"
  with any of the following names:

    Qt5PositioningConfig.cmake
    qt5positioning-config.cmake

  Add the installation prefix of "Qt5Positioning" to CMAKE_PREFIX_PATH or set
  "Qt5Positioning_DIR" to a directory containing one of the above files.  If
  "Qt5Positioning" provides a separate development package or SDK, be sure it
  has been installed.

CMake Error at CMakeLists.txt:241 (find_package):
  By not providing "FindQt5Svg.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Svg", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Svg" with any
  of the following names:

    Qt5SvgConfig.cmake
    qt5svg-config.cmake

  Add the installation prefix of "Qt5Svg" to CMAKE_PREFIX_PATH or set
  "Qt5Svg_DIR" to a directory containing one of the above files.  If "Qt5Svg"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/pi/navit-build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/navit-build/CMakeFiles/CMakeError.log".`

**Comment by metalstrolch** [comment]
Seems you are missing some QT5 development packages.

If you do not even want to have QT5 support e.g. qt5 graphics and qt5 vehicle because you plan to use GTK or SDL2, you can disable QT5 support by adding "-DDISABLE_QT:BOOL=yes" to cmake command line.

If you want to have QT5 support, you should add qtpositioning5-dev and libqt5svg5-dev to your build system. But as I don't have raspbian buster, i could be wrong with the package names here.

**Comment by Budman1758** [comment]
I don't know what the difference is between QT5 and the others mentioned.  If both are enabled in "my build" I was not aware of that. I am just following the instructions on [this](https://navit.readthedocs.io/en/latest/development/android_development.html) page. I am not a developer at all. Just trying to install the newest version.  I did not modify anything in the downloaded files from Git.  

I am not one to gripe usually but I can say that the install documentation to get this up and running on Linux (Raspberry Pi) is rather lacking in detail for the average "Joe Blow" user such as myself. To say its frustrating would be close to the understatement of the year......

Trying to get this on a Pi 4b with 8 GIG RAM. What would be the best graphics system to use in this case?

**Comment by metalstrolch** [comment]
Sorry @Budman1758, Navit is developed by way too few people in way too few private free time. Some of us try to help people here, even on Christmas. But none of us is "responsible" for any thing. Rants like yours tend to drive my will to help you near zero. I have better things to do than hearing from you how frustrated you are, while you are not even trying to give details about what you are doing, nor if my suggestions helped you in any way. Period.

If you think the documentation is too bad, feel free to enhance it by adding things you think are missing here. I'm looking forward for every merge request from you about that. But sure you won't. Ranting is easier.

"Joe Blow" should use packages shipped with his distribution first. As far as I know, there is a Navit package available on buster, so why not just use that.
Try "apt-get navit". No need to roll your own.
But I may as well be wrong here. I don't have any raspberry pi. An I personally do not even care for that platform.

On your PI you can use GTK, or Qt5 or even EGL depending of the "other" software you're already using. Since it seems you have at least GTK installed I'd opt for that. I'd not use SDL on that platform as the GTK or QT graphics should perform better. EGl will be too difficult for you to set up.

**Comment by hoehnp** [comment]
@metalstrolch: From [here](https://packages.debian.org/buster/navit) I would assume that it should be available in the package manager.

**Comment by OLFDB** [comment]
> Trying to get this on a Pi 4b with 8 GIG RAM. What would be the best graphics system to use in this case?

From my experience gtk_drawing_area is the best graphics you can get with navit.

you should create a directory build inside the navit folder and cd into that. Then configure using 

cmake -Dgraphics/qt5=false ../

make 

make install

extract the attached file and copy it to ~/.navit/navit.xml and start navit

[navit_shipped_gtkgui.xml.zip](https://github.com/navit-gps/navit/files/6057214/navit_shipped_gtkgui.xml.zip)

**Comment by OLFDB** [comment]
I did a test build on Raspberry Pi Desktop. You need to change libpng12-dev to libpng-dev in the minimum dependencies and then it builds fine with cmake.
