### ISSUE TITLE
libvehicle_gpsd.so plugin_init not found

### ISSUE THREAD

**Issue by OLFDB** [navit-gps/navit#1090]
error:navit:plugin_load:can't load '/usr/local/lib64/navit/vehicle/libvehicle_gpsd.so', plugin_init not found

on Debian 10.8 

Instead of "plugin_init" there is "module_vehicle_gpsd_init" method inside the library:

nm -D /usr/local/lib64/navit/vehicle/libvehicle_gpsd.so 
                 U attr_search
                 U callback_destroy
                 U callback_list_call_attr_args
                 U callback_new_args
                 w __cxa_finalize
                 U debug_printf
                 U event_add_timeout
                 U event_add_watch
                 U event_remove_timeout
                 U event_remove_watch
                 U g_free
                 U g_malloc0
                 w __gmon_start__
                 U gmtime_r
                 U gps_close
                 U gps_data
                 U gps_open
                 U gps_read
                 U gps_stream
                 U g_strconcat
                 U g_strdup
                 U index
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 U max_debug_level
                 U memcpy
0000000000002060 T module_vehicle_gpsd_init
                 U plugin_register_category_vehicle
                 U __stack_chk_fail
                 U strchr
                 U strftime
                 U strlen

**Comment by jkoan** [comment]
Is this a self build or the official deb package?
If its a self build, which commit sha/branch was used?

**Comment by OLFDB** [comment]
It is a self build on branch _origin/OLFDB-nightlayout-tunnel_, but there is only one change in navit.c compared to the master.

**Comment by OLFDB** [comment]
And was not working without any change to the master as well. navit is giving this version info: navit 0.5.5+git:xdevxgitxnotxfound-

**Comment by martin-ac** [comment]
Hello, I have the same error message even when trying to start a local build of Navit-0.5.5 from my build folder where 'libvehicle_gpsd.so' is existing in the given path:

error:navit:plugin_load:can't load '/VAIO-Daten/navitz-0.5.5/navit/vehicle/gpsd/.libs/**libvehicle_gpsd.so**', **plugin_init not found**
error:navit:vehicle_new:invalid source 'gpsd://localhost': unknown type 'gpsd'

I think the second error line is a result of the first one.
Anyway Navit starts and the result of the error is that in settings the list of vehicles is empty.

I compiled and build on Kubuntu 20.04 and did not do any change to the source or xml's.
The Navit about screen shows exactly the same version info as given in the above comment.

Thanks in advance for your help.

**Comment by jkoan** [comment]
should be fixed now. Will be included in the next minor release
