### ISSUE TITLE
Fastlane directory uses invalid names for some locales

### ISSUE THREAD

**Issue by linsui** [navit-gps/navit#1101]
[Fastlane](https://github.com/fastlane/fastlane/blob/633860a5aae0fa9c0b936797560efb24181b1bf7/fastlane_core/lib/fastlane_core/languages.rb#L14) uses [BCP47](https://www.w3.org/International/articles/bcp47/) locale tags, which use a `-` as the separator rather than `_`. There are a number of locales that use the `_` here. Please rename those dirs to use `-`. Thanks!

For reference: F-Droid downstream [issue](https://gitlab.com/fdroid/fdroiddata/-/issues/2323).

**Comment by jkoan** [comment]
That's interesting as those are directly downloaded from with fastlane. Anyhow I will rename them as requested

**Comment by jkoan** [comment]
Fixed by 
1e32e2e

**Comment by linsui** [comment]
Thanks!
