### ISSUE TITLE
Feature request: support for brouter

### ISSUE THREAD

**Issue by apalazzi** [navit-gps/navit#1102]
brouter https://github.com/abrensch/brouter is an open source routing engine specifically aimed to cycling, with advanced features and greatly customizable; it would be nice if it could be easily used with navit.

**Comment by jkoan** [comment]
I don't think this makes sense as Navit uses its own builtin routing-engine which can also do routing for cycling. 
Also there would be a problem with the integration in general as Navit is written in C and brouter is written in Java.
