### ISSUE TITLE
F-Droid CI build failing blocking merges

### ISSUE THREAD

**Issue by metalstrolch** [navit-gps/navit#1105]
Currently the f-droid CI build fails constantly, which causes merges to be blocked. Unfortunately I don't have a clue how f-droid works so I cannot fix that. Who can help?

Thanks!

Blocks at least #1089

**Comment by mvglasow** [comment]
Seems the command that fails is this one:

    curl --silent https://gitlab.com/fdroid/fdroidserver/repository/master/archive.tar.gz | tar -xz --directory=fdroidserver --strip-components=1

and the output is:

```
2e1d11242e9439032b0119552d3f90d5d7d10a6f	refs/heads/master

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Exited with code exit status 2
```

The SHA is the latest F-Droid release.

When I open the URL, I get a 404 error. When I try to download the source archive from the Gitlab repo, the URL is https://gitlab.com/fdroid/fdroidserver/-/archive/master/fdroidserver-master.tar.gz. Changing the URL might work, will look into this (unless someone else beats me to it :-))

**Comment by mvglasow** [comment]
Should be fixed now. Apparently the download URL changed, which broke the workflow. For pending PRs, all you need to do is merge master (or trunk) into the feature branch and push, which will restart CI. For the merge, unless there is a need to have multiple commits, “squash and merge” is the preferable option to keep the history legible.
