### ISSUE TITLE
cities missing from bin produced by maptool based on osm.pbf

### ISSUE THREAD

**Issue by yeupou** [navit-gps/navit#1108]
Hello,

Using france.osm.pbf from https://download.openstreetmap.fr/extracts/ along with maptool ,0.5.5+dfsg.1-2+b1  it seems that a massive amount of cities end up missing in the resulting bin file.

Is it a known issue?

command used : 
for osm in *.osm.pbf; do maptool --input-file "$osm" --protobuf --64bit ../bin/"${osm%.*}".bin --threads `nproc`; done

Note that there is no obvious lack of memory issue, the computer used having at all time at least 10GB of memory still unused (unless the job is being done using tempfiles in tmpfs that might be too small at times)

Regards,

**Comment by yeupou** [comment]
Example of errors:

[...]
OSM Warning:http://www.openstreetmap.org/node/710451302 Lost town Le Bouchet (null)
OSM Warning:http://www.openstreetmap.org/node/710451369 Lost town Mousseau (null)
OSM Warning:http://www.openstreetmap.org/node/710463121 Lost town La Merci Dieu (null)
OSM Warning:http://www.openstreetmap.org/node/710475604 Lost town Geluwe (null)
OSM Warning:http://www.openstreetmap.org/node/710556838 Lost town Dranouter (null)
OSM Warning:http://www.openstreetmap.org/node/710559301 Lost town Nieuwkerke (null)
OSM Warning:http://www.openstreetmap.org/node/710645746 Lost town Loker (null)
OSM Warning:http://www.openstreetmap.org/node/710713105 Lost town Le Cabanis (null)
OSM Warning:http://www.openstreetmap.org/node/710726091 Lost town Le Ligat (null)
OSM Warning:http://www.openstreetmap.org/node/710739826 Lost town Les Courrayes (null)
OSM Warning:http://www.openstreetmap.org/node/710745526 Lost town Westouter (null)
OSM Warning:http://www.openstreetmap.org/node/710753682 Lost town Ten Brielen (null)
OSM Warning:http://www.openstreetmap.org/node/710765363 Lost town Houtem (null)
OSM Warning:http://www.openstreetmap.org/node/710775431 Lost town Leisele (null)
OSM Warning:http://www.openstreetmap.org/node/710776564 Lost town Izenberge (null)
OSM Warning:http://www.openstreetmap.org/node/710782173 Lost town Roesbrugge (null)
OSM Warning:http://www.openstreetmap.org/node/710798051 Lost town Haringe (null)
OSM Warning:http://www.openstreetmap.org/node/710803069 Lost town Sint-Jan Ter Biezen (null)
OSM Warning:http://www.openstreetmap.org/node/710804500 Lost town Roesbrugge-Haringe (null)
OSM Warning:http://www.openstreetmap.org/node/710855257 Lost town Adinkerke (null)
OSM Warning:http://www.openstreetmap.org/node/711004829 Lost town Le Plessis aux Grolles (null)
OSM Warning:http://www.openstreetmap.org/node/711004905 Lost town Sauvigny (null)
OSM Warning:http://www.openstreetmap.org/node/711329709 Lost town La Haye-Pesnel (null)
OSM Warning:http://www.openstreetmap.org/node/711334566 Lost town Hocquigny (null)
OSM Warning:http://www.openstreetmap.org/node/711339002 Lost town Équilly (null)
OSM Warning:http://www.openstreetmap.org/node/711458848 Lost town Les Vieilles Forges (null)
OSM Warning:http://www.openstreetmap.org/node/711458866 Lost town Chaume (null)
OSM Warning:http://www.openstreetmap.org/node/711458934 Lost town Brégoux (null)
OSM Warning:http://www.openstreetmap.org/node/711464956 Lost town La Giserie (null)
OSM Warning:http://www.openstreetmap.org/node/711464958 Lost town Brébail (null)
OSM Warning:http://www.openstreetmap.org/node/711578958 Lost town Le Val Bardou (null)
OSM Warning:http://www.openstreetmap.org/node/711778119 Lost town Le Grand Tiret (null)
OSM Warning:http://www.openstreetmap.org/node/711778147 Lost town Le Coudret (null)
OSM Warning:http://www.openstreetmap.org/node/711787574 Lost town Bénand (null)
OSM Warning:http://www.openstreetmap.org/node/711787758 Lost town Creuzaz (null)
OSM Warning:http://www.openstreetmap.org/node/712164289 Lost town La Noë (null)
OSM Warning:http://www.openstreetmap.org/node/712321899 Lost town La Meuse (null)
OSM Warning:http://www.openstreetmap.org/node/712353358 Lost town Le Vernet (null)
OSM Warning:http://www.openstreetmap.org/node/712353422 Lost town L'Estivalet (null)
OSM Warning:http://www.openstreetmap.org/node/712353531 Lost town Montchabrier (null)
OSM Warning:http://www.openstreetmap.org/node/712385380 Lost town Angreviers (Rive Gauche) (null)
OSM Warning:http://www.openstreetmap.org/node/712387677 Lost town La Motte (null)
OSM Warning:http://www.openstreetmap.org/node/712430723 Lost town Confluent (null)
OSM Warning:http://www.openstreetmap.org/node/712615235 Lost town Les Hautes Rives (null)
OSM Warning:http://www.openstreetmap.org/node/712722019 Lost town Haravilliers (null)
OSM Warning:http://www.openstreetmap.org/node/712727666 Lost town La Triloterie (null)
OSM Warning:http://www.openstreetmap.org/node/712727727 Lost town Le Heaulme (null)
OSM Warning:http://www.openstreetmap.org/node/712730197 Lost town Turin (null)
OSM Warning:http://www.openstreetmap.org/node/712748570 Lost town De Moeren (null)
OSM Warning:http://www.openstreetmap.org/node/712749088 Lost town De Barakken (null)
OSM Warning:http://www.openstreetmap.org/node/712749390 Lost town Paradijs (null)
OSM Warning:http://www.openstreetmap.org/node/712821441 Lost town Saint-Martin-de-Cenilly (null)
OSM Warning:http://www.openstreetmap.org/node/712840570 Lost town Roncey (null)
OSM Warning:http://www.openstreetmap.org/node/712842413 Lost town Berville (null)
OSM Warning:http://www.openstreetmap.org/node/712865123 Lost town La Quinte (null)
OSM Warning:http://www.openstreetmap.org/node/712876270 Lost town Les Combettes (null)
OSM Warning:http://www.openstreetmap.org/node/712876410 Lost town Mont-Follet (null)
OSM Warning:http://www.openstreetmap.org/node/712876432 Lost town Bernardière (null)
OSM Warning:http://www.openstreetmap.org/node/712969101 Lost town La Bouette (null)
OSM Warning:http://www.openstreetmap.org/node/713090015 Lost town La Petite Age (null)
OSM Warning:http://www.openstreetmap.org/node/713210671 Lost town Le Falgoux (null)
OSM Warning:http://www.openstreetmap.org/node/713215693 Lost town Saint-Cernin (null)
OSM Warning:http://www.openstreetmap.org/node/713221487 Lost town Thiézac (null)
OSM Warning:http://www.openstreetmap.org/node/713258567 Lost town Le Moulin de Chambon (null)
OSM Warning:http://www.openstreetmap.org/node/713291248 Lost town Quevaucamps (null)
OSM Warning:http://www.openstreetmap.org/node/713325014 Lost town La Croix (null)
OSM Warning:http://www.openstreetmap.org/node/713340966 Lost town La Blanchardière (null)
OSM Warning:http://www.openstreetmap.org/node/713347374 Lost town Chaussadis (null)
OSM Warning:http://www.openstreetmap.org/node/713352574 Lost town Fourmagne (null)
OSM Warning:http://www.openstreetmap.org/node/713398664 Lost town La Morcellière (null)
OSM Warning:http://www.openstreetmap.org/node/713398668 Lost town La Garenne (null)
OSM Warning:http://www.openstreetmap.org/node/713398670 Lost town La Tour (null)
OSM Warning:http://www.openstreetmap.org/node/713398671 Lost town La Custière (null)
OSM Warning:http://www.openstreetmap.org/node/713398675 Lost town La Briolletrie (null)
OSM Warning:http://www.openstreetmap.org/node/713398676 Lost town La Salvardrie (null)
OSM Warning:http://www.openstreetmap.org/node/713398678 Lost town La Babinière (null)
OSM Warning:http://www.openstreetmap.org/node/713398680 Lost town La Guignardière (null)
OSM Warning:http://www.openstreetmap.org/node/713399374 Lost town La Gounière (null)
OSM Warning:http://www.openstreetmap.org/node/713400671 Lost town La Fougère (null)
OSM Warning:http://www.openstreetmap.org/node/713400672 Lost town Mousseaux (null)
OSM Warning:http://www.openstreetmap.org/node/713400674 Lost town Les Hauts Mousseaux (null)
OSM Warning:http://www.openstreetmap.org/node/713409804 Lost town Baumescure (null)
OSM Warning:http://www.openstreetmap.org/node/713450516 Lost town Courrèges (null)
OSM Warning:http://www.openstreetmap.org/node/713454878 Lost town La Boissière (null)
OSM Warning:http://www.openstreetmap.org/node/713462555 Lost town Le Maffre (null)
OSM Warning:http://www.openstreetmap.org/node/713466916 Lost town Virazels du Larzac (null)
OSM Warning:http://www.openstreetmap.org/node/713521856 Lost town Sévigny (null)
OSM Warning:http://www.openstreetmap.org/node/713521858 Lost town Bailleul (null)
OSM Warning:http://www.openstreetmap.org/node/713522807 Lost town Bierre (null)
OSM Warning:http://www.openstreetmap.org/node/713570562 Lost town Le Haut de Nécy (null)
OSM Warning:http://www.openstreetmap.org/node/713576750 Lost town Le Bosq (null)
OSM Warning:http://www.openstreetmap.org/node/713707064 Lost town Aubusson (null)
OSM Warning:http://www.openstreetmap.org/node/713721477 Lost town Les Sarles (null)
OSM Warning:http://www.openstreetmap.org/node/713721742 Lost town Barrideau (null)
OSM Warning:http://www.openstreetmap.org/node/713721806 Lost town Letieux (null)
OSM Warning:http://www.openstreetmap.org/node/713721946 Lost town Ballissac (null)
OSM Warning:http://www.openstreetmap.org/node/713722096 Lost town Bosc (null)
OSM Warning:http://www.openstreetmap.org/node/713722099 Lost town Chovozo (null)
OSM Warning:http://www.openstreetmap.org/node/713881166 Lost town La Haute Pissote (null)
OSM Warning:http://www.openstreetmap.org/node/713914775 Lost town Le Breuil (null)
OSM Warning:http://www.openstreetmap.org/node/713951645 Lost town Roquesquatre (null)
OSM Warning:http://www.openstreetmap.org/node/714104663 Lost town Livilliers (null)
OSM Warning:http://www.openstreetmap.org/node/714170146 Lost town Carrefour de l’Hostellerie (null)
OSM Warning:http://www.openstreetmap.org/node/714172837 Lost town L'Anjourière (null)
OSM Warning:http://www.openstreetmap.org/node/714172845 Lost town Le Port (null)
OSM Warning:http://www.openstreetmap.org/node/714172851 Lost town La Birochère (null)
OSM Warning:http://www.openstreetmap.org/node/714172862 Lost town La Normandière (null)
OSM Warning:http://www.openstreetmap.org/node/714235858 Lost town La Vergne (null)
OSM Warning:http://www.openstreetmap.org/node/714684645 Lost town Apremont (null)
OSM Warning:http://www.openstreetmap.org/node/715077060 Lost town Le Pégier (null)
OSM Warning:http://www.openstreetmap.org/node/715077098 Lost town Le Saix (null)
OSM Warning:http://www.openstreetmap.org/node/715077190 Lost town Gardiolette (null)
OSM Warning:http://www.openstreetmap.org/node/715077237 Lost town La Magdelaine (null)
OSM Warning:http://www.openstreetmap.org/node/715100112 Lost town Theizé (null)
OSM Warning:http://www.openstreetmap.org/node/715120606 Lost town La Cave Haute (null)
OSM Warning:http://www.openstreetmap.org/node/715120836 Lost town Mas del Camp (null)
OSM Warning:http://www.openstreetmap.org/node/715121022 Lost town La Cave Basse (null)
OSM Warning:http://www.openstreetmap.org/node/715144869 Lost town Fuchsloch (null)
OSM Warning:http://www.openstreetmap.org/node/715202334 Lost town Saint-Calais-du-Désert (null)
[...]


```
$ export LC_ALL=C && df -h
Filesystem                  Size  Used Avail Use% Mounted on
udev                         16G     0   16G   0% /dev
tmpfs                       3.2G  1.6M  3.2G   1% /run
/dev/mapper/250g21devuan64  214G  134G   69G  66% /
tmpfs                       5.0M   12K  5.0M   1% /run/lock
tmpfs                       6.3G  171M  6.1G   3% /dev/shm
/dev/mapper/4t15home        3.6T  1.2T  2.4T  32% /home
tmpfs                       6.3G  613M  5.7G  10% /tmp
cgroup_root                  10M     0   10M   0% /sys/fs/cgroup
tmpfs                        50M  8.7M   42M  18% /var/log
tmpfs                        50M  5.1M   45M  11% /var/spool
tmpfs                       3.2G     0  3.2G   0% /run/user/0
tmpfs                       3.2G   36K  3.2G   1% /run/user/1000
```


 ```
vmstat 
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 0  0  91492 8637300 199688 17113392    0    0   210  1107   68   63 10  3 84  3  0
```


No memory issue, no swapping.

**Comment by metalstrolch** [comment]
Yes, this is known but most probably the error messages are misleading.

This error occurs on the stage when maptool tries to assign cities to countries and their administrative sub regions using the is_in tags or the border relations around them. 
So the "lost towns" could just not being collected into the search directory. Thus you cannot find them on "town" search. But they may be in map knowing where they are.

So those have
 - no administartive border relation that is a closed circle around them
 - no is_in tag at all
 - wrong is_in tag

Since you're using a map excerpt, there are a lot of towns at the border of your excerpt where the surrounding relation is broken (because of parts of it being cut-off). And the posted ones mostly have no is_in at least.

**Comment by yeupou** [comment]
Hi there,

Most of the maps there are away from country borders but I guess they do have no is_in.
However, on my final map (.bin) opened within navit, I miss thousands of town. Could that be unrelated?

**Comment by stephan75** [comment]
IMHO the is_tag is deprecared for years already!?

**Comment by yeupou** [comment]
Is there any way to check list of town identified in a bin, besides from trying to open it in navit, in order to understand if the bin itself is valid?

**Comment by metalstrolch** [comment]
is_in is not deprecated. It's considered "not required where administrative boundaries are fully mapped" according to https://wiki.openstreetmap.org/wiki/Key:is_in . However when dealing with map excerpts, the boundaries are most probably not intact which is causing the mentioned problems. Is_in is only one means beyond others to get places to search index.

Well, I IMHO don't know of any tools that will let you do what you want, but you could create yourself based on e.g. the binfile extractor (https://github.com/metalstrolch/navit_binfile_extractor) and navit source for index. Should not be that hard. But may be just opening in Navit may be easier today.

@yeupou , could you please retest on your side with the France excerpt from Geofabrik https://download.geofabrik.de/europe/france-latest.osm.pbf since https://download.openstreetmap.fr/extracts/  is horribly slow to download from at least here. It will finish downloading in roughly 2 days estimated.
I'll have a run on the Geofabrik based one as well. I'll report back my results, but usually those excerpts are fine.

**Comment by metalstrolch** [comment]
@yeupou , could you please check your log for an entry like that:
"Broken country polygon 'FR'"

**Comment by yeupou** [comment]
@metalstrolch 

I'll try with these. 

Note that download speed from  https://download.openstreetmap.fr/extracts/ depends a lot on which mirror you end up. I noticed a few times that some mirrors picked by default are, as you said, very slow, but cancelling the download and restarting immediately usually allowed me to switch to a suitable mirror.

**Comment by metalstrolch** [comment]
Finished processing the Geofabric OSM excerpt. there were 1149 lost towns. All of them I checked are actually outside of France.
Seems maptool does fine here. I assume a problem with the data on  https://download.openstreetmap.fr/extracts/. Still downloading, 2 days to wait.
[geofabrik-france-latest.log](https://github.com/navit-gps/navit/files/6291788/geofabrik-france-latest.log)

**Comment by yeupou** [comment]
Ok, that's odd, not sure what I did but now I guess a yellow screen no matter the map (especially with a the german map that should have the default navit area) and no city listed at all in search.

Looks like my setup is completely broken. So maybe that the root of the current issue, maybe not a maptool related issue.

Nothing obvious in starting navit -d 2

**Comment by metalstrolch** [comment]
after downloading it, it's proven. The excerpt from https://download.openstreetmap.fr/extracts/  is broken.

`OSM Warning:http://www.openstreetmap.org/relation/2202162 Broken country polygon 'FR'`

592102 lost towns. Obvious because the border polygon is broken. Mystery solved. Definitive not a maptool issue.

The log is too bog to add it unzipped.
[france-latest.log.zip](https://github.com/navit-gps/navit/files/6296488/france-latest.log.zip)

**Comment by yeupou** [comment]
Ok, so that's good to know (unclear where it should be reported but it make whole https://download.openstreetmap.fr/extracts/ purpose moot).

So, indeed, not a maptool issue.

**Comment by jkoan** [comment]
> So, indeed, not a maptool issue.

So this issue can be closed?

**Comment by yeupou** [comment]
Sure. Thanks for the extensive tests.
