### ISSUE TITLE
Logging in to trac seems to be broken

### ISSUE THREAD

**Issue by l29ah** [navit-gps/navit#1127]
http://trac.navit-project.org/openidlogin via google, openid-then-using-google-openid-url, and wordpress doesn't work. Clicking the "Sign up" link results in
```
Permission error

You do not have permission to do that, for the following reason:

You are not allowed to execute the action you have requested.
```

**Comment by jkoan** [comment]
You need to choose custom openid (the green person) and use your wiki link which will be displayed on the top of your user page. 
But New issues should not be opened on trac any more.

**Comment by l29ah** [comment]
> But New issues should not be opened on trac any more.

Then guidelines at https://wiki.navit-project.org/index.php/Reporting_Bugs should be adjusted.

**Comment by jkoan** [comment]
> > But New issues should not be opened on trac any more.
> 
> Then guidelines at https://wiki.navit-project.org/index.php/Reporting_Bugs should be adjusted.

Done, thanks for the hint
