### ISSUE TITLE
enable_expression="vehicle.position_valid" not working

### ISSUE THREAD

**Issue by jkrzyszt** [navit-gps/navit#1130]
I can see 'enable_expression="vehicle.position_valid"' used in navit/xslt/osd_minimum.xslt but it doesn't work for me as expected when I use it in my navit.xml.  Is it still valid?  If not, is there a replacement?

Thanks,
Janusz

**Comment by mvglasow** [comment]
Just have it a brief test on Android; it works as expected for me. (I added these OSD elements a while back; the attribute is not my work, though.)

Compass and current street name remain hidden until the device gets its first position; only then do they show. On Android specifically, if you have network-based location, the first position update will be received within a few seconds. (Without network location, this will not happen until the GPS gets a fix, which may take some time.) If the device loses its fix (e.g. when your only source of location data is GPS and you are in a tunnel), the attribute is **not** cleared, i.e. Navit will still assume it has a valid position.

However, this attribute is set in the vehicle implementation, which differs from platform to platform.

Which platform are you on (and, if you know, which vehicle implementation do you use)? What behavior are you seeing – do compass and current street name OSDs show before you receive the first location update, or do they fail to show?

**Comment by jkrzyszt** [comment]
I'm running on linux, vehicle gpsd.  Compass shows immediately, befre GPS gets a fix.  Current street name - I'm not sure, but probably the same.  Regarding other vehicle attributes, vehicle.posititon_coord_geo shows up immediately (0, 0 before the first fix), but e.g. vehicle.position_time_iso8601 is rendered blank before the first fix.

What matches your description is that the attribute seems to persist across fix loss -- that's not a problem for me.

My goal is to hide a button with command="set_center_cursor()" until the fix is acquired.

**Comment by OLFDB** [comment]
vehicle gpsd doesn't support this attribute.

You can try this change on trunk:

```
diff --git a/navit/vehicle/gpsd/vehicle_gpsd.c b/navit/vehicle/gpsd/vehicle_gpsd.c
index 9dbc18aa4..7b4939772 100644
--- a/navit/vehicle/gpsd/vehicle_gpsd.c
+++ b/navit/vehicle/gpsd/vehicle_gpsd.c
@@ -378,6 +378,9 @@ static int vehicle_gpsd_position_attr_get(struct vehicle_priv *priv,
         enum attr_type type, struct attr *attr) {
     struct attr * active=NULL;
     switch (type) {
+    case attr_position_valid:
+       attr->u.num=(priv->fix_type>0?attr_position_valid_valid:attr_position_valid_invalid);
+       break;
     case attr_position_fix_type:
         attr->u.num = priv->fix_type;
         break;

```
as a quick fix. For me that is working on trunk for Ubuntu with gpsd/focal 3.20-8 amd64

Let me know if it works for you as well.

**Comment by jkrzyszt** [comment]
Thanks, I'll give it a try in a few days and report back.

**Comment by jkrzyszt** [comment]
With the patch applied, references to vehicle.position_valid seem do return true/false for vehicle_gpsd, However, I would expect true is returned as soon as GPS fix i acquired, while it seems to require some movement first.  Is that by design?  If yes, what are my other options?

My goal is to hide a button that calls set_center_cursor() (or prevent it from calling that function at least) for as long as that would result in jumping to coordinates (0, 0), and show the button (or make it actually call the function) as soon as some non-default position coordinates are available for set_center_cursor() to use.

Thanks,
Janusz

**Comment by OLFDB** [comment]
Can you add:

```
diff --git a/navit/vehicle/gpsd/vehicle_gpsd.c b/navit/vehicle/gpsd/vehicle_gpsd.c
index 9dbc18aa4..97c1aebf3 100644
--- a/navit/vehicle/gpsd/vehicle_gpsd.c
+++ b/navit/vehicle/gpsd/vehicle_gpsd.c
@@ -177,6 +177,7 @@ vehicle_gpsd_callback(struct gps_data_t *data, const char *buf, size_t len,
     }
     if (data->set & MODE_SET) {
         priv->fix_type = data->fix.mode - 1;
+        dbg(lvl_info,"Fix Mode: %i", priv->fix_type);
         data->set &= ~MODE_SET;
```

So you can see when it is set to >0 ? You need at least a 2D fix, not just NMEA data sent by the device.
