### ISSUE TITLE
Fresh install of Navit will not start up

### ISSUE THREAD

**Issue by kontrarie** [navit-gps/navit#1139]
On a newly installed laptop with Ubuntu 21.04 = Hirsute Hippo I installed navit with a simple "apt install navit" ; this provided packages

ii  navit                                      0.5.5+dfsg.1-2build1                                                 amd64        Car navigation system with routing engine
ii  navit-data                                 0.5.5+dfsg.1-2build1                                                 all          Car navigation system with routing engine - data files
ii  navit-graphics-gtk-drawing-area            0.5.5+dfsg.1-2build1                                                 amd64        Car navigation system with routing engine - GTK+ graphic plugin
ii  navit-gui-internal                         0.5.5+dfsg.1-2build1                                                 amd64        Car navigation system with routing engine - internal GUI

When I start it, I get an error message:
navit -d1
error:navit:traffic_new:wrong type 'null'
I cannot find an entry for traffic_new in the config file.
What I am doing wrong?

**Comment by OLFDB** [comment]
In the log entry `error:navit:traffic_new:wrong type 'null'` traffic_new is the function that is logging, not the attribute.

The attribute handled here is traffic. For Linux the type is null by default. 

```
<!-- Traffic -->
		<traffic type="null"/>
```

You can just ignore this error. If the software doesn't startup, there should be more log entries. 

Can you share them?

**Comment by kontrarie** [comment]
Thanks for looking into the matter! I'm afraid there is not much more to report. Only I may have expressed my issue poorly: the program does start up, and produces its usual screen; it is however blank (could send a screen copy if you tell me where to send it).
When running with -d2 it periodically produces 
    info:navit:route_set_position_from_tracking:enter
    info:navit:route_set_position_from_tracking:ret
    info:vehicle_gpsd:vehicle_gpsd_callback:speed ok
    info:navit:tracking_update:Static speed: 5, static distance: 25
which looks rather healthy?

Here is what I get with the original navit.xml file:
karel@schal:~/.navit$ navit -d1
error:navit:traffic_new:wrong type 'null'
warning:graphics_gtk_drawing_area:get_data:Failed to open iPaq sleep file. Error-Code: 10

I had a modified config, in which the buttons for zooming in and out were uncommented, and these do show. Also I activated another map data file, and this produced a warning, but I had learned to ignore those:

karel@schal:~/.navit$ navit -d1
error:navit:traffic_new:wrong type 'null'
warning:map_binfile:binfile_read_eoc64:map file /opt/adelco/navit/benelux.bin: eocl wrong
warning:graphics_gtk_drawing_area:get_data:Failed to open iPaq sleep file. Error-Code: 10
warning:navit:osd_std_calculate_sizes:cannot get padding for item=0x55e1b366c730: item->gr is NULL
warning:navit:osd_std_calculate_sizes:cannot get padding for item=0x55e1b366c170: item->gr is NULL

Need to add that originally I got an error
error:navit:xinclude:Unable to include '/home/karel/.navit/navit_layout_*.xml'
I worked around this with
touch home/karel/.navit/navit_layout_dummy.xml
but perhaps something more substantial needs to be added? I could not locate any *layout*xml files, though.

**Comment by jkoan** [comment]
Is the blank screen has a yellow tone to it the most possible cause is that you are missing maps.
Does a menu show up when you are tapping/clicking on the blank screen?

**Comment by kontrarie** [comment]
I thought of missing maps, too. The background is indeed pale yellow-ish. And yes, when clicking in it then the usual "main menu" shows up.

OTOH the bin file that I use in my own config was freshly downloaded; and with the original config from the distributed package I get the exact same result; even when setting the location to the default 11.5666 48.1333 through the menu. I observed however that the maps directory as supplied with the distributed package is empty... (/usr/local/navit/maps/)

How to start with as "known good" map?

**Comment by jkoan** [comment]
Probably the maps are not configured right. I think the default config assumes a xml file within the maps directory to configure each map individually.
I would recommend to configure maps within the main maps.xml like described here: https://navit.readthedocs.io/en/v0.5.6/maps.html

**Comment by jkoan** [comment]
Oh sorry, i missed two things from your previous comment. 

> karel@schal:~/.navit$ navit -d1
> error:navit:traffic_new:wrong type 'null'
> warning:map_binfile:binfile_read_eoc64:map file /opt/adelco/navit/benelux.bin: eocl wrong
> warning:graphics_gtk_drawing_area:get_data:Failed to open iPaq sleep file. Error-Code: 10
> warning:navit:osd_std_calculate_sizes:cannot get padding for item=0x55e1b366c730: item->gr is NULL
> warning:navit:osd_std_calculate_sizes:cannot get padding for item=0x55e1b366c170: item->gr is NULL
> 
The "eocl wrong" actually dosnt look good, as this means navit couldn't read the zip64 Contants (our binfiles are really just zipfiles with binary tiledate in them)
> Need to add that originally I got an error
> error:navit:xinclude:Unable to include '/home/karel/.navit/navit_layout_*.xml'
> I worked around this with
> touch home/karel/.navit/navit_layout_dummy.xml
> but perhaps something more substantial needs to be added? I could not locate any _layout_xml files, though.
For the Layout files, yes, they are missing from the debian/ubuntu packages. You can download them from here and put them in the appropriate place. You need at least one of the 7 "navit_layout_*.xml" Files. Otherwise Navit could not display anything, as the layouts define how to display every map item. https://github.com/navit-gps/navit/tree/1e32e2ed7d76851dcfcef95280d52bb8693c6c08/navit

**Comment by kontrarie** [comment]
Solved! It was indeed the lack of a usable layout file that blocked it all.
For your info, here is what I new get upon invocation, the "eocl" error is not really bad, apparently since it works neatly.

karel@schal:~/.navit$ navit -d1
error:navit:traffic_new:wrong type 'null'
warning:map_binfile:binfile_read_eoc64:map file /opt/adelco/navit/benelux.bin: eocl wrong
warning:graphics_gtk_drawing_area:get_data:Failed to open iPaq sleep file. Error-Code: 10
warning:navit:osd_std_calculate_sizes:cannot get padding for item=0x558207a46ae0: item->gr is NULL
warning:navit:osd_std_calculate_sizes:cannot get padding for item=0x558207a46520: item->gr is NULL
error:navit:graphics_image_new_scaled_rotated:No image for '/usr/share/navit/textures/cemetery.png'
error:navit:graphics_image_new_scaled_rotated:No image for '/usr/share/navit/textures/scrub.png'
error:navit:graphics_image_new_scaled_rotated:No image for '/usr/share/navit/textures/wood.png'
error:navit:graphics_image_new_scaled_rotated:No image for '/usr/share/navit/textures/wetland.png'

Many thanks! Keep up the good work!
