### ISSUE TITLE
Q: A copy of the default navit.xml?

### ISSUE THREAD

**Issue by treqzct** [navit-gps/navit#1146]
Where can one find a copy of the **navit.xml** that navit uses by default if no navit.xml file is supplied?

**Comment by hoehnp** [comment]
@treqzct, first of all thank you for your question. However, for answering it would be helpful to know the platform you are refering to.

**Comment by treqzct** [comment]
I'm on Android 7. But if I have to pull it from the code base that'd be fine too. Thanks

**Comment by jkoan** [comment]
The navit.xml can be found here: https://github.com/navit-gps/navit/blob/trunk/navit/navit_shipped.xml 
However normally during the build some xslt's are applied from here: https://github.com/navit-gps/navit/tree/trunk/navit/xslt
Additionally you need the layout files from here: https://github.com/navit-gps/navit/tree/trunk/navit called navit_layout_*.xml
