### ISSUE TITLE
maptool aborts with failed assertion

### ISSUE THREAD

**Issue by mvglasow** [navit-gps/navit#1147]
### Steps to reproduce:

1. Grab an OSM extract from Geofabrik (https://download.geofabrik.de/)
2. Try to process it with maptool, e.g. `maptool [--protobuf] -i /path/to/input /path/to/output.bin`

### Expected result:

A binfile map is produced.

### Actual result:

No binfile map is produced and the last lines of output look like the following:

```
PROGRESS9: Processed 21793 nodes (21708 out) 0 ways 0 relations 0 tiles 2:14 27 MB
process_multipolygons:process (thread 0)
process_multipolygons:finish (thread 0)
maptool: /home/michael/src/navit/navit/maptool/itembin.c:93: item_bin_copy_attr: Assertion `attr == attr_osm_wayid' failed.
```

### Versions:

e071fb1 on Ubuntu 20.04

### Further information:

I tried this with different data files, both in Protobuf and OSM format, as well as for different extracts (Lithuania, Latvia and Liechtenstein, latest version as of this writing). Each time I got the same error at the end. 

Since #1129 introduced a bug in multiploygon processing (which #1143 should have fixed), I also tried ea5a86b (last commit before #1129); same error here.

I then retried on PBF data from 2019 (which I remember successfully converting back then) – same error.

**Comment by mvglasow** [comment]
I tried to figure out where this bug got introduced.

36506bbd (Sept 2019) presumably was OK – this was my commit with changes to maptool, which I would have tested back then. Alas, it no longer builds on Ubuntu 20.04 because of a type mismatch in `vehicle_gpsd`.

a66b662f7 (May 2020) is the oldest commit I got to build, and it has the bug described above. Older versions no longer build on 20.04 because of two issues: some SVGs being incompatible with librsvg > 2.47 (fixed in a66b662f7), and there is the type mismatch in `vehicle_gpsd`, apparently brought about by a new gpsd version and fixed in df8c2e319.

If someone has an idea what could be causing this bug, any input is welcome. Otherwise, I will need to try some surgery to get older commits to build and find out where this bug got introduced.

a66b662f7 (April 2020, parent of a66b662f7)

**Comment by metalstrolch** [comment]
This is once more one of the Heisenbugs of the maptool. I am processing maps (most time whole planet) around once per three months ever since I got the 100MBit line in 2018. And I never had such issues. Now I rechecked with lithuania from Geofabrik.de and it converts fine. I am on Gentoo Linux using the latest trunk version as of today (e071fb187020c81d0cc0de190cb4b7c60e589ce8)

Long story short: I cannot reproduce this. What's wrong with Ubuntu. I'll try to investigate, but as long as I cannot reproduce this may be hard.

**Comment by metalstrolch** [comment]
What arch are you on? x86_64?

**Comment by jkoan** [comment]
@metalstrolch do you have assertions enabled (a Debug build)? I got this assertion every time regrading the data converted. But never created a ticket as i always forgot to do so.
On Release builds assertions are disabled as far i know

**Comment by metalstrolch** [comment]
Yes that's the thing. I do not have assertions enabled. I think that's the difference.

**Comment by metalstrolch** [comment]
Seems we should re-think the usefulness of this assertion.

**Comment by metalstrolch** [comment]
See description of #1149

**Comment by mvglasow** [comment]
Weird that this worked before, as I don’t remember fiddling with any parameters that look related. Anyways, I got it to work and after a brief test on a small extract, I am now waiting as the map of Europe is being processed. Thanks for the prompt solution!
