### ISSUE TITLE
How to use maptool？

### ISSUE THREAD

**Issue by Guan-ji** [navit-gps/navit#1150]
### How to use maptool？
I use`sudo apt-get install navit` to install navit, I downloaded the OSM map, the format is osm.bz2.

When I use maptool for format conversion, I get `command not found: maptool`

I guess this is caused by not installing maptool, but how to install it?

I also tried to install navit directly with cmake, but the result has not changed...

**Comment by mvglasow** [comment]
If you are building Navit yourself (no need to install it), `maptool` should be in a subdir of your build dir named `navit/maptool`. You would then need to run maptool with a full path, e.g. `~/navit-linux-builddir/navit/maptool/maptool ARGS`.

For a list of command line args, see https://github.com/navit-gps/navit/blob/trunk/navit/maptool/maptool.c#L271 (I guess we should document than somewhere...)

@aerostitch did the packaging for Debian; maybe he knows more about this (does the package include maptool at all? should we ensure it is on one of the default paths?)

**Comment by treqzct** [comment]
> does the package include maptool at all?

On Debian 10, there are two separate packages **navit** and **maptool**. Navit, by default, **suggests** to install maptool but does not install it by default.

**Comment by Guan-ji** [comment]
> If you are building Navit yourself (no need to install it), `maptool` should be in a subdir of your build dir named `navit/maptool`. You would then need to run maptool with a full path, e.g. `~/navit-linux-builddir/navit/maptool/maptool ARGS`.
> 
> For a list of command line args, see https://github.com/navit-gps/navit/blob/trunk/navit/maptool/maptool.c#L271 (I guess we should document that somewhere...)
> 
> @aerostitch did the packaging for Debian; maybe he knows more about this (does the package include maptool at all? should we ensure it is on one of the default paths?)

Thank you, mvglasow.
I only have four files in `/navit-build/navit/maptool`, 
1 CMakeFiles/CMakeDirectoryInformation.cmake 
2 CMakeFiles/progress.marks
3 cmake_install.cmake
4 Makefile

And I installed navit this way,https://wiki.navit-project.org/index.php/Linux_development. So I still can't use maptool. 

Actually I cannot download Navit binfile. So I downloaded the map file in osm.bz2 format and tried to convert it to bin format with maptool.

Could it be the cause of the os? My os is Manjaro 21.1.2 Pahvo. But I use `sudo apt-get install navit` in raspbian, I also can't use maptool.

**Comment by Guan-ji** [comment]
> > does the package include maptool at all?
> 
> On Debian 10, there are two separate packages: **navit** and **maptool**. Navit **suggests** to install maptool but does not install it by default.

Could you tell me how to install maptool? I got the maptool installation package **maptool.1.gz** here, http://manpages.ubuntu.com/manpages/precise/man1/maptool.1.html
But i don't know how to install maptool...

**Comment by jkoan** [comment]
> Could you tell me how to install maptool? I got the maptool installation package **maptool.1.gz** here, http://manpages.ubuntu.com/manpages/precise/man1/maptool.1.html
> But i don't know how to install maptool...

maptool.1.gz is just the manual Page. On Linux you normaly dont want to install things manually. Normally you would use the distributions package manager. For Debian the command would be `apt install maptool`

**Comment by treqzct** [comment]
> But I use sudo apt-get install navit in raspbian, I also can't use maptool.
> Could you tell me how to install maptool?

You do it the same way as you did when installing navit. Try: `sudo apt-get install maptool`

**Comment by Guan-ji** [comment]
> > Could you tell me how to install maptool? I got the maptool installation package **maptool.1.gz** here, http://manpages.ubuntu.com/manpages/precise/man1/maptool.1.html
> > But i don't know how to install maptool...
> 
> maptool.1.gz is just the manual Page. On Linux you normaly dont want to install things manually. Normally you would use the distributions package manager. For Debian the command would be `apt install maptool`

Thanks, but I cannot install maptool through **apt** or **yay** in **RPI** and **Manjaro**, Maybe it's a problem with the software source, I tried to add other software sources, but the results did not change. Maybe there is another way to install maptool? Or is there any other way to get the map in Navit binfile format？

**Comment by Guan-ji** [comment]
> > > Could you tell me how to install maptool? I got the maptool installation package **maptool.1.gz** here, http://manpages.ubuntu.com/manpages/precise/man1/maptool.1.html
> > > But i don't know how to install maptool...
> > 
> > 
> > maptool.1.gz is just the manual Page. On Linux you normaly dont want to install things manually. Normally you would use the distributions package manager. For Debian the command would be `apt install maptool`
> 
> Thanks, but I cannot install maptool through **apt** or **yay** in **RPI** and **Manjaro**, Maybe it's a problem with the software source, I tried to add other software sources, but the results did not change. Maybe there is another way to install maptool? Or is there any other way to get the map in Navit binfile format？

solved！！Because my os in RPI is 32-bit, but maptool requires arm64.
