### ISSUE TITLE
Incompatible translation license change

### ISSUE THREAD

**Issue by comradekingu** [navit-gps/navit#1158]
@jkoan
The core translation component was changed from AGPLv3+ to GPLv2+
https://hosted.weblate.org/changes/?component=navit-core&project=navit-test&lang=&action=55&user=&start_date=&end_date=

That is not a compatible change. Going all AGPLv3+ is.
#779 is relevant

**Comment by jkoan** [comment]
The Weblate project you are referring to is just a test for now, and I imported the current state of our translations. Which as far I know are GPLv2 licensed. I just incorrectly configured the initial project load to I adjusted it in the change you linked. Also the navit-test project will be deleted shortly as it is just for testing if Weblate is a suitable translation platform as the current solution launchpad is nether integrated nor stability usable
