### ISSUE TITLE
How to dynamically update the HMI parameters

### ISSUE THREAD

**Issue by ThomasChen98** [navit-gps/navit#1164]
Hi, we are using Navit for our student project. We implemented our own navigation algorithm and used Navit as a graphical display software. We customized the HMI layout in Navid.xml but we do not know how to dynamically update those numbers and display these numbers in real-time (i.e., display real-time weather forecast and the time of the day at the bottom)

For now, we hard-coded everything as follows. All the numbers are fixed in the Navit.xml file. We found a way to dynamically update the Navit.xml file with real-time data already in Python, but we don't know how to re-render the display. So even if the Navit.xml file has new parameters, the display will still have initial values.
![Screenshot from 2021-10-16 14-02-44](https://user-images.githubusercontent.com/29134164/138930894-d8555fe6-2f21-42d5-840e-8473b8ed0225.png)
).

**Comment by metalstrolch** [comment]
The navit.xml file is not reevaluated during run time, so your approach to update it on the fly is doomed to fail. Most probably you need to write your own navit plugin that reads the values to navit. You can make navit even show positions (POIs) on map that way. Have a look at old "pedestrian" plugin, that was indeed planned to form a "multiplayer game" but it forms a good template on how plugin code doing what you want may look like.

**Comment by jkoan** [comment]
Closing here as dynamic updates from the configuration are not currently planned. A alternative is to write a navit plugin and update the values at runtime
