### ISSUE TITLE
Build on sudo apt install navit for raspberry pi yellow screen

### ISSUE THREAD

**Issue by xizero** [navit-gps/navit#1166]
![Capture](https://user-images.githubusercontent.com/548388/143311511-b85fac4d-b90d-4740-8c60-a89fa6557c7a.JPG)
![Capture2](https://user-images.githubusercontent.com/548388/143311527-038a0a1a-a448-486f-8d08-528e6a8f3e0d.JPG)
### Thanks for opening an issue on Navit. Before submitting a bug report, please read the documentation on what to provide here:
https://wiki.navit-project.org/index.php/Reporting_Bugs

had an issue with using the version installed on raspbian --- 
yellow screen even with all the maps etc working .. no map showed ... 

reinstalled  .. and found that the "layouts" were missing from the build the default "route" layout that shipped with the package doesn't work.

if your gps is working and your maps are properly sorted, if all else fails ..

  i recompiled from the source which worked .. found that layouts are there so copied them and it started working.

[navit_layout_car.zip](https://github.com/navit-gps/navit/files/7598605/navit_layout_car.zip)
to get it working extract this to this folder /home/pi/.navit  and in the  app select the car layout

**Comment by hoehnp** [comment]
Thank you for reporting this bug. However, as you state it is installed via apt install. As you mention that compiling from source works, it clearly indicates it is a problem of the Raspbian package. Therefore, I would ask you to file a bug at the Raspbian project instead and close the bug here.
