### ISSUE TITLE
unable to render maps with 0.5.6/0.5.6 Raspbian+Devuan -  but cites are properly listed

### ISSUE THREAD

**Issue by yeupou** [navit-gps/navit#1168]
Hi,

I am trying to use navit on raspbian, that only includes 0.5.5 version. I test also on Devuan with 0.5.6.
I use gtk_draw_area.

GPS seems fine, it gives my actual coordinates, but no matter which map I use (bin downloaded from http://maps9.navit-project.org/, bin built out of osm files with maptool), I only get yellow background as if no map was charged, while I am sure I ask to show an area that should be included in the map.

I even tried with planet-nnnn.bin, same deal.

It is worth noting that searching town gives me a full list of towns, so it is not as if the map was not read (since the town list comes from there, no?)

How to debug this?

Only visible error is:
error:map_textfile:get_line:Unable to get line (No child process)

Regards,

**Comment by jkoan** [comment]
Could you please verify that the layouts are loaded property? If the map stays yellow the problem is most likely that those are not properly loaded.

**Comment by yeupou** [comment]
Ahem! Ok, for some reason, the Debian readme only mention the requirement to download the maps.
This debian packaging bug was already reported one year ago https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=967960

Indeed, I was missing the layout files. 

Thanks for your assistance.
