### ISSUE TITLE
Navit : graphical roadmap = yellow screen.  But textual roadmap is OK.

### ISSUE THREAD

**Issue by jemilambi** [navit-gps/navit#1169]
Hello,

Navit knows my route to destination.  But does not display graphically.  Only by text well.

My configuration = Navit 0.5.5+ & Raspberry PI 3B+
navit.xml (as .txt file) and screenshots are attached. 
[navit.txt](https://github.com/navit-gps/navit/files/7656138/navit.txt)

Please, anybody help.  Thank you, Jean-Michel.

![RouteDescription](https://user-images.githubusercontent.com/60398536/144751353-de62b08d-a034-43a5-844d-b1a341cdf52b.jpg)
![maps](https://user-images.githubusercontent.com/60398536/144751360-06e47de4-33f8-4a9b-88a4-3003fff8b50b.jpg)
![settings](https://user-images.githubusercontent.com/60398536/144751370-e3abc18c-dfe9-491e-bbbf-00350603e746.jpg)
![actions](https://user-images.githubusercontent.com/60398536/144751382-4682f658-17ba-4e51-92a9-4b4552e3fd26.jpg)
![prompt](https://user-images.githubusercontent.com/60398536/144751385-84495df1-ac6a-4fbe-9298-998d0c78402a.jpg)
![gpsmon](https://user-images.githubusercontent.com/60398536/144751389-56f39c53-490e-4163-bbd3-c0cff24e6c91.jpg)
![cgps-s](https://user-images.githubusercontent.com/60398536/144751391-38491d3e-1338-4874-8849-cd04d1c95e38.jpg)

**Comment by jkoan** [comment]
Could you please verify within the logs that the layout files are loaded properly?

**Comment by jemilambi** [comment]
Thank you so much.  I investigate this right now.

**Comment by jemilambi** [comment]
That was it 👍 now it works.  I noticed this message.  But some internet page made me neglect this warning,

**Comment by jemilambi** [comment]
This one https://githubmemory.com/repo/navit-gps/navit/issues/1152

**Comment by jemilambi** [comment]
If I can do something for you just let me know.

**Comment by jkoan** [comment]
Just keep being involved into the community ;-)

**Comment by jemilambi** [comment]
:-)
