### ISSUE TITLE
Cross-comping for armboard is failng with navit-0.5.3

### ISSUE THREAD

**Issue by anantha-vidhya** [navit-gps/navit#1175]
I actually facing 2 issues right now
1. I couldn't able to **add maps** to the compiled navit app on Desktop
2. I am failing in **cross-compiling** the navit application to arm **amm437x** custom sbc board
3. Is navit can be build for arm am437x based custom board or not 
4. if possible some one please tell me the steps
Sorry if i am writing al this in wrong place i didn't get where i can get solution or at least guidance about this i tried in all possible ways so i posted this as one issue.
Please help me out in this regards.

Thanks in advance
A.N.V.Lavanya

**Comment by bkoppelmann** [comment]
Hi A.N.V.Lavanya,

your problems are a bit vague.

1. How did you try to add maps? I usually go to http://maps9.navit-project.org/ to download a map in bin format. Then go to your navit xml config to disable the sample map. Look for;
```
<!-- If you dont want to use the sample map, either set enabled="no" in the next line or remove the xml file from the maps directory -->
<mapset enabled="yes">
	<xi:include href="$NAVIT_SHAREDIR/maps/*.xml"/>
</mapset>
```
and set enabled to "no".
To enable the map which was just downloaded, look for;
```
<!-- Mapset template for openstreetmaps -->
<mapset enabled="no">
```
set enabled to "yes" and add your map like this
```
<map type="binfile" enabled="yes" data="/path/to/your/map.bin"/>
</mapset>
```
2. How did you try to build for the arm amm437x? What errors did you get?
3. I don't know if it is possible now. However, with enough willpower and work invested, sure :)
4. I don't think this is wrong place to ask these questions. However, don't expect to get an easy solution. People are willing to help, but will not do the work for you. 

Cheers,
Bastian

**Comment by anantha-vidhya** [comment]
Thank you  so much for your reply,
well I am not expecting some one easily do work for me.
I am expecting some sort of  help in achieving my goal to compile for arm board.

1. How i am adding maps: To add maps i followed the same procedure as you mentioned.But still it not worked for me. 
     Also i used command like **cmake ../navit-0.5.3 -DSAMPLE_MAP=n** since if i am not using this way command i am ending     
     with make errors.
          
2. How i am trying to build for am437x?
 I tried 2 different ways which none of them yielded me result First one is below
    **I am using tisdk procedure to build navit recipe as follows**
                       - sudo dpkg-reconfigure dash tap no
                       - wget https://releases.linaro.org/components/toolchain/binaries/6.2-2016.11/arm-linux-gnueabihf/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf.tar.xz
                       - tar -Jxvf gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf.tar.xz -C $HOME
                       - git clone git://arago-project.org/git/projects/oe-layersetup.git tisdk
                       - cd tisdk
                       - ./oe-layertool-setup.sh -f configs/processor-sdk/processor-sdk-04.02.00.09-config.txt
                       -  cd build
                       - . conf/setenv
                       - export PATH=$HOME/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/bin:$PATH
                       - MACHINE=am437x-evm bitbake navit
                       Which is showing me errors as
**ERROR: scons build execution failed.
arm-linux-gnueabihf-gcc: error:  -isystem/home/futura/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include : No such file or directory
rm -f packet_names.h && sed -e '/^ *\([A-Z][A-Z0-9_]*\),/s// "\1",/' < packet_states.h > packet_names.h && chmod a-w packet_names.h
timebase_h(["timebase.h"], ["leapseconds.cache"])
scons: *** [bits.os] Error 1
scons: *** [crc24q.os] Error 1
scons: *** [matrix.os] Error 1
scons: building terminated because of errors.
ERROR: Function failed: do_compile (log file is located at /home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/gpsd/3.14-r0/temp/log.do_compile.3106)** 
3. Second method i followed is 
     - downloaded navit from website directly of version navit-0.5.3
     - i used tisdk process development of sdk 04.02
     - i sourced the environment variables from sdk04.02->linux-devkit as source /$HOME/ti-processor-sdk-linux-am437x-evm-04.02.00.09/linux-devkit/environment-variables
     - mkdir navit-build-arm
     - cd navit-build-arm
     - cmake ~/navit-0.5.3
     - at above step i am using cross-compiler as arm-linux-gnueabihf-
     - i also copied all dependency libraries like SDL which is showing as not log of cmake.
     - but still i proceded where i got errors in make step.
     
4. Could you please comment on above methods i am following is it correct or i need to add something else?

**Comment by bkoppelmann** [comment]
> ERROR: Function failed: do_compile (log file is located at /home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/gpsd/3.14-r0/temp/log.do_compile.3106)

I don't know about bitbake or this specific toolchain. However, it looks to me that the error is not in navit but rather the gpsd package that is a dependency of navit.

> but still i proceded where i got errors in make step.

Can you provide the error log? Is it the same as with bitbake? Also, when you paste error logs, can you use code blocks like this? This makes it easier to read.
```
<Long error message here>
```

Is there a reason why you use version 5.3.0?

Cheers,
Bastian

**Comment by anantha-vidhya** [comment]
> I don't know about bit bake or this specific tool chain. However, it looks to me that the error is not in navit but rather the gpsd package that is a dependency of navit.
Yes in terminal i got log message as build failed due to gpsd. I am pasting the  log messages here which created during build of navit under gpsd folder in with name log.do_compile3106

	DEBUG: Executing shell function do_compile
scons: Reading SConscript files ...
Checking if compiler accepts -Wextra ...no
Checking if compiler accepts -Wall ...no
Checking if compiler accepts -Wno-uninitialized ...no
Checking if compiler accepts -Wno-missing-field-initializers ...no
Checking if compiler accepts -Wcast-align ...no
Checking if compiler accepts -Wmissing-declarations ...no
Checking if compiler accepts -Wmissing-prototypes ...no
Checking if compiler accepts -Wstrict-prototypes ...no
Checking if compiler accepts -Wpointer-arith ...no
Checking if compiler accepts -Wreturn-type ...no
Checking if compiler accepts -pthread ...no
Checking whether the C++ compiler works... no
C++ doesn't work, suppressing libgpsmm build.
Checking for ncurses... yes
Checking for libusb-1.0... yes
Checking for C library librt... no
Checking for dbus-1... yes
Checking for bluez... yes
Checking for C type in_port_t... no
Did not find in_port_t typedef, assuming unsigned short int
Checking whether SUN_LEN is declared... no
Checking whether SUN_LEN is declared... no
SUN_LEN is not system-defined, using local definition
Checking for C header file linux/can.h... no
You do not have kernel CANbus available.
Checking if compiler is C11 ...no
Checking for C header file libkern/OSAtomic.h... no
No memory barriers - SHM export and time hinting may not be reliable.
Checking if compiler supplies __ORDER_BIG_ENDIAN__ ...no
Checking for C header file endian.h... no
Checking for C header file sys/endian.h... no
Checking for C header file machine/endian.h... no
You do not have the endian.h header file. RTCM V2 support disabled.
Checking for C function daemon()... no
Checking for C function strlcpy()... no
Checking for C function strlcat()... no
Checking for C function clock_gettime()... no
Checking for C library libbluetooth... no
libbluetooth not found, bluez cannot be enabled.
Checking for C library libdbus-1... no
libdbus-1 not found, dbus_export cannot be enabled.
Checking for C header file sys/timepps.h... no
Checking if sys/ioctl.h supplies TIOCMIWAIT ...no
Forcing pps=no (neither TIOCMIWAIT nor RFC2783 API is available)
Neither xsltproc nor xmlto found, documentation cannot be built.
Checking for QtNetwork... no
Altered configuration variables:
nmea2000 = False (default True): NMEA2000/CAN support
rtcm104v2 = False (default True): rtcm104v2 support
pps = False (default True): PPS time syncing support
libgpsmm = False (default True): build C++ bindings
qt = False (default True): build QT bindings
debug = True (default False): include debug information in build
chrpath = True (default False): use chrpath to edit library load paths
prefix = /usr (default /usr/local): installation directory prefix
sysroot = /home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm (default ): cross-development system root
libdir = /usr/lib (default lib): system libraries
Prefixing includepy '/python2.7' with sysroot prefix
'/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm/usr/include/python2.7'
RTCM2 regression tests suppressed because rtcm104v2 is off.
Part of the website build requires asciidoc, not installed.
scons: done reading SConscript files.
scons: Building targets ...
substituter(["jsongen.py"], ["jsongen.py.in"])
Creating 'gpsd_config.h'
chmod -w jsongen.py
chmod +x jsongen.py
arm-linux-gnueabihf-gcc -march=armv7-a -marm -mfpu=neon -mfloat-abi=hard --sysroot=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm -o bits.os -c -isystem/home/futura/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/gpsd/3.14-r0=/usr/src/debug/gpsd/3.14-r0 -fdebug-prefix-map=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux= -fdebug-prefix-map=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm= --sysroot=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm -Wextra -Wall -Wno-uninitialized -Wno-missing-field-initializers -Wcast-align -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wpointer-arith -Wreturn-type -pthread -Wmissing-declarations -g -O0 -fPIC " -isystem/home/futura/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include " -I/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm/usr/include/dbus-1.0 -I/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm/usr/lib/dbus-1.0/include bits.c
arm-linux-gnueabihf-gcc: error:  -isystem/home/futura/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include : No such file or directory
substituter(["maskaudit.py"], ["maskaudit.py.in"])
chmod -w maskaudit.py
chmod +x maskaudit.py
arm-linux-gnueabihf-gcc -march=armv7-a -marm -mfpu=neon -mfloat-abi=hard --sysroot=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm -o crc24q.os -c -isystem/home/futura/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/gpsd/3.14-r0=/usr/src/debug/gpsd/3.14-r0 -fdebug-prefix-map=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux= -fdebug-prefix-map=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm= --sysroot=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm -Wextra -Wall -Wno-uninitialized -Wno-missing-field-initializers -Wcast-align -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wpointer-arith -Wreturn-type -pthread -Wmissing-declarations -g -O0 -fPIC " -isystem/home/futura/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include " -I/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm/usr/include/dbus-1.0 -I/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm/usr/lib/dbus-1.0/include -I/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm/usr/include/libusb-1.0 crc24q.c
arm-linux-gnueabihf-gcc: error:  -isystem/home/futura/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include : No such file or directory
Creating 'revision.h'
arm-linux-gnueabihf-gcc -march=armv7-a -marm -mfpu=neon -mfloat-abi=hard --sysroot=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm -o matrix.os -c -isystem/home/futura/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/gpsd/3.14-r0=/usr/src/debug/gpsd/3.14-r0 -fdebug-prefix-map=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/x86_64-linux= -fdebug-prefix-map=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm= --sysroot=/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm -Wextra -Wall -Wno-uninitialized -Wno-missing-field-initializers -Wcast-align -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wpointer-arith -Wreturn-type -pthread -Wmissing-declarations -g -O0 -fPIC " -isystem/home/futura/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include " -I/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm/usr/include/dbus-1.0 -I/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm/usr/lib/dbus-1.0/include -I/home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/sysroots/am437x-evm/usr/include/libusb-1.0 matrix.c
```
ERROR: scons build execution failed.
```
arm-linux-gnueabihf-gcc: error:  -isystem/home/futura/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include : No such file or directory
rm -f packet_names.h && sed -e '/^ *\([A-Z][A-Z0-9_]*\),/s// "\1",/' < packet_states.h > packet_names.h && chmod a-w packet_names.h
timebase_h(["timebase.h"], ["leapseconds.cache"])
```
scons: *** [bits.os] Error 1
scons: *** [crc24q.os] Error 1
scons: *** [matrix.os] Error 1
scons: building terminated because of errors.
ERROR: Function failed: do_compile (log file is located at /home/futura/Downloads/navit-build-arm/tisdk/build/arago-tmp-external-linaro-toolchain/work/armv7ahf-neon-linux-gnueabi/gpsd/3.14-r0/temp/log.do_compile.3106)
```
> Is there a reason why you use version 5.3.0?
No there is no specific version i am using . randomly i downloaded the navit source from website there i downloaded latest one.
But while building using bit bake method the version is fixed in tisdk build nothing we can add there.
navit:
  meta-oe              svn (skipped)
like the above it mentioned in the recipes list in bit bake  utility.

I hope this is what you are expecting else please let me know is something else you are looking for?

Thanks & Regards
A.N.V.Lavanya

**Comment by anantha-vidhya** [comment]
Can some one respond to me please?

**Comment by hoehnp** [comment]
As @bkoppelmann already pointed out, that the problem could be in gpsd, I was checking out to which project the files in the log belong to. This is actually the gpsd project and not to the navit project. Please ask there for help. Closing the issue as off topic.
