### ISSUE TITLE
Assembly error message while cross-compiling for arm board

### ISSUE THREAD

**Issue by anantha-vidhya** [navit-gps/navit#1177]
Navit application make fails leaving me this messages :
**/tmp/ccYRLvPu.s: Assembler messages:
/tmp/ccYRLvPu.s:702: Error: bad instruction `lock'
/tmp/ccYRLvPu.s:703: Error: bad instruction `incl [r3]'
/tmp/ccYRLvPu.s:704: Error: bad instruction `setne r2'
/tmp/ccYRLvPu.s:738: Error: bad instruction `lock'
/tmp/ccYRLvPu.s:739: Error: bad instruction `decl [r3]'
/tmp/ccYRLvPu.s:740: Error: bad instruction `setne r2'
/tmp/ccYRLvPu.s:807: Error: bad instruction `lock'
/tmp/ccYRLvPu.s:808: Error: bad instruction `decl [r3]'
/tmp/ccYRLvPu.s:809: Error: bad instruction `setne r2'
/tmp/ccYRLvPu.s:1018: Error: bad instruction `lock'
/tmp/ccYRLvPu.s:1019: Error: bad instruction `decl [r3]'
/tmp/ccYRLvPu.s:1020: Error: bad instruction `setne r2'
/tmp/ccYRLvPu.s:1185: Error: bad instruction `lock'
/tmp/ccYRLvPu.s:1186: Error: bad instruction `decl [r3]'
/tmp/ccYRLvPu.s:1187: Error: bad instruction `setne r2'
/tmp/ccYRLvPu.s:1295: Error: bad instruction `lock'
/tmp/ccYRLvPu.s:1296: Error: bad instruction `decl [r3]'
/tmp/ccYRLvPu.s:1297: Error: bad instruction `setne r2'
/tmp/ccYRLvPu.s:1597: Error: bad instruction `lock'
/tmp/ccYRLvPu.s:1598: Error: bad instruction `decl [r3]'
/tmp/ccYRLvPu.s:1599: Error: bad instruction `setne r2'
/tmp/ccYRLvPu.s:1643: Error: bad instruction `lock'
/tmp/ccYRLvPu.s:1644: Error: bad instruction `decl [r3]'
/tmp/ccYRLvPu.s:1645: Error: bad instruction `setne r2'
navit/graphics/qt_qpainter/CMakeFiles/graphics_qt_qpainter.dir/build.make:67: recipe for target 'navit/graphics/qt_qpainter/CMakeFiles/graphics_qt_qpainter.dir/RenderArea.cpp.o' failed
make[2]: *** [navit/graphics/qt_qpainter/CMakeFiles/graphics_qt_qpainter.dir/RenderArea.cpp.o] Error 1
CMakeFiles/Makefile2:533: recipe for target 'navit/graphics/qt_qpainter/CMakeFiles/graphics_qt_qpainter.dir/all' failed
make[1]: *** [navit/graphics/qt_qpainter/CMakeFiles/graphics_qt_qpainter.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2**

Did any one had idea of this?

**Comment by jkoan** [comment]
Your Compiler seems to do crazy things. But this doesn't seems to be directly related to navit
