### ISSUE TITLE
Intermittent/squared object display at low zoom levels

### ISSUE THREAD

**Issue by mav-** [navit-gps/navit#1180]
Created a Navit config to see if it can replace OsmAnd for my navigation needs. So far I'm very impressed, I love how customizable everything in Navit is. Running into one issue though, spend quite some time trying to find out whats wrong, but failed :)

At low zoom levels, I can't get my maps to display right. For example, I've set state and borderlines to display at all zoom levels, but parts of the objects disappear entirely, or sometimes strange squared blocks are displayed that disappear when zoomed in.

I've added some screenshots below to explain the issue better.
Higher zoom levels look fine, notice the country-border line is displayed as it should:

![navit-2](https://user-images.githubusercontent.com/980406/158903451-9bec2353-3983-4b1d-96e2-e38fc9b3719e.png)

Zoomed out one level, notice how parts of the country-border line now disappear:

![navit-3](https://user-images.githubusercontent.com/980406/158903550-98e631d2-0cff-4415-a60c-6f694fd7447f.png)

Zoomed out further, notice how even more parts of the country-border disappeared:

![navit-4](https://user-images.githubusercontent.com/980406/158903656-90e40c73-cf75-46a4-84fe-fb135c430e73.png)

Zoomed out again, this is the view I'm having the most problems with. Notice how objects are now displayed in a "squared" like structure and how the green blocks appear at the coastlines:

![navit-5](https://user-images.githubusercontent.com/980406/158903785-c2d764dd-bba2-4e1a-8e02-e8a7708c84d3.png)

It feels like there is a limit as to how much objects can be displayed, so it skips them... but I'm not sure.
This is on navit 0.5.5+dfsg.1-2+b1 (Debian Bullseye package and en_US.UTF-8 locale). I've not tried any other navit versions or operating systems. Internal GUI and gtk_drawing_area graphics type (others didnt work).

I've tried several maps. The screenshots above are from the navit planet extractor, but I've tried a geofabrik version (converted with maptool) as well. The problem persists. I did notice much less problems with the free Garmin world base map though.
Does anyone else encounter this?

**Comment by jkoan** [comment]
I think the answer to this is the same as to my own question in #873 for the tiles in the land. So Probably theirs not much we can do about it without plummeting the performance. 
For the Water its the problem described here #918

**Comment by mav-** [comment]
Thanks for the reply! Indeed, looks like the same issue. I'll work around it for now, hope it will be fixed some day :-).

**Comment by mav-** [comment]
I rebuilt a europe.bin with maptool -E (--experimental) which provides a few more zoom levels with proper coastlines. I didnt notice a performance hit, but that might not be the case on lower spec devices. It doesnt fix the 'rasterized' objects, but borderlines also seem to show a little better:

![navit-6](https://user-images.githubusercontent.com/980406/159155455-8b2941bc-eeed-4fc3-8d94-13461fb8b113.png)

**Comment by jkoan** [comment]
Closing here as we track this in #873
