### ISSUE TITLE
Auto layout switch not taking local time into account

### ISSUE THREAD

**Issue by OLFDB** [navit-gps/navit#1185]
In navit.c navit_layout_switch the GNSS time (UTC) is taken to calculate the sunrise/set values.

```
3540 if (vehicle_get_attr(n->vehicle->vehicle, attr_position_time_iso8601,&iso8601_attr,NULL)==1) {
            currTs=iso8601_to_secs(iso8601_attr.u.str);

```
Later currTs is used to determine if time is after sunrise, or after sunset and to switch to day/night layout.

```
3607 if (HOURS(trise)*60+MINUTES(trise)<(currTs%86400)/60) {
            after_sunrise = TRUE;
        }

        if (((HOURS(tset)*60+MINUTES(tset)<(**currTs**%86400)/60)) ||
                ((HOURS(trise_actual)*60+MINUTES(trise_actual)>(**currTs**%86400)/60))) {
            after_sunset = TRUE;
        }
        if (after_sunrise && !after_sunset && l->dayname) {
            navit_set_layout_by_name(n,l->dayname);
            dbg(lvl_debug,"layout set to day");
        } else if (after_sunset && l->nightname) {
            navit_set_layout_by_name(n,l->nightname);
            dbg(lvl_debug,"layout set to night");
        }

```
This is only working correctly when the system time is set to UTC (and DST is off) and we are in the UTC time zone.

It could be solved by using Zonedetect for getting the current timezone based on the GNSS coordinates.
(Zonedetect would also be able to provide the country based on coordinates to change default country for searching destinations to have to current country by default).

At least system timezone and DST should be taken into account for currTs:

```
// add timezone offset to GNSS UTC time to calculate sunrise/set correctly
            time_t z = time(NULL);
            struct tm * pdt = gmtime(&z);
            mktime(pdt);

            // use pdt->tm_isdst to have standard local time when system uses DST
            currTs=iso8601_to_secs(iso8601_attr.u.str) + (pdt->tm_gmtoff-(pdt->tm_isdst==1?3600:0));
```

**Comment by OLFDB** [comment]
The issue was caused by the vehicle/iphone. It sends localtime instead of UTC in the location event.
So what I wrote above is crap. Nevertheless there is an issue when negative rise times are returned by the sunriset function.

This can be addressed by  

       ```
 int hr = HOURS(trise);
        int mr = MINUTES(trise);
        int hs = HOURS(tset);
        int ms = MINUTES(tset);
        int minofrise;
        int minofset = HOURS(tset) * 60 + MINUTES(tset);

        int curtsinmin = (currTs%86400)/60;

        if (hr < 0) {
            minofrise = 1440 + (HOURS(trise) * 60 - MINUTES(trise));


            if(curtsinmin >= minofrise && curtsinmin <= 1440) {
                after_sunrise = TRUE;
                dbg(lvl_error, "After sunrise");
            }

            if (curtsinmin >= 0 && curtsinmin <= minofset) {
                after_sunrise = TRUE;
                dbg(lvl_error, "After sunrise");
            }

            if (curtsinmin > minofset && curtsinmin < minofrise) {
                after_sunset = TRUE;
                dbg(lvl_error, "After sunset");
            }

        } else {

            minofrise = HOURS(trise) * 60 + MINUTES(trise);

            if (minofset < curtsinmin) {
                after_sunrise = TRUE;
                dbg(lvl_error, "After sunrise");
            }

            if (((minofset < curtsinmin)
                        || ((minofrise > curtsinmin)))) {
                after_sunset = TRUE;
                dbg(lvl_error, "After sunset");
            }
        }
```

**Comment by jkoan** [comment]
Why is it possible to have negative rise times in the first place?

**Comment by OLFDB** [comment]
Please leave the issue open. There is definitely a problem with negative times returned and the above fix fixes this partially. I think this happens, when the sunrise is before 00:00 and current time is after 12:00 and before sunrise time. Same for sunset. I had made a test function passing all possible coordinates and checked the results. Also mglasow mentioned issues with sunrise and set on the southern hemisphere in an issue.

**Comment by OLFDB** [comment]
[sunriset 2.kml.zip](https://github.com/navit-gps/navit/files/10339163/sunriset.2.kml.zip)
Simulation with fix.
