### ISSUE TITLE
Remove feature to read image-files from zip

### ISSUE THREAD

**Issue by jkoan** [navit-gps/navit#1194]
Currently navit could load Images from ZIP-files. But this feature is only able to work when navit has a appropriate zip and is using `gtk_drawing_area`.

In my opinion we should remove this feature to simplify the code and allow for better maintainability. 

What are you opinions on this @navit-gps/core and others?

The current code sections can be found here:
https://github.com/navit-gps/navit/blob/0338c1f696e01cd89c26ea7854cfc110c283f069/navit/graphics.c#L868-L888
https://github.com/navit-gps/navit/blob/0338c1f696e01cd89c26ea7854cfc110c283f069/navit/graphics.c#L1002-L1004
https://github.com/navit-gps/navit/blob/0338c1f696e01cd89c26ea7854cfc110c283f069/navit/graphics/gtk_drawing_area/graphics_gtk_drawing_area.c#L231-L243

**Comment by lains** [comment]
Yes, I guess reading images from zip files is actually not currently in use... I assume I can be dropped, especially if it's not even implemented for all targets.

**Comment by metalstrolch** [comment]
I agree as well. It's even questionable if zipping images even reduces size assuming the images are not plain bitmaps.
