### ISSUE TITLE
OSD: Disable/Enable Buttons

### ISSUE THREAD

**Issue by bkoppelmann** [navit-gps/navit#1197]
Hi,

I was trying to create a drop down menu. If you click on a button "menu" a new buttons appears. And if you click on the submenu button  an action happens and it disappear again. First I was trying to achieve it like this:

```
<osd name="menu" enabled="yes" type="button" x="0 y="0" w="48" h="48" src="menu.png" command="
    osd[@name=="submenu1"].enabled = "yes";
"/>
<osd name="submenu1" enabled="no" type="button" x="0" y="50" w="48" h="48" src="submenu1.png" command="
    gui.menu();
    osd[@name=="submenu1"].enabled = "no";
"/>
```
This doesn't work since "enabled" is not attribute, but rather a value that is only checked while parsing the config.

I then tried to create this using `osd_configuration`.  I have a cmdif that sets `osd_configuration` based on the routing status. How would I set another bit of osd_configuration for my drop down menu? I tried:

```
<osd name="menu" enabled="yes" type="button" x="0 y="0" w="48" h="48" src="menu.png" command="
    osd_configuration = osd_configuration | 4;
"/>
```
Which doesn't do anything to `osd_configuration`.

Any ideas?

Cheers,
Bastian

**Comment by OLFDB** [comment]
You are missing the closing quotation mark at `x="0`.

I tested with and it changes the osd_configuration value:
`<osd name="menu" osd_configuration="1" enabled="yes" type="button" x="0" y="0" w="48" h="48" src="menu.png" command="osd_configuration=osd_configuration|4"/>`

**Comment by OLFDB** [comment]
For a submenu use:
`<osd name="menu" osd_configuration="1" use_overlay="1" enabled="yes" type="button" x="0" y="200" w="48" h="48" icon_w="48" icon_h="48" src="menu.png" command='osd_configuration=osd_configuration|16;'/>
<osd name="submenu" enable_expression="osd_configuration&amp;16" use_overlay="1" type="button" x="0" y="260" w="48" h="48" icon_w="48" icon_h="48" src="menu.png" command=' osd_configuration=osd_configuration&amp;~16;'/>`

`use_overlay="1"` is important to have the gui updated.

**Comment by bkoppelmann** [comment]
Hi OLFDB,

> You are missing the closing quotation mark at `x="0`.

that was my mistake while cutting down my example to the minimum. Should have tested it in navit before posting.

> use_overlay="1" is important to have the gui updated.

I was missing exactly that. Thank you! It's working now for me.
Cheers,
Bastian
