### ISSUE TITLE
Yellow Screen in Raspberry Pi

### ISSUE THREAD

**Issue by NKumar1612** [navit-gps/navit#1210]
Hello Team Navit,

I'm using a Rasperry Pi 3b+ with, Raspbian 11 OS, with U-blox 7 GPS/GLONASS device for finding my location. I used [this](https://ozzmaker.com/navigating-navit-raspberry-pi/#:~:text=Navit%20can%20be%20installed%20without,skip%20to%20the%20next%20step.) with a few changes since i used Ublox 7 instead of BerryGPS-IMU.

So after i followed all of the steps and even checked my gps which works alright.

And in the navit.xml, i've added a map of my city using, [maps9 navit](http://maps9.navit-project.org/), (i'll show my whole code below)

So then when i ran the code, first i got a white screen for about 3 seconds:
![navit-1](https://user-images.githubusercontent.com/34906491/202124124-105a7e12-0599-4563-ba0c-6dea41928b86.png)

then it turned yellow:
![navit-2](https://user-images.githubusercontent.com/34906491/202124252-48fe105f-94af-41ab-b4a9-dad5267599e6.png)

i've tried shifting the location to other areas in the city and yet they are still pitch yellow.

and these are the errors that i recieve in the terminal:
![navit-4](https://user-images.githubusercontent.com/34906491/202125298-94d0fab9-0971-4761-a943-6e0d5aba3451.png)

and this is my navit.xml code:
![xmlcode1](https://user-images.githubusercontent.com/34906491/202130611-d2c2c8bf-4190-451f-ad09-d231fb7de419.png)
![xmlcode2](https://user-images.githubusercontent.com/34906491/202130669-f8d74b6d-b410-4ecb-b944-d73732eb7504.png)
![xmlcode3](https://user-images.githubusercontent.com/34906491/202130702-9b20f653-7bbb-4747-a881-d5954979fd60.png)
![xmlcode4](https://user-images.githubusercontent.com/34906491/202130739-a28b1f23-28f5-4a48-a8cf-ff38e11e475a.png)
![xmlcode5](https://user-images.githubusercontent.com/34906491/202130761-a574dc1e-4f98-417c-8626-1ab826f7823c.png)
![xmlcode6](https://user-images.githubusercontent.com/34906491/202130779-a659cfa3-1733-4c93-85e9-12fe0dfd9c2c.png)
![xmlcode7](https://user-images.githubusercontent.com/34906491/202130829-7ab22bf9-5665-4b97-abac-9b2d1029f6a8.png)
![xmlcode8](https://user-images.githubusercontent.com/34906491/202131031-cde95651-7a29-486b-b2c3-1a59933c4936.png)
![xmlcode9](https://user-images.githubusercontent.com/34906491/202131057-f2f12602-c9e5-4e19-81e2-6df5153fa844.png)
![xmlcode10](https://user-images.githubusercontent.com/34906491/202144969-665e1245-1873-4893-ae96-075fc3a7cb4b.png)
![xmlcode11](https://user-images.githubusercontent.com/34906491/202131228-9caf5cb8-5f51-4d34-b95a-0332361b41f3.png)
![xmlcode12](https://user-images.githubusercontent.com/34906491/202131247-ac75c8b0-4ff9-47c5-bb14-db7e3aeb4cbb.png)
![xmlcode13](https://user-images.githubusercontent.com/34906491/202131393-9ac4c7a6-89bc-4889-9a83-20b62f3a2a99.png)
![xmlcode14](https://user-images.githubusercontent.com/34906491/202144669-a13425d4-6c93-4a6e-85f8-12b420f21d1e.png)
![xmlcode15](https://user-images.githubusercontent.com/34906491/202145021-609b0885-2a9c-4a61-ad24-64f63e7593a8.png)

![xmlcode16](https://user-images.githubusercontent.com/34906491/202144739-a18444af-037f-4c19-b3cc-4d5e004a2501.png)
![xmlcode17](https://user-images.githubusercontent.com/34906491/202131655-32a486c8-a4c5-4368-85c5-b45897ff25a1.png)
![xmlcode18](https://user-images.githubusercontent.com/34906491/202131679-3aae16fa-704d-4402-9879-294c3f7d842b.png)

**Comment by hoehnp** [comment]
Hi @NKumar1612,

it would be more helpful to have the navit.xml as a text file instead of screenshots. Especially since the lines seem truncated to me.

**Comment by NKumar1612** [comment]
hello @hoehnp, would you please help me in sending the file since it's my first time opening an issue in github?

**Comment by hoehnp** [comment]
this should work by simply renaming navit.xml to navit.txt and drag it in, like you probably did with the images.

**Comment by hoehnp** [comment]
Hello @NKumar1612,
this is an downstream bug of debian:  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=967960

It should be resolved by downloading the navit_layout*.xml files from https://github.com/navit-gps/navit/tree/trunk/navit

**Comment by jkoan** [comment]
@hoehnp has already given the solution, so closing this
