### ISSUE TITLE
Control navit from other application

### ISSUE THREAD

**Issue by gaotianh** [navit-gps/navit#1226]
Hi, I want to control navit from other applications like resetting the destination in raspberry pi. 
I am wondering should I use python binding to achieve that? 
I could not open the navit wiki page for the binding, so is it possible that I could get more information?

Thanks

**Comment by jkoan** [comment]
You can use DBus which is probably most appropriate. 
As this is not yet in our upstream documentation look here: https://navit--1195.org.readthedocs.build/en/1195/user/configuration/integrations/dbus.html
