### ISSUE TITLE
Saber ler o navit.log

### ISSUE THREAD

**Issue by RupestreC** [navit-gps/navit#1237]
Bom dia, gostaria de saber ler o navit.log. Anexo o meu recente navit.log e gostaria de saber ler os dados que estão no seu conteúdo. Obrigado
[navit.log](https://github.com/navit-gps/navit/files/11637489/navit.log)

**Comment by jkoan** [comment]
It seems like you configured the vehicle source wrong. Could you provide your navit.xml?

**Comment by jkoan** [comment]
No future response, so we can't help
