### ISSUE TITLE
How to compile on Raspberry PiOS bookworm?

### ISSUE THREAD

**Issue by adevoss** [navit-gps/navit#1249]
What is the procedure to compile on PiOS bookworm?
The commands on https://navit.readthedocs.io/en/trunk/development/linux_development.html return an error and there is no new `navit` file.

What branch to compile? trunk, master or other?

**Comment by jkoan** [comment]
Please post the log output of your commands and the exact steps you followed.

**Comment by adevoss** [comment]
Installed packages on Raspberry Pi PiOS bookworm (as described in docs, also installed `build-essential`):
```
sudo apt-get install cmake zlib1g-dev libpng-dev libgtk2.0-dev librsvg2-bin \
                     g++ gpsd gpsd-clients libgps-dev libdbus-glib-1-dev freeglut3-dev libxft-dev \
                     libglib2.0-dev libfreeimage-dev gettext protobuf-c-compiler libprotobuf-c-dev libspeechd-dev
```

To compile (as described in docs):
- cloned repo `trunk` in directory-c
- created directory-b
- cd directory-b
- cmake directory-c

(Trying to solve #1241)
[navit-compile.txt](https://github.com/navit-gps/navit/files/13219049/navit-compile.txt)

**Comment by jkoan** [comment]
Everything seems fine. You only need to run make after cmake

**Comment by adevoss** [comment]
Thanks.
Now I can test my PR.

**Comment by adevoss** [comment]
Please re-open.

- created a local branch after cloning repo
- added ~10 lines of code in 1 file
- After compiling, the `navit` file is too big (2.6M vs 737K)
- copied the `navit` file to `/usr/bin` over the official file
- Navit does not start (see log file)
[202311012209.log](https://github.com/navit-gps/navit/files/13232120/202311012209.log)
- Restored the official navit file. All fine.

What are extra steps to compile Navit successfully?
I will create the PR so you can see the added lines of code.

**Comment by jkoan** [comment]
The size is probably explained by the fact that you compiled a dev build with debug symbols and what not (the default)
This also explains why you can't copy it over to the original binary. Also with that the libraries of the Dev build are not where they are supposed to be for a Dev build. 
The easiest solution is to test the Dev build local with ./navit inside the build directory and that the navit folder. After you verified that your code is working you can then build a package to be able to install with your package manager or directly install the Dev build into your system. The first option would use cpack and the second "make install". The first  option has the advantage that you can easily remove the package from the system using the package manager later on.

**Comment by adevoss** [comment]
Thanks.
I thought right the opposite way: Replacing the binary is a good real world test.
A package would be a bonus. First I'll test #1250 locally.

**Comment by adevoss** [comment]
Navit starts showing the map on the gps location.
So now I have to go testing on the road.

**Comment by jkoan** [comment]
> Navit starts showing the map on the gps location.
> So now I have to go testing on the road.

Just for you to know. It's also possible to use vehicle "demo" to set a start and end location and test with that in the comfort of your home ;)

**Comment by adevoss** [comment]
> also possible to use vehicle "demo"

Thanks.
Why didn't I read this earlier? :-) My PR #1259 is (almost) finished.
