### ISSUE TITLE
Adding an attribute to attr_def.h breaks lookup when entering destination

### ISSUE THREAD

**Issue by adevoss** [navit-gps/navit#1260]
To reproduce:

- Add an attribute to `attr_def.h`
- Recompile
- Enter a destination

**Comment by jkoan** [comment]
Could you please provide a patch how/where you tried to insert a attribute?

**Comment by adevoss** [comment]
Sure. Take #1259 and search for my `// TODO` comments.

**Comment by OLFDB** [comment]
You should add a new attribute in attr_def.h only at the end of a type. Never somewhere where it causes other attributes of that type to get a new value. As maptool is also using attributes, all maps not created with maptool made from your code might not work anylonger. 

You could try building your map using maptool build from your code, or move the new attribute after ATTR(outputdir) and try again (line 415 in your attr_def.h):

```
ATTR(outputdir)
ATTR(data_tts)
ATTR2(0x0003ffff,type_string_end)
```

**Comment by adevoss** [comment]
> You should add a new attribute in attr_def.h only at the end of a type.

Ah. My first thought was: I can't go wrong when I insert the new attribute `data_tts` directly under `data`.
I will move the new attribute to the end of the type.

To be clear: I didn't modify the map and/or maptool. Using the same map only changed a `.c` file and `attr_def.h`.
After I changed `attr_def.h` I will update #1259.
