### ISSUE TITLE
Navit.sh

### ISSUE THREAD

**Issue by Timfedora** [navit-gps/navit#1262]
When I try to download the 'navit.sh' file from this link: https://download.navit-project.org, it just shows 'message: not found.' I've tried using four different web browsers.

**Comment by jkoan** [comment]
https://download.navit-project.org/ is for dev builds only. As there isn't very much activity at the moment those artifacts are already deleted as they are past the retention period. 
But you can download the last release from here: https://github.com/navit-gps/navit/releases

**Comment by Timfedora** [comment]
Ok
