### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by Timfedora** [navit-gps/navit#1263]
So how do you build it from the .tar file on fedora?

**Comment by OLFDB** [comment]
Don't use a tar file, build from scratch:

With fedora 38:

See https://navit.readthedocs.io/en/v0.5.6/development/linux_development.html#fedora-dependencies.

You need to replace cegui-devel with cegui06-devel and remove saxon-scripts from the yum command.

`sudo yum install gettext-devel libtool glib2-devel cegui06-devel freeglut-devel quesoglc-devel SDL-devel libXmu-devel gpsd-devel gtk2-devel speech-dispatcher-devel cvs python-devel`

Add a copr repository to get saxon-scripts:

```
sudo dnf copr enable tliardon/saxon
```
Now install the build essentials, the C++ compiler and gspd:
```
sudo dnf groupinstall "Development Tools" "Development Libraries"

sudo yum install gcc-c++

sudo yum install gpsd
```
Get navits source code:

```
git clone https://github.com/navit-gps/navit.git
```
Build:
```
cd navit
mkdir build
cd build
cmake ../
make
sudo make install
```

Configure GPSD for your GPS device.

Start navit:
```
navit
```

This will start navit with the basic config "navit.xml" found in 

/usr/local/share/navit

directory.

You will see a yellow screen with a small green circle in the lower part of the window only.

Get a map including your area [here](https://github.com/navit-gps/gh-actions-mapserver/releases). 

Copy the file to /usr/local/share/navit/maps/ .

Edit navit.xml and change:

```
               <mapset enabled="yes">
                        <xi:include href="$NAVIT_SHAREDIR/maps/*.xml"/>
                </mapset>

                <!-- Mapset template for OpenStreetMap -->
                <mapset enabled="no">
                        <map type="binfile" enabled="yes" data="/media/mmc2/MapsNavit/osm_europe.bin"/>
                </mapset>
```

to

```
               <mapset enabled="no">
                        <xi:include href="$NAVIT_SHAREDIR/maps/*.xml"/>
                </mapset>

                <!-- Mapset template for OpenStreetMap -->
                <mapset enabled="yes">
                        <map type="binfile" enabled="yes" data="$NAVIT_SHAREDIR/maps/<your file name here>"/>
                </mapset>
```

Restart navit.

**Comment by Timfedora** [comment]
Thanks!
