### ISSUE TITLE
Offer Taiwan as a separate download in the Android download dialog

### ISSUE THREAD

**Issue by jidanni** [navit-gps/navit#347]
Why do I have to download 981 megabytes of three countries when all I want is Taiwan. I have not left Taiwan in a quarter century. Maps. Me allows one to even download just half of Taiwan. And other applications allow one to have a rectangle so they can just download a few square kilometers. I can't even get started using this application till I download 981 megabytes!

**Comment by metalstrolch** [comment]
You can use the Navit planet extractor to download any custom region you want. See http://maps.navit-project.org

**Comment by pgrandin** [comment]
@jidanni what platform are you using?

**Comment by jidanni** [comment]
Android.

**Comment by sleske** [comment]
I think what @jidanni wants so say is: "Why does the Android download helper only let me download "Japan+Korea+Taiwan" (about 800 MiB), when I only want Taiwan.
That is indeed a valid point. I edited the title.

We should consider offering Taiwan as a separate download. According to http://maps.navit-project.org/ , just Taiwan would only be about 150 MiB.

**Comment by sleske** [comment]
Incidentally, it would also make sense to offer Korea as a separate download. Japan + Korea makes sense, because we can only download rectangles, and a rectangle containing Japan also contains Korea, because of Japan's banana shape (no offense :-) ).

**Comment by pgrandin** [comment]
@sleske indeed!

@jidanni the technical reason is that currently the list of countries is hardcoded into Navit for the android map download, and that list could be more granular.

This is where Taiwan is defined : https://github.com/navit-gps/navit/blob/trunk/navit/android/src/org/navitproject/navit/NavitMapDownloader.java#L127

As a short term fix, I moved Taiwan to its own menu entry in https://github.com/navit-gps/navit/commit/bcd60ee37e970973c17c2e71d8953c800dbe7ebf we will still need to merge that in trunk.

We can push that to the Play Store today or tomorrow. In the mean time, if you want to test it you can download an apk with this change here : https://3271-30791823-gh.circle-artifacts.com/0/root/project/android-arm/navit/android/bin/navit-bcd60ee37e970973c17c2e71d8953c800dbe7ebf-arm-debug.apk

The long term fix will be to have a more detailed list of countries (and regions, for some countries) and keep that list outside of Navit's code. Our member @jkoan started working on this but this is not completely ready yet.

**Comment by pgrandin** [comment]
It works :)

![taiwan](https://user-images.githubusercontent.com/701794/32035308-22725cc6-b9cd-11e7-8128-8b37792092bd.png)

Tested using the apk listed above. We need to fix the filesize listed in the menu though.

**Comment by jkoan** [comment]
The change is already done and will definitely be part of the next release. I will close this issue now.

**Comment by pgrandin** [comment]
Actually this isn't pushed to the play store yet, as we have issues with the android build system.
We don't know if the OP knows (or wants) to install apk packages directly, so I wanted to wait until it's completely released.

**Comment by jidanni** [comment]
The OP likes using Google Play.
No hurry though.
