### ISSUE TITLE
Multipolygons

### ISSUE THREAD

**Issue by jandegr** [navit-gps/navit#398]
A place to document my progress and findings on a new approch to display openstreetmap multipolygons and to get some participants to test/tweak all the existing graphics drivers to handle the multipolygons.

On the maptools side this approach just assembles all the outers and inners of a multipolygon relation into a single way instead of the old approach/attempt in navit/trac to triangulate all.

**Comment by jandegr** [comment]
A sample relation : http://www.openstreetmap.org/relation/1825800

displayed with the old gtk (before the move to cairo) on windows but with the maptool tweak for multipolygons 

![gtk_old](https://user-images.githubusercontent.com/9937104/36030152-5a4ab792-0da6-11e8-908e-c5116a96cf54.JPG)

The display of the outer and inner is correct but it just shows a blue line where it moves from the outer to the inner.

same sample on android after a little tweak in android/graphics to make it "lift the pen" when moving from the outer to the inner

![android_pen_lifted](https://user-images.githubusercontent.com/9937104/36030305-ed2c3180-0da6-11e8-995e-99d4bcb2711e.JPG)

**Comment by jandegr** [comment]
For maptool I used psql, so step one
https://github.com/navit-gps/navit/pull/399
allows to build a map from a psql pgsimple database, 
without the multipolygon tweaks

**Comment by jandegr** [comment]
On request, the no-multipolygon version

![dry](https://user-images.githubusercontent.com/9937104/36046466-4b2ef04c-0dd9-11e8-9f1f-4d32bb715399.JPG)

**Comment by jandegr** [comment]
and now a more complete sample, also the rivers 'ringvaart' and 'leie' are now showing properly, those are also multipolygon relations as well.

![wet](https://user-images.githubusercontent.com/9937104/36046717-2468a074-0dda-11e8-8312-7f618fdd4649.JPG)

**Comment by jandegr** [comment]
A sample map with relations tagged with natural=water and waterway=riverbank processed.


[luxembourg.zip](https://github.com/navit-gps/navit/files/1713242/luxembourg.zip)

**Comment by sleske** [comment]
Nice! The missing support for multipolygon relations was a real annoyance with Navit - loads of buildings, lakes etc. missing.

**Comment by jandegr** [comment]
An attempt to modify win32 graphics

https://github.com/navit-gps/navit/commit/0652cead7cb553c8e2b417d77dd41bc2a026851b

displaying a multipolygon before adapting win32 graphics
![echternach_old](https://user-images.githubusercontent.com/9937104/36073372-ce2fe7a6-0f2f-11e8-879a-1566d8d4d9fb.JPG)

after the win32 graphics code change
![echternach_new](https://user-images.githubusercontent.com/9937104/36073383-05533a08-0f30-11e8-8d92-47894fc485e5.JPG)

on OSM
https://www.openstreetmap.org/relation/1771486

This location is part of the Luxembourg testmap I posted above, so anybody can test the same relation.

**Comment by jkoan** [comment]
Really nice work :)

**Comment by metalstrolch** [comment]
How to test your generated map? Are there any changes required to trunk right now to test except the "lift pen" patch described here for win32?

Because it seems your trick in detecting closed loops in polygon drawing code seems to fail during zoom and pan as Navit somehow reduces the number of points in a polygon sometimes hitting the start point. No loops are detectable anymore, as the reducing code assumes everything is just one closed loop.

**Comment by jandegr** [comment]
@metalstrolch 
Thanks for testing, that is indeed a known issue. Clipping will need to be reviewed if this approach to multipolygons would be found worth to be further worked on.
Jus for testing graphics, this helps a lot https://github.com/navit-gps/navit/commit/5d3166ff9da9d94d732d8a883f5d68cd9956d279
I doubt the usefullness of the existing clipping anyway since most graphics will clip anything beyond the screen themselves.

Some other known issues 
- rivers and such kan produce very big items, have found river relations of over 50km long.
There is code in maptool to spilt such items but that is not used yet for multipolygons.
- multipolygons with their members not in sequence in OSM are not sorted yet, however members in sequence but to be walked in reverse are already dealt with.

**Comment by metalstrolch** [comment]
Indeed, 5d3166f makes the results way better. And I assume there's just something wrong with the relations doing river "Sauer" in the North.

Interesting approach.
I would strongly rethink how to deal with detecting closed loops, as there seem to be a lot of polygons having the same node multiple times, that are not multi polygons.
I suggest a better approach like injecting a separator node with a special misformed coordinate. This could then be preserved by draw_polygon_clipped while keeping the interfaces intact and preserving map file compatibility.
And a simple rule like it's always the outer polygon first, with the inners following to be subtracted from the outer. This would form a simple interface for polygons with holes, as that's what this is about mostly.

For curiosity. The [qt5_multipolygon](/navit-gps/navit/tree/qt5_multipolygon) contains the "fix" for qt5 graphics.
Keep going @jandegr

**Comment by jkoan** [comment]
@jandegr any progress? What about merge what we have so far?

**Comment by metalstrolch** [comment]
Closing this as #824 got merged to trunk.
