### ISSUE TITLE
[Proposal] Move out of trac.navit-project.org

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#424]
Hi,

I personally find that trac is quite old looking and not really user-friendly for external contributors.
Plus, it would be nice to manage all our issues in the same place as our pull requests.

So my proposal is that I move all the currently opened trac tickets to github issues with their entire history and assign them to the user which has it currently in trac.
Once that's done I think we can update the website and redirect track.navit-project.org to github/navit-gps/issues with a 301.

Would you be ok with that proposal?

Thanks for your feedback,
Joseph

**Comment by jkoan** [comment]
It's perfect! In my opinion just do it :)
Also I really much like all preferences you selected. Even I really like that nobody is assigned after the move (because most of the old assignments are outdated)

**Comment by sleske** [comment]
> The attachements are not saved
> Seems some code blocks are missing

Sorry, but these seem like deal-breakers to me. Can't we import the issues without dropping half the information?

**Comment by aerostitch** [comment]
> Sorry, but these seem like deal-breakers to me. Can't we import the issues without dropping half the information?
Yes, sorry, I noticed those 2 after posting the message but I needed some sleep so I edited it, keeping those as notes to work on it today.
I was also wondering if it was worth keeping the closed tickets or if we should just not import them. I'd be all for the 2nd solution, but let me know if you want to keep them.

**Comment by aerostitch** [comment]
So I've been able to fix:
* the issue with the labels: https://github.com/mavam/trac-hub/pull/21
* make sure to avoid importing closed tickets: https://github.com/mavam/trac-hub/pull/20
* make sure we don't loose the html & xml codes from the comments and the description: https://github.com/mavam/trac-hub/pull/19

See: https://github.com/aerostitch/testnavit/issues

I'm still working on trying to figure out how to get the attachments in.

**Comment by aerostitch** [comment]
All attachments have been imported to https://github.com/aerostitch/navit-attachments (I'll keep it there for archival)
Integrated properly with the issues.
See https://github.com/aerostitch/testnavit/issues
Let me know if that needs more change.

**Comment by aerostitch** [comment]
Closing. See #425 for explanations.
