### ISSUE TITLE
[Proposal] assign PR to people automatically at the end of the CI build

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#431]
There are people more proficient than others on certain parts of the tool, so they are generally the best person to review the PR related to that part of the tool.
What we could do is, once a CI job is finished successfully, run a script as a last step that would assign the ticket to 2 or 3 people that correspond to the parts of the tool being touched by the revision. A mapping could be constructed with people more cross to back some areas where nobody's assigned yet.
Of course assignments to a ticket can be changed afterwards manually.
This idea would be to encourage people that are not proficient on an area to let others take care of the review.
Not sure if it's a good or a bad idea, it's just something I see a lot lately (generally with github bots but we probably don't need to go that far) and was wondering if it could be helpful here too.

**Comment by pgrandin** [comment]
I like this idea. A good example is that @mdankov is probably our maptool expert currently.

**Comment by aerostitch** [comment]
Moved this to a note in the [Fancy ideas for later](https://github.com/navit-gps/navit/projects/6) project.
