### ISSUE TITLE
Upload Display

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#463]
Für das SGS2 Smartphone habe ich ein Display gestaltet 2D/3D. Grundsätzlich funktioniert die Navigation. Ist eine Anregung zur Gestaltung der 3D Ansicht \(OSM\). Insbesonders wäre die XML zu prüfen. Wo können die Grafiken und die XML-Datei hochgeladen werden. Finde mich in der WIKI Kontaktseite nicht zurecht.

For the SGS2 Smartphone I designed a display 2D/3D. Basically the navigation works. Is an inspiration for the design of the 3D view \(OSM\). In particular would be to examine the XML-File. Where can the graphics and the XML file will be uploaded. It will not find handle in the WIKI me contact page. 
Gruß aus Austria

Reported by: *anonymous

Original Ticket: [navit/support-requests/3](https://sourceforge.net/p/navit/support-requests/3)

**Comment by jkoan** [comment]
Original not reachable
