### ISSUE TITLE
Searching city and street by sql server

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#480]
Hi,

I have posted on the openmoko mailing list a message that is about
searching the street and city by a SQL server, propably sqlite.

I have tested generating these data from OSM with a small area and
it seems to work.

But big data is a problem when converted at once.

In general, is there an interest ?

Lothar

Reported by: lollisoft

Original Ticket: "navit/feature-requests/15":https://sourceforge.net/p/navit/feature-requests/15

**Comment by jandegr** [comment]
I don't understand how this would relate to Navit, at runtime we don't have a relational database
