### ISSUE TITLE
Map of Slovakia in download list

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#482]
Hi. I miss map of Slovakia in Navit's download list. Can you add it?
I use latest trunk version from 20.2.2011

Thanks for help.

Reported by: prescott66

Original Ticket: [navit/feature-requests/17](https://sourceforge.net/p/navit/feature-requests/17)

**Comment by jandegr** [comment]
I confirm it is not predefined on the mapserver and not in the android mapdowload either

**Comment by jandegr** [comment]
Added Slovakia to the list in Android
https://github.com/navit-gps/navit/commit/85adcb7e5853096f7f1105eae8b35d2c331b7391

**Comment by aerostitch** [comment]
Thanks for taking care if this @jandegr. I guess we can close this then right? Feel free to reopen if it's not the case.
