### ISSUE TITLE
Update website to give user a more elegant jump into navit

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#483]
First of all good work to all the developers. 
I was pointed to this project from GPS Viking. 
I use Viking all the time, and wanted a Windows Mobile Version. Someone pointed me here. 
My first impressions of your little bit. 
Your trying to over simplify things. 
This needs a few things to make it so average user can install it and configure it. 
There needs to be a configuration option that edits the navit.xml file. 
205k of configuration file, most are not going to push through that except a dedicated 
geek. 
Your homepage need to advertise that Nav-it can use OSM MAPS, Garmin img files, etc. 
It took me 10 minutes of reading and different pages before I actually found maps. 
So I downloaded the OSM for my State \(Arkansas USA\) and when I try to search for my 
own address, it goes from US flag icon input town, but no state, then when I get to Street, 
the enter/checkmark icon is missing so you can't even input the street name 

I know its only 0.2.x version so thesee are just issues that need to be worked out. 

I use a GPS with a motorcycle and there is thousands more like me, we like to make 
tracks from our gps and share our trips on-line, The ability to export gpx files is high 
on the list of things, there is others that travel around the world and the using OSM maps 
is a great thing for them. 

Just my first thoughts. 
I don't think its ready for me to try on my gps since I can't even get to my osm map 
on my pc. 

Reported by: caish

Original Ticket: [navit/feature-requests/18](https://sourceforge.net/p/navit/feature-requests/18)

**Comment by jkoan** [comment]
Most of the informations are outdated but we really need to update the website

**Comment by jkoan** [comment]
Website got updated. Tracing new issues in new issues
