### ISSUE TITLE
Allow search for cities by zip code (postal code)

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#484]
Sometimes, when you search for Cities and there exist multiple with the exact same name, there is no way to tell them apart.
It would be great if a search by zip code could be implemented.
Otherwise: Great work\!

Reported by: *anonymous

Original Ticket: [navit/feature-requests/19](https://sourceforge.net/p/navit/feature-requests/19)

**Comment by jandegr** [comment]
Hi,

We can search on zipcode in binfile, just gui_internal does not do it, not sure if any steps were taken to let gui_qml do it.

**Comment by aerostitch** [comment]
This was fixed in https://github.com/navit-gps/navit/pull/818 right @metalstrolch ?

Thanks 
Joseph

**Comment by metalstrolch** [comment]
At least for internal GUI. Don't know for qml. Don't know if we should care for qml here.
