### ISSUE TITLE
Make navit say speed bump alerts

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#485]
two requests...
1 -Some one implement on Navit other alert to speed bump \(http://en.wikipedia.org/wiki/Speed\_bump\), but in Brazil this are big, aprox 20-40 cm of height, and the most of gps navigator alert this.
2 - Send text of look out camera, to file .mo\(.po\) to be translated to ours language.

att
diecavallax

Reported by: diecavallax

Original Ticket: [navit/feature-requests/20](https://sourceforge.net/p/navit/feature-requests/20)

**Comment by jkoan** [comment]
Will be tracked at #637
