### ISSUE TITLE
Bluetooth Audio Support (maybe only Android related)

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#486]
When I use Navit on my android smartphone and have it paired using bluetooth with my car radio for using handsfree, the text-to-speech output is not forwarded to the car radio \(and somehow lower volume than unpaired, so maybe android problem?\).

I don't know if Navit itself can decide which audio output device is used when sending text to the TTS service, so if it's not possible to make navit choose it \(or have an influence in it\) please delete this request.

If it's possible somehow by changing some value in the configuration file, it would be great if this would work with the gui, too, so you don't need to change so much when you leave/enter the car.

Reported by: blablabloblo1

Original Ticket: [navit/feature-requests/21](https://sourceforge.net/p/navit/feature-requests/21)

**Comment by jkoan** [comment]
As far as I see this is not a problem from navit (and we can't fix it), it's more a android problem where the audio output has a start lag of more than the length of the tts output.
the connection losses are also not relevant to navit, again this is android.
