### ISSUE TITLE
mac osx needs machine/endian.h inclusion

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#509]
src/endianness.h contains \#include &lt;endian.h&gt; which is machine/endian.h on Mac OSX. It also includes byteswap.h which does not exist at all on Mac OSX, making compilation impossible.

I found this patch that works around it \(http://wiki.openmoko.org/wiki/User:SNMoore\#Patch\_to\_work\_around\_byteswap.h\_and\_endian.h\_errors\_on\_OS\_X\)

Patch to work around byteswap.h and endian.h errors on OS X

-\#include &lt;byteswap.h&gt;
-\#include &lt;endian.h&gt;
\+
+\#ifndef \_BYTESWAP\_H
+\#define \_BYTESWAP\_H
\+
+//\#warning "byteswap.h is an unportable GNU extension\!  Don't use\!"
\+
+static inline unsigned short bswap\_16\(unsigned short x\) \{
\+  return \(x&gt;&gt;8\) | \(x&lt;&lt;8\);
+\}
\+
+static inline unsigned int bswap\_32\(unsigned int x\) \{
\+  return \(bswap\_16\(x&0xffff\)&lt;&lt;16\) | \(bswap\_16\(x&gt;&gt;16\)\);
+\}
\+
+static inline unsigned long long bswap\_64\(unsigned long long x\) \{
\+  return \(\(\(unsigned long long\)bswap\_32\(x&0xffffffffull\)\)&lt;&lt;32\) |
+\(bswap\_32\(x&gt;&gt;32\)\);
+\}
\+
+\#endif
\+
\+
+\#include &lt;machine/endian.h&gt;

Reported by: spaetz

Original Ticket: "navit/bugs/20":https://sourceforge.net/p/navit/bugs/20

**Comment by jkoan** [comment]
With the PR #1088 we know that this is obsolete
