### ISSUE TITLE
deprecated "is_in" tag

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#526]
Hi,

According to OSM wiki, the is\_in tag used by maptool will probably be deprecated :
http://wiki.openstreetmap.org/wiki/Placename\_hierachies

Is there any other method to find town location without this tag for maptool.
Many contributor seem to delete this tag.

Regards

Reported by: arnaudlemeur

Original Ticket: [navit/bugs/37](https://sourceforge.net/p/navit/bugs/37)

**Comment by jandegr** [comment]
Has been fixed
