### ISSUE TITLE
Wrong OSD roundabout exit

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#527]
Hi,

On some roundabout, the OSD indication is not consistent with the real roudabout geometry.  \(see attached file for example\)
The vocal indication is correct.

Regards,

Reported by: arnaudlemeur

Original Ticket: [navit/bugs/38](https://sourceforge.net/p/navit/bugs/38)

**Comment by jandegr** [comment]
outdatede, completely reworked in H5
