### ISSUE TITLE
Crash gtk when destination reached with Demo vehicle

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#528]
Activate Demo vehicle in navit.xml:
&lt;vehicle name="Demo" profilename="car" enabled="yes" active="yes" source="demo://"/&gt;

Select a position point and a destination point by clicking on map. Once the destination reached by demo car, move the mouse over navit, the application crash generally the first times and there's the following stack:

\*\*\* glibc detected \*\*\* navit: malloc\(\): smallbin double linked list corrupted: 0x08acfd98 \*\*\*
======= Backtrace: =========
/lib/libc.so.6\(+0x6c501\)\[0x3a3501\]
/lib/libc.so.6\(+0x6f679\)\[0x3a6679\]
/lib/libc.so.6\(\_\_libc\_malloc+0x63\)\[0x3a7f33\]
/lib/libglib-2.0.so.0\(g\_realloc+0x3a\)\[0x17a4ca\]
/lib/libglib-2.0.so.0\(+0x6189f\)\[0x19589f\]
/lib/libglib-2.0.so.0\(g\_string\_sized\_new+0x4f\)\[0x1969df\]
/lib/libglib-2.0.so.0\(+0x4323a\)\[0x17723a\]
/lib/libglib-2.0.so.0\(g\_markup\_parse\_context\_parse+0x72f\)\[0x17904f\]
/usr/lib/libgtk-x11-2.0.so.0\(+0x11ddeb\)\[0xfc3deb\]
/usr/lib/libgtk-x11-2.0.so.0\(gtk\_label\_set\_markup+0xb8\)\[0xfc6618\]
/usr/lib/libgtk-x11-2.0.so.0\(gtk\_tooltip\_set\_markup+0x87\)\[0x10c2737\]
/usr/lib/libgtk-x11-2.0.so.0\(+0x21c7ab\)\[0x10c27ab\]
/usr/lib/libgtk-x11-2.0.so.0\(+0x21d26c\)\[0x10c326c\]
/usr/lib/libgtk-x11-2.0.so.0\(gtk\_main\_do\_event+0x348\)\[0xfd4c58\]
/usr/lib/libgdk-x11-2.0.so.0\(+0x5636a\)\[0x25936a\]
/lib/libglib-2.0.so.0\(g\_main\_context\_dispatch+0x1d5\)\[0x171855\]
/lib/libglib-2.0.so.0\(+0x41668\)\[0x175668\]
/lib/libglib-2.0.so.0\(g\_main\_loop\_run+0x187\)\[0x175ba7\]
navit\[0x8059846\]
navit\(event\_main\_loop\_run+0x1e\)\[0x805ef2e\]
navit\(main\_real+0x25c\)\[0x80525ec\]
navit\(main+0x1b\)\[0x805233b\]
/lib/libc.so.6\(\_\_libc\_start\_main+0xe7\)\[0x34dce7\]
navit\[0x8052281\]

Reported by: *anonymous

Original Ticket: [navit/bugs/39](https://sourceforge.net/p/navit/bugs/39)

**Comment by jkoan** [comment]
Tested with up to date navit, no crash anymore
