### ISSUE TITLE
maptool: orphaned switch: -o/--coverage

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#529]
The help text of maptool talks about a switch named “-o” or “--coverage” which is not implement at least since r2724 of maptool.c.

It seems to me as if this would be a:
• project suffering from bit-rot,
• project that has been superseded by another one or
• a feature not cleanly removed

It would be nice, if someone compent could clear this by eather implementing the command line switch or removing it from the help text. 

Reported by: keinstein

Original Ticket: [navit/bugs/40](https://sourceforge.net/p/navit/bugs/40)

**Comment by pgrandin** [comment]
```
$ grep -ri coverage maptool/
```
Gone.
