### ISSUE TITLE
Vocal direction instructions fails at roundabouts.

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#530]
Platform:	Android at Samsung Galaxy Si9000
SVN-Build:	4118
Notes:		Screenshots are made under Windows at home, because i was driving the car.

In my tests sometimes the vocal direction instructions are wrong. The display is always right, but
the voice is sometimes -1. I have heard one like this \(in german, not exact wording\):

"Bitte den Kreisverkehr an der nullten Ausfahrt verlassen.", see \[2\]

But the right wording should be:

"Bitte den Kreisverkehr an der ersten Ausfahrt verlassen."

The wrong vocal direction instructions are not always wrong. I´ve find out, that often \(but not always\)
the instructions correct, when the streets have the same color \(e.g. yellow, see \[1\]\) and always
fails on roundabouts with different street colors \(e.g. red, yellow and white, see \[2\]\).

\[1\] Roundabout-01.png
\[2\] Roundabout-02.png

Reported by: nobody

Original Ticket: [navit/bugs/41](https://sourceforge.net/p/navit/bugs/41)

**Comment by jandegr** [comment]
navigation has been worked a lot on since,
example H5 or this one https://github.com/navit-gps/navit/commit/d068e328245dd1997ce1a108027e319f2e8f5fed#diff-744627ef73670978039ecdb68a04faff
