### ISSUE TITLE
City not found

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#533]
I have installed the latest svn on android.
1\. Navit does not find some citys. f.e. Netherlands,Goes or Netherlands, Zierikzee
2\. In V1.0 I have dutch spoken instructions. Later versions english.

Reported by: nobody

Original Ticket: [navit/bugs/44](https://sourceforge.net/p/navit/bugs/44)

**Comment by jandegr** [comment]
outdated,
I have done plenty of testing with a map of the Netherlands in the last few years, must have been fixed at some point.
