### ISSUE TITLE
Dutch instructions

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#534]
I have installed the latest SVN.
In version 1.00 Navit gives dutch spoken instructions.
Later versions he gives english spoken instructions

Reported by: nobody

Original Ticket: [navit/bugs/45](https://sourceforge.net/p/navit/bugs/45)

**Comment by pgrandin** [comment]
This looks more like a user support than an actual bug.
Navit will refer to the system locale for the language to use in the UI.
When using espeak, espeak needs to be configured to select the proper language too : https://wiki.navit-project.org/index.php/Speech#Configuring_Speech_in_your_language
