### ISSUE TITLE
Android: the menu start inside the notification bar

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#550]
Android 7.0
Samsung J7 prime
When clicking on the 3 dots to get the menu, the menu starts from the top of tge screen but this part is in the notification card so half of the 1st elt (download map) triggers the android notification menu when you click on the first half of the element which is annoying.

Note that the fact that the button triggering the menu is on the righr and the menu appears on the right which is strange.

**Comment by mvglasow** [comment]
I developed the two features that seem to be interacting in a bad way here: the menu button as well as the semitransparent system bars. As far as I remember, there is no way for an app to influence placement of the Android overflow menu—Android will decide where to place it.

Can you post a screenshot of what you’re seeing?

**Comment by pgrandin** [comment]
@mvglasow should we assign the issue to you?
