### ISSUE TITLE
Support for interactions with navit for more languages?

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#562]
Currently we can interact with Navit in python and I was wondering if anyone would be up to add more languages like lua, ruby, Go etc.
I'd be happy to help especially with Go.
I think those could be written in their own repo to avoid polluting this one.
Wondering if there's a place where there is a full doc with examples done for the existing ones.

**Comment by pgrandin** [comment]
I wonder what the benefit would be.
Outside of python, the best way to interact is probably dbus, which allows us to make it language-agnostic. What are your thoughts?

**Comment by aerostitch** [comment]
* not having to use python if you're not a big fan of python
* allow users to interact with navit can be done via dbus but if you have an already implemented lib to do some basic methods like `CalculateRoute` to which you give coordinates and a options (aviod tolls, shortest, fastest, etc)
* allow end users to reusing the routing engine with another map rendering system not written in C for applications in web interfaces maybe

It's just an idea I'm throwing out there. Wondering if it's worth exploring

**Comment by aerostitch** [comment]
I added a note about that in my ["Fancy ideas for later"](https://github.com/navit-gps/navit/projects/6) project, we'll see what we do about it later.
