### ISSUE TITLE
Avoid embedding jar in git?

### ISSUE THREAD

**Issue by aerostitch** [navit-gps/navit#579]
Hi,

Currently we checked in `gradle/wrapper/gradle-wrapper.jar` and I was wondering if it was possible to avoid keeping jar files in git and use either download a new one or use system packages for that.

On debian, the jar is available in the `libgradle-plugins-java` package and is located in `/usr/share/java/gradle-wrapper.jar`.

This would require an update of `graddlew` and `gradlew.bat`.

Thanks for your help,
Joseph

**Comment by pgrandin** [comment]
Maybe @jandegr will know better about this.
If we want to download the jar from somewhere at build time, we could probably add it here : https://github.com/navit-gps/dependencies

**Comment by aerostitch** [comment]
Why download stuffs when it's available as packages in your distro???

**Comment by pgrandin** [comment]
> either download a new one

Because you asked for it :)

**Comment by jandegr** [comment]
This is just the way they all do it and it works for everybody, AFAIK CI is not a purpose on its own but to verify certain things, as it works now it also verifies that local build will work as intended.
from https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:adding_wrapper

_To make the Wrapper files available to other developers and execution environments you’ll need to check them into version control. All Wrapper files including the JAR file are very small in size. Adding the JAR file to version control is expected. Some organizations do not allow projects to submit binary files to version control. At the moment there are no alternative options to the approach._

**Comment by aerostitch** [comment]
WTF? No alternative approach else than putting binaries into git repos? :scream:

**Comment by jkoan** [comment]
I would vote for change the gradle script so it checks for OS (look if package is available) and if not try to download it. 
I can do the linux script :)

**Comment by aerostitch** [comment]
Sounds good to me @jkoan.

**Comment by jandegr** [comment]
This all souds like overkill, there used to be another one in the repo but is already gone by removing ACRA.
Just you install one and then it will be a trusted source I suppose and done with it, there is more urgent work to do.

**Comment by jkoan** [comment]
I will leave everything as it is for now, as we don't have resources to fight against those little things for now. But i will happily accept PRs which resolve problems in this direction, but they need to target linux and windows.
