### ISSUE TITLE
Windows TTS engine doesn't pronounce correct german language

### ISSUE THREAD

**Issue by harpmaster** [navit-gps/navit#590]
The windows tts engine can't say ü, ä, ß .... maybe you can fix it

**Comment by jkoan** [comment]
This is due to https://github.com/navit-gps/navit/blob/trunk/navit/linguistics.c 
We should probably change it so speech engines which support those characters could get them. Any thoughts @aerostitch @pgrandin @mvglasow ?

**Comment by mvglasow** [comment]
@harpmaster what gets pronounced when a name contains any of these characters? An incorrect sound (such as u for ü) or is the sound omitted?

@jkoan it’s been a while since I last touched this code, but as far as I can tell, linguistics.c just provides a bunch of transformation functions (needed e.g. to search for names with diacritics not found on the keyboard, ensuring that e.g. Überlingen will be found by searching for Uberlingen or Ueberlingen). Naturally, doing the same thing before passing text to a speech engine will result in mispronunciations. Can you elaborate on the linguistics functions involved when text is passed to the speech engine?

**Comment by jkoan** [comment]
thx @harpmaster i will try to dig into it. For me this sounds like a encoding issue. Like Navit sends "Über" but Windows receives something else.
Could you also provide the navit.xml used? (You can use https://gist.github.com/ to upload it)

**Comment by mdankov** [comment]
Looks like wrong TTS language setting...

@harpmaster what is your system locale setting? What language does Navit use for announcements? Does it pronounce English words correctly?

Navit actually does not pass to TTS engine any language information for street names announcements. So if you have selected English routing instructions, it's up to TTS engine to guess that you need proper German street names pronunciation. Some engines may do this well, some don't.

**Comment by harpmaster** [comment]
@mdankov thanks for your response. my TTS settings all are german. in the navit.xml i use 
<config xmlns:xi="http://www.w3.org/2001/XInclude" language="de_AT">
with espeak activated all works fine. when i use balabolka as speech-reader all fine. i use in navit  the comand-line-utility of balabolka
and instead of 
<speech type="espeak" cps="15"/> i use 
<speech type="cmdline" data="balcon.exe -t %s" />
i tried other things but had the same outputs. balcon.exe seems the easiest way to let navit speak with windows-tts.
i didn't try yet the english settings because i will not use it. but if it helps i will get it a try ....

**Comment by mdankov** [comment]
That makes sense. We should figure out how to tell balcon.exe which language we need.

In [the docs](http://balabolka.site/bconsole.htm) it's said one should use -id option to select locale id.

For German it appears id of 7 should be used. So please try

speech type="cmdline" data="balcon.exe -id 7 -t %s"

**Comment by harpmaster** [comment]
-id 7 didn't work. to use the speech with -id you have to install in win 7 for example microsoft-server-voice. so i installed hedda and in the navit.xml

speech type="cmdline" data="balcon.exe -id 0x0407 -t %s" 

it works, but the same problems like before ....

**Comment by mdankov** [comment]
I'm unsure if balcon.exe supports hexadecimal values for id. In the documentation, at least in the sample it's given in decimal. So maybe -id 1031 would be a better try.

But I have another idea. Are you sure navit talks to you with hedda voice? To be sure, try to add -v hedda option to balcon.exe, with or without the -id option.

Another idea would be to experiment with balcon.exe to test if it's able to give correct German pronunciation, running it from command line.

The first tires would be
```
balcon.exe -t "Leipziger Straße"
balcon.exe -v hedda -t "Leipziger Straße"
balcon.exe -id 1031 -t "Leipziger Straße"
balcon.exe -id 1031 -v hedda -t "Leipziger Straße"

```
Another option to play with would be -enc utf8, especially if you have good results directly running balcon.exe versus running it from Navit.

**Comment by harpmaster** [comment]
sorry to say that but all things i already have done, but no success. i tried it again but only balcon.exe in the command-line is given perfect german pronunciation.

if you have to use voices for your choice you have to write for example in navit.xml

<speech type="cmdline" data="balcon.exe -n steffi -t %s" />

-enc utf8 doesn't change anything

i have tried it now with spanish language, downloaded MSSpeech_TTS_es-ES_Helena.msi and it works fine with

speech type="cmdline" data="balcon.exe -id 0x0c0A -t %s"

seems navit has problems with german language ...

**Comment by mvglasow** [comment]
@harpmaster just to clarify, did the Spanish strings you tried have some kind of special character (áéíóú or ñ), and did they get pronounced correctly (ñ probably being the most obvious)?

**Comment by harpmaster** [comment]
good idea to let me check these things, because it doesn't pronounce correctly the words with those special characters. sorry, i didn't noticed before ....

**Comment by mdankov** [comment]
It looks like Navit and balcon use different character encodings. And maybe balcon does not support -enc option for command line parameters.

Then we have a few options to check.

At first, set speech to `<speech type="cmdline" data="cmd /c c:\balcon-helper.bat %s">`

Then create a text file c:\balcon-helper.bat with the following content:

`echo %1 | balcon.exe -enc utf8 -n hedda -i`

If that doesn't help, try placing in that file
```
echo %1 >c:\temp\balcontext.txt
balcon.exe -enc utf8 -n hedda -f c:\temp\balcontext.txt
```

For the latter example to work, there should be a c:\temp\ directory on your computer.

If that still won't help, I'd like to look at the exact file contents c:\temp\balcontext.txt. It would be nice if you could pack it with some archiver like 7zip, rar and put on some binary file sharing resource.

**Comment by mdankov** [comment]
I have mailed to balabolka developer. He was very interested in our problem and has confirmed that -enc option does not work for texts fed to balcon.exe with -t option.

Thanks to Ilya Morozov, there's a new version of balcon.exe on his [site](http://balabolka-tts.ru) supporting our case.

So with balcon.exe 1.46, `<speech type="cmdline" data="balcon.exe -enc utf8 -t %s">` has a good chance to be working for you. Language id and voice name options may still be needed, of course.

**Comment by harpmaster** [comment]
that's a wonderful information! i tried it immediately and it works! i also use spanish voice helena with the same options and what a great pronunciation.

so the commands to use are

speech type="cmdline" data="balcon.exe -enc utf8 -n hedda -t %s" 
or for other installed speeches for example
speech type="cmdline" data="balcon.exe -enc utf8 -n steffi -t %s"
speech type="cmdline" data="balcon.exe -enc utf8 -n helena -t %s"

so big hug to Ilya Morozov and of course you!
