### ISSUE TITLE
cannot install navit-0.5.1-arm-release-unsigned.apk

### ISSUE THREAD

**Issue by rmsppu** [navit-gps/navit#630]
I'm unable to install the 0.5.1 under Lineage OS (Android 7.1.2) on a Samsung Note 8 (GT-N5510) -- it reports that the application may be corrupt, or under Android 6.0.1 on a Kyocera Duraforce Pro (VZW), which reports "There was a problem parsing the package".

The package file is not corrupt -- the contents of the zip file can be extracted.

**Comment by jkoan** [comment]
Hi @rmsppu 
Sorry for the trouble, for installing you need a release signed version of our software.
For example `[this](https://7521-30791823-gh.circle-artifacts.com/0/root/project/android-arm/navit/android/bin/navit-3de4a6cccf934cbd169e8189b782f440b3dd04d0-arm-release-signed.apk)` should work
