### ISSUE TITLE
Notification icon missing again on Android Oreo

### ISSUE THREAD

**Issue by mvglasow** [navit-gps/navit#640]
### Steps to reproduce

1. Install a recent build of Navit on Android Nougat (7.x).
2. Start Navit and observe the notification icon.
3. Install the same build on Android Oreo (8.x), or upgrade the OS on the device.
4. Start Navit again and observe the notification icon.

### Expected behavior

Notification icon appears while Navit is running, regardless of OS version

### Actual behavior

Notification icon appears on Android 7 but not on Android 8.

### Versions tested

Navit d421350 (actually a branch of it, with no changes regarding the notification), on LineageOS 14.1 and 15.1 respectively.

**Comment by jkoan** [comment]
Hi @mvglasow
I can reproduce the same issue on my Oneplus 3T with Android 8.0.0 (Original Firmware -> OxygenOS)
I will look into it again soon.

**Comment by jkoan** [comment]
It's probably due to the new channels.
This post has a good description around this: https://stackoverflow.com/a/43093261

So we probably only need to change things slightly
