### ISSUE TITLE
maptool crash read pbf file

### ISSUE THREAD

**Issue by DerKleinePunk** [navit-gps/navit#648]
(gdb) run
Starting program: /home/punky/develop/navit-build/navit/maptool/maptool -a debug -P -i /home/punky/develop/libosmscout-code/maps/hessen-latest.osm.pbf hessen.bin
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
PROGRESS: Phase 1: reading input data 0:00 0 MB

Program received signal SIGSEGV, Segmentation fault.
0x00005555555900e7 in osmpbf__blob_header__init (message=0x56f72bb0) at /home/punky/develop/navit/navit/maptool/generated-code/fileformat.pb-c.c:49
49	    *message = init_value;
(gdb) 

~/develop/navit-build/navit$ ./navit -v
Running from source directory
navit 0.5.1+git:e6ba22a2-

Debian Linux 64 Bit

**Comment by bignaux** [comment]
Could you try on top of recent git ?

**Comment by DerKleinePunk** [comment]
after delete old output dir and rebuild all

PROGRESS12: Processed 1426692 nodes (0 out) 4648076 ways 0 relations 5301 tiles 1:53 19 MB
PROGRESS: Phase 13: done 1:53 19 MB

It seems it is done but in Navit i can't see the map

<graphics type="sdl"/>

<mapset enabled="no">
			<xi:include href="$NAVIT_SHAREDIR/maps/*.xml"/>
		</mapset>

		
		<mapset enabled="yes">
			<map type="binfile" enabled="yes" data="/home/punky/develop/navit-build/navit/maptool/hessen.bin"/>
		</mapset>
I have try to set a new pos but the screen is always one color

**Comment by jkoan** [comment]
Wenn you search for something that should be in the map, could that be found?

**Comment by DerKleinePunk** [comment]
the search is working after search for an City the map shows something. it muss be an problem with the current pos.

The Text for this that not write on white background is difficult to read but this is an other issue.
I close this. Thanks.
