### ISSUE TITLE
Scale color on new "Medion" tablet is white

### ISSUE THREAD

**Issue by mensch21** [navit-gps/navit#670]
Hello,
on my latest tablet (from Medion company) the color for "scale" is now white. On my former tablets (Lenovo) the color was black. In white color the scale is not readable on the map - not enough contrast.
Would it be possible to get the color for "scale" configured? Up to now it is not possible.
Example: <osd type="scale" enabled="yes" x="660" y="-90" w="600" h="72" font_size="600" color="#0000ff"/>
Best Regards
Joachim Brachvogel

**Comment by lains** [comment]
The color for OSD "scale" item is determined first by a call to [osd_set_std_attr](https://github.com/navit-gps/navit/blob/trunk/navit/osd/core/osd_core.c#L3821), this color is then set a the inverse of the `text_color` in [osd_scale_init](https://github.com/navit-gps/navit/blob/trunk/navit/osd/core/osd_core.c#L3790).
But then, there is [additional code that set the color to almost white if it was calculated to be dark](https://github.com/navit-gps/navit/blob/trunk/navit/osd/core/osd_core.c#L3796).
This is probably where the color could be forced to a given value by configuration in the xml config file.

**Comment by mensch21** [comment]
Many thanks. This invertation is tricky "opc->osd_item.color_fg.r = 0xffff-opc->osd_item.text_color.r;",...
Months ago I checked with text_color="#000000" but nothing had changed.
Now I noticed in Navit-Wiki: "For some reason, #000000 does not work, so #111111 is the next best guess for near-black.". I tried text_color="#111111" and the scale is "nearly" :-) black. Great is works.
