### ISSUE TITLE
Wiki download link still points to 0.5.0

### ISSUE THREAD

**Issue by lains** [navit-gps/navit#675]
On the Wiki's homepage for navit (http://www.navit-project.org/), the "latest release" download link is pointing to an old (0.5.0) release:
https://github.com/navit-gps/navit/releases/tag/v0.5.0

**Comment by lains** [comment]
Shall 0.5.3 be considered as stable and thus make the Wiki point to that release?
https://github.com/navit-gps/navit/releases

**Comment by aerostitch** [comment]
Yes we should.
On that page are also incorrect:
* the link to the download center (points to a 404)
* the link to gpsd (the domain don't exist anymore)

**Comment by lains** [comment]
Rework on https://www.navit-project.org/ seems to be finished and points to the correct URLs.
I think we should close this.
