### ISSUE TITLE
Allow QR code input for GPS coordinates

### ISSUE THREAD

**Issue by lains** [navit-gps/navit#678]
On Android, when scanning a QR code for GPS coordinates, and allow navit to handle this type of input to open a contextual menu for these GPS coords (same GUI as when typing the coordinates manually).

To generate QR codes for geo coords, use "Contents" type="Geo location" on the following website
https://zxing.appspot.com/generator

For example, the Android application "Barcode scanner", when scanning a geo QR code, allows two actions: "Display map" or "Navigate there"

Example QR code:
![eiffel_tower](https://user-images.githubusercontent.com/383502/46258260-a45e9c80-c4c7-11e8-9875-b1f42ef8c16e.png)

**Comment by jkoan** [comment]
This should be easy by processing the geo intent (which will be send by the qr-scanner app of your choise) which is planned aleready ;)

**Comment by lains** [comment]
I am currently implementing a similar feature , but the other way around:
In Android, when tapping on a specific location on the map, have the contextual menu allow to open the location in an external Android application (using the geo intent).

**Comment by lains** [comment]
Implemented in #812
