### ISSUE TITLE
0.5.0 tarball has changed

### ISSUE THREAD

**Issue by rossburton** [navit-gps/navit#712]
We just noticed that the navit-0.5.0 tarball checksum has changed.  Comparing the old navit 0.5.0 from our mirrrors and a freshly downloaded copy:

$ md5sum *
16ceaa14aaa22d15f156a5ed3478b731  new-navit-0.5.0.tar.gz
242f398e979a6b8c0f3c802b63435b68  old-navit-0.5.0.tar.gz

Unpacking them shows what happened:

$ tar ztvf old-navit-0.5.0.tar.gz |head
drwxrwxr-x root/root         0 2015-12-31 07:42 navit-0.5.0/
-rw-rw-r-- root/root        35 2015-12-31 07:42 navit-0.5.0/.gitignore
-rw-rw-r-- root/root       338 2015-12-31 07:42 navit-0.5.0/AUTHORS
-rwxrwxr-x root/root     28998 2015-12-31 07:42 navit-0.5.0/CMakeLists.txt
-rw-rw-r-- root/root      3763 2015-12-31 07:42 navit-0.5.0/COPYING
-rw-rw-r-- root/root       144 2015-12-31 07:42 navit-0.5.0/COPYRIGHT
-rw-rw-r-- root/root       210 2015-12-31 07:42 navit-0.5.0/ChangeLog
-rw-rw-r-- root/root     17987 2015-12-31 07:42 navit-0.5.0/GPL-2
-rw-rw-r-- root/root     25284 2015-12-31 07:42 navit-0.5.0/LGPL-2
-rw-rw-r-- root/root       681 2015-12-31 07:42 navit-0.5.0/Makefile.am

$ tar ztvf new-navit-0.5.0.tar.gz |head
drwxrwxr-x root/root         0 2015-12-31 07:42 navit-gps-navit-4c7e3da/
-rw-rw-r-- root/root        35 2015-12-31 07:42 navit-gps-navit-4c7e3da/.gitignore
-rw-rw-r-- root/root       338 2015-12-31 07:42 navit-gps-navit-4c7e3da/AUTHORS
-rwxrwxr-x root/root     28998 2015-12-31 07:42 navit-gps-navit-4c7e3da/CMakeLists.txt
-rw-rw-r-- root/root      3763 2015-12-31 07:42 navit-gps-navit-4c7e3da/COPYING
-rw-rw-r-- root/root       144 2015-12-31 07:42 navit-gps-navit-4c7e3da/COPYRIGHT
-rw-rw-r-- root/root       210 2015-12-31 07:42 navit-gps-navit-4c7e3da/ChangeLog
-rw-rw-r-- root/root     17987 2015-12-31 07:42 navit-gps-navit-4c7e3da/GPL-2
-rw-rw-r-- root/root     25284 2015-12-31 07:42 navit-gps-navit-4c7e3da/LGPL-2
-rw-rw-r-- root/root       681 2015-12-31 07:42 navit-gps-navit-4c7e3da/Makefile.am

Looks like a generated tarball has been replaced with a git archive of 0.5.0 (that SHA is the 0.5.0 tag).  I can provide the previous tarball if you'd like to restore it.

Things that break due to this change:
- anything that assumes the content of navit-0.5.0.tar.gz is a directory called navit-0.5.0/
- anything that verifies tarballs against known checksums

Note that OpenEmbedded, the build system I work on, is both of those.

**Comment by jkoan** [comment]
Hi,
in fact this is a problem, and we should do research on this. 
But my question is why do you use a outdated version? We are already on 0.5.3.

**Comment by jkoan** [comment]
File from github release:
242f398e979a6b8c0f3c802b63435b68
File from Sourceforge release:
16ceaa14aaa22d15f156a5ed3478b731

Github: https://github.com/navit-gps/navit/releases/tag/v0.5.0
Sourceforge: https://sourceforge.net/projects/navit/files/v0.5.0/

You are right that they should be the same, but we can't change it because of the reasons you already give. If someone download from Sourceforge and knows the md5sum of this file we would brake his old build by updating the file the the right one.
so I am closing here because we can't do it any better. We can only make it better in the future.

**Comment by rossburton** [comment]
I still don't understand how the file on SourceForge changed.  We use that tarball in our QA and it only recently changed.

Note that you can't rely on the GitHub "source code" links (such as 
https://github.com/navit-gps/navit/archive/v0.5.0.tar.gz) to produce the same tarball md5sum over time, they're generated on demand by git-archive and cached, so over time they can (and do) get regenerated and change.

As the old 0.5.0 tarball has been around for a long time, I really do endorse replacing the tarball (and also uploading the same tarball to github as a release artifact).
