### ISSUE TITLE
Unable to use binary maps with on Raspbian

### ISSUE THREAD

**Issue by NetForces** [navit-gps/navit#736]
I have Navit 0.5.0 installed on Raspbian (would love to use 0.5.3 but could not find a Raspbian package for it).

I downloaded a very small map from Planet Extractor (http://maps9.navit-project.org/api/map/?bbox=-74.0,45.4,-73.4,45.7) and when trying to use this map I get the following:

```
pi@raspberrypi:~ $ navit -d 1
error:navit:xinclude:Unable to include /usr/share/navit/maps/*.xml
warning:map_binfile:binfile_read_eoc64:map file /home/pi/maps/montreal.bin: eocl wrong
warning:navit:command_object_get_attr:cannot retrieve attributes from none ((nil)), func=(nil)
warning:navit:command_get_attr:could not retrieve 'name' from 'none'
```

Tried various binary maps, always the same.

Even if it's a warning and I see the map loaded:

![10 0 9 148 raspberrypi - vnc viewer 2019-01-24 16-45-39](https://user-images.githubusercontent.com/984831/51710527-7d3c5580-1ff7-11e9-8a47-97474d971cb3.png)

I can't search any city or streets.

Any hints appreciated.

**Comment by NetForces** [comment]
Was able to compile master on my Pi and I get the same result:

```
pi@raspberrypi:~/Documents/navit-build/navit $ ./navit -d 1
Running from source directory
warning:map_binfile:binfile_read_eoc64:map file /home/pi/maps/montreal.bin: eocl wrong
warning:navit:layout_new:Another layout with name 'Bike' has already been parsed. Discarding subsequent duplicate.
warning:navit:layout_new:Another layout with name 'Car-Android' has already been parsed. Discarding subsequent duplicate.
warning:navit:layout_new:Another layout with name 'Car-dark' has already been parsed. Discarding subsequent duplicate.
warning:navit:layout_new:Another layout with name 'Car-simple' has already been parsed. Discarding subsequent duplicate.
warning:navit:layout_new:Another layout with name 'Car' has already been parsed. Discarding subsequent duplicate.
warning:navit:layout_new:Another layout with name 'T@H' has already been parsed. Discarding subsequent duplicate.
warning:graphics_gtk_drawing_area:get_data:Failed to open iPaq sleep file. Error-Code: 0
```

```
pi@raspberrypi:~/Documents/navit-build/navit $ ./navit -v
Running from source directory
navit 0.5.3+git:845dd409-
pi@raspberrypi:~/Documents/navit-build/navit $ 
```

Build-in Munchen maps do work but not a downloaded binary from Planet Extractor.

**Comment by NetForces** [comment]
Actually is I enable the build-in maps it also gives a similar warning and I can't find Munchen if I I go in Actions -> Town...

```
pi@raspberrypi:~/Documents/navit-build/navit $ ./navit -d 1
Running from source directory
warning:map_binfile:binfile_read_eoc64:map file /home/pi/Documents/navit-build/navit/maps/osm_bbox_11.3,47.9,11.7,48.2.bin: eocl wrong
warning:navit:layout_new:Another layout with name 'Bike' has already been parsed. Discarding subsequent duplicate.
warning:navit:layout_new:Another layout with name 'Car-Android' has already been parsed. Discarding subsequent duplicate.
warning:navit:layout_new:Another layout with name 'Car-dark' has already been parsed. Discarding subsequent duplicate.
warning:navit:layout_new:Another layout with name 'Car-simple' has already been parsed. Discarding subsequent duplicate.
warning:navit:layout_new:Another layout with name 'Car' has already been parsed. Discarding subsequent duplicate.
warning:navit:layout_new:Another layout with name 'T@H' has already been parsed. Discarding subsequent duplicate.
warning:graphics_gtk_drawing_area:get_data:Failed to open iPaq sleep file. Error-Code: 10
```

**Comment by mvglasow** [comment]
Just to be sure, you have made sure you’re searching in the correct country, right? (There’s a flag next to the control where you enter the name of the town to search for; click it to set the country.)

**Comment by NetForces** [comment]
@mvglasow you are right !

![10 0 9 148 raspberrypi - vnc viewer 2019-01-25 16-38-25](https://user-images.githubusercontent.com/984831/51774265-ae805880-20bf-11e9-8699-b17ccd91b22f.png)

I saw that flag before but thought it was the language setting (defaulted to GB).

How do I change this default ?

**Comment by mvglasow** [comment]
Defaults are governed by the system locale setting. `en_CA` should do the trick. You can also set the locale specifically for Navit in navit.xml, via the `language` attribute of the `config` element. Like this:

    <config xmlns:xi="http://www.w3.org/2001/XInclude" language="en_CA">

Navit evaluates the language and country part separately, thus allowing even exotic combinations such as `en_IT` (English-language UI, country search defaults to Italy).

**Comment by NetForces** [comment]
Perfect ! I'm closing this as it's seems to work as designed. Thanks !

**Comment by lains** [comment]
Hopefully, implementing https://github.com/navit-gps/navit/issues/676 should improve user experience for users that have a location and language combination that is not supported out-of-the-box...

**Comment by Fadyayman1011** [comment]
is it possible to show maps in navit without connecting GPS??

**Comment by jkoan** [comment]
> is it possible to show maps in navit without connecting GPS??

Yes it is. If you don't see the map there are two most likely causes.
1) Your viewport is set somewhere where no map data is available. You can check if the map is loaded correctly by going to actions and search for something within the map you installed. When searching look out that the country in the top left corner is set correctly.
2) This one only applies when you are using a Debian based distribution or related (Debian/Ubuntu/Raspberry pi OS/...): If you installed navit from the packages manager you got a bug where the layout files are missing. If this is the case you need to manually download the navit_laxout_*.xml files from here https://github.com/navit-gps/navit/tree/trunk/navit and install these files next to your navit.xml
