### ISSUE TITLE
Impossible to register on forum

### ISSUE THREAD

**Issue by kontrarie** [navit-gps/navit#742]
I feel sure this is not the right place to post this issue, but I cannot find any better. Sincere apologies! For a couple of days now I have been trying to register on the navit forum, but get rewarded for my efforts with

Errno 2: pg_connect(): Unable to connect to PostgreSQL server: could not connect to server: No route to host Is the server running on host "postgres" (172.17.0.4) and accepting TCP/IP connections on port 5432? at [ROOT]/includes/db/postgres.php line 108 []

It would seem there is a shortage of support, I might perhaps be able to contribute my humble bit, feel free to get in touch.

M.fr.Gr.,

**Comment by kontrarie** [comment]
Sorry, I should have included the url I am connecting to, it is
https://forum.navit-project.org/ucp.php?mode=register

**Comment by kontrarie** [comment]
and then I clicked the 'close' accidentally...

**Comment by jkoan** [comment]
Yes your right, our database server is down right now. this is also the reason why the wiki is down as well. If you need help feel free to join us on IRC or Discord:
IRC: https://web.archive.org/web/20180213151510/http://webchat.freenode.net/?channels=navit
Discord: https://discordapp.com/invite/ADfXxZx

**Comment by kontrarie** [comment]
Thanks for prompt reaction! My issue is not life-threatening, actually not even really urgent. So I'll prefer to quietly wait for you to get things right. Again, if I can help (on the longer term) to keep the machinery up and running, feel free to offer me a drink :) !

**Comment by jkoan** [comment]
Forum and Wiki should be up soon (work is ongoing). We would be happy to welcome you to our community if you want to help ;) we are always open to chat on the mentioned platforms (which are synced as well)

**Comment by kontrarie** [comment]
Nice! "Chat" is a bit counternatural to me, though - call me kind of slowish, preferring to write things out in calm... E-mail is my preferred medium, slow but reliable and utterly traceable (important for people with poor memories, like myself) which of course places me on the "infrastructure" side of any project. Mail very welcome at karlchen9 at adelco punkt be

**Comment by kontrarie** [comment]
sorry, make that
karlchen9 at skynet punkt be

**Comment by hoehnp** [comment]
kontrarie: if you are curious, you can also visit our talk at FOSDEM in Brussels on Sunday.

**Comment by jkoan** [comment]
Closing this issue anyway because thew real issue is over (wiki and forum) are back up.

**Comment by kontrarie** [comment]
@hoehnp: FosDem sounds like a great idea, expect me! If I catch the early spring sun I might be wearing some funny red hat...

@jkoan: yes, the forum and the wiki are up again, unfortunately I am still unable to register... Continue here or start new thread?

**Comment by kontrarie** [comment]
Permission error

You do not have permission to do that, for the following reason:

You are not allowed to execute the action you have requested.

**Comment by kontrarie** [comment]
is what I get when pointing my browser (Firefox) at https://wiki.navit-project.org/index.php/Special:CreateAccount

**Comment by kontrarie** [comment]
I still cannot register on the Navit wiki/forum. More than three months later, I still get slapped as reported above. HELP!

Permission error

You do not have permission to do that, for the following reason:

You are not allowed to execute the action you have requested.
