### ISSUE TITLE
Embedding navit in other apps

### ISSUE THREAD

**Issue by viktorgino** [navit-gps/navit#752]
Hi

I am developing a headunit project here: https://github.com/viktorgino/headunit-desktop

I'm trying to embed Navit into my app, and I would need a little help understanding how Qt is being setup and loaded. Would anyone be able to give me a few pointers to get started with? I managed to enable the QML2 gui, but it is unclear how its actually loaded etc.

Thanks in advance.

**Comment by viktorgino** [comment]
I've figured this out, had to change a few things tho, see https://github.com/viktorgino/navit for more details

**Comment by shadabmustaafa** [comment]
Hi,
I'm looking to embed Navit inside another .net application and am unable to find any resources. By chance any reference to relevant resource or sample code? Any wrapper to be used in .netcf35 to use navit with some basic functionalities like navigate to a given location (lat/lon), cancel current running navigation, etc.

Much thanks in advance.
