### ISSUE TITLE
data structrue for navigation

### ISSUE THREAD

**Issue by xiaozhi12345678** [navit-gps/navit#757]
I want to know the data structure of input and output of the navigation.could you tell me where are them and API function?Thank you!

**Comment by mvglasow** [comment]
You might look at `route.c`, which has everything for finding the shortest path from A to B, and `navigation.c`, which generates maneuvers for the path, as well as their header files `route.h` and `navigation.h`. I have been adding doxygen comments to many of the functions and structures over the past few years, as I had to muddle my way through this myself.
