### ISSUE TITLE
Ci builds for MacOS

### ISSUE THREAD

**Issue by jkoan** [navit-gps/navit#767]
At some point navit was able to be built on macos and even for iPhone.
as circleci has a macos executor we should probably use it to build navit there also.
I also have seen that @OLFDB did some changes to Apple, so probably he can state the current state of macos build and help us with a guide how to build it (if there are any macos specific steps).

It would also be required to think about how we would handle ci builds as we don't have unlimited time/resources to build.

**Comment by lains** [comment]
Yes, I'd love to see an automated build for IOS. [Existing Wiki page](http://wiki.navit-project.org/index.php/IOS) point to a non-existent URL for downloading pre-compiled images at  http://download.navit-project.org/navit/iphone/cydia/, actually this URL is now http://legacy.navit-project.org/navit/iphone/cydia/.
I did download a package in the past and it was quite old (obsolete).

**Comment by OLFDB** [comment]
The build for macos is working, but there is no GUI... I didn't have time to dig further into it yet.
CI for macos is not free as I have seen, but app signing is not possible using cross compilers.
For ios it would be the best to make Navit available in Apples appstore, so it doesn't require a jailbroken device.

**Comment by jkoan** [comment]
I think as a open source project we get some free time on the macos machines. But don't know for sure.
The problem with Apple appstore is that you need a dev account which costs monthly a big chunk of money :(

**Comment by mvglasow** [comment]
If we support the platform and we have a way to do CI for it, I’m all in for it. If folks out there use Navit on these platforms, I’d love to know that my most recent changes are not breaking things for them (at least to the extent CI can do that).

As for the app store, to my knowledge it has terms which are incompatible with the GPL (see https://en.wikipedia.org/wiki/GNU_General_Public_License#Legal_barrier_to_app_stores and https://en.wikipedia.org/wiki/App_Store_(iOS)#Controversial_apps), which has led to the removal of all GPL apps. Additionally, Navit may not comply with other terms of theirs (I have heard of, among others, a ban on custom keyboards, which would definitely be an issue for us). We’d likely get a rejection notice, complete with an NDA (which means whoever gets the notice might not even be able to share it with other devs, let alone potential new devs). If we decided to get compliant, we would not even be able to discuss the necessary design changes, which would create all kinds of further complications for us. Not to mention that I wouldn’t like a big corporation being able to tell us what we can do and not do. Apple doesn’t seem to like FOSS much (which I admit is why I don’t like Apple much).

On the other hand, there’s Cydia and possibly other distribution channels which are not controlled by Apple, and therefore make less of a fuss about the license or functionality of apps. On the other hand, app stores like Cydia would limit our audience to people with jailbroken devices. For non-jailbroken devices, the only way I know of is via an enterprise certificate, but I have no idea how feasible that is for us.

**Comment by charlescurley** [comment]
On Wed, 03 Apr 2019 17:55:22 -0700
mvglasow <notifications@github.com> wrote:

> As for the app store, to my knowledge it has terms which are
> incompatible with the GPL (see
> https://en.wikipedia.org/wiki/GNU_General_Public_License#Legal_barrier_to_app_stores
> and
> https://en.wikipedia.org/wiki/App_Store_(iOS)#Controversial_apps),
> which has led to the removal of all GPL apps.

Not entirely. Nextcloud distributes their client for iOS under the GPL,
version 3, with an additional license proviso, which is spelled out in
the file COPYING.iOS. https://github.com/nextcloud/ios I just updated
my copy through the app store two days ago.

Of course, I have no idea how much Apple knows of or approves of this
approach.



-- 
"When we talk of civilization, we are too apt to limit the meaning of
the word to its mere embellishments, such as arts and sciences; but
the true distinction between it and barbarism is, that the one
presents a state of society under the protection of just and
well-administered law, and the other is left to the chance government
of brute force."
- The Rev. James White, Eighteen Christian Centuries, 1889
Key fingerprint = CE5C 6645 A45A 64E4 94C0  809C FFF6 4C48 4ECD DFDB
https://charlescurley.com

**Comment by mvglasow** [comment]
I could imagine Apple being OK with this exception. Things get interesting, though, if multiple copyright holders are involved. Nextcloud is a fork of Owncloud, thus parts of the software would be copyrighted by the latter, and even if Nextcloud decides not to pursue App Store distribution as a license violation, Owncloud still might.

Same over here: copyright remains with the individual contributors unless they have transferred it to someone else. Therefore, such a commitment would have to be made by everyone—including past contributors, and possibly heirs of deceased former contributors. On the other hand, the harder it is to get hold of someone for a statement, the less interested they likely are in pursuing license violations.

**Comment by bignaux** [comment]
for Macosx , let consider use nix on darwin. https://www.softinio.com/post/moving-from-homebrew-to-nix-package-manager/
