### ISSUE TITLE
Impossible to register on forum (still not solved)

### ISSUE THREAD

**Issue by kontrarie** [navit-gps/navit#772]
I still cannot register on the Navit wiki/forum. More than three months later, I still get slapped as reported before. HELP!

Permission error

You do not have permission to do that, for the following reason:

You are not allowed to execute the action you have requested.

**Comment by jkoan** [comment]
@pgrandin https://wiki.navit-project.org/index.php/Special:CreateAccount does not let you create a new account. Forum seem to be okay (links you to wiki, login working for existing accounts)

**Comment by kontrarie** [comment]
Any news?

**Comment by jkoan** [comment]
The registration was disabled due to spam, now it is enabled again :)

**Comment by jemilambi** [comment]
Jkoan?  I face the same issue today as kontrarie on 7 April 2019.   Registration seems to be disabled due to spam.
I need this forum because my navit gives me the textual roadmap but no graphical roadmap.  If you don't know the answer.  Then I need that forum.  Thank you.  Regards,

**Comment by hoehnp** [comment]
@jemilambi, such a topic should rather be created as an issue on GitHub. I don't know if anyone is still actively monitoring the forum.
