### ISSUE TITLE
Feature Request: Navigation inside a building

### ISSUE THREAD

**Issue by CorporateDrone** [navit-gps/navit#773]
We'd like to provide turn-by-turn directions inside large metal buildings, where GPS is unreliable. Can navit use things like wifi signal strength or Bluetooth beacons to get location?

**Comment by mvglasow** [comment]
It depends on the platform your are planning to use, and the location sources available on that platform.

Navit gets location data through a `vehicle` instance, of which different implementations are available. For platforms such as Android, which provide their own location API, we have a dedicated vehicle instance which obtains whatever the API returns. We also have some generic `vehicle` implementations which are not strictly platform-dependent, for sources such as NMEA or gpsd. YMMV with those.

For Android (which I happen to know best), applications can select their desired location provider by criteria. Ours are such that we disable network locations as soon as we get a GPS signal: wifi and cells would be used to get the initial position until GPS is available, but then they would be disabled and not be re-enabled even if there were a GPS outage. However, that could be adapted.

Navit itself does not scan for wifis etc., nor does it resolve wifi BSSIDs and similar into coordinates—that would require an external tool. If that external tool mimics a location source supported by one of Navit’s generic `vehicle` implementations, it should work (possibly requiring minor modifications).

**Comment by CorporateDrone** [comment]
Thank you for the thorough explanation. These will be for forklifts fitted with Android devices. I'll research what Android's API provides.
