### ISSUE TITLE
Migrate trac tickets

### ISSUE THREAD

**Issue by mvglasow** [navit-gps/navit#776]
It seems trac is de facto not being used for new tickets any more. There is still a huge backlog of old tickets, but updating them is difficult as our self-hosted infrastructure is not always reliable (for example, right now I cannot log in using my wiki account). Also, having tickets scattered across two systems (Github and trac) is not exactly great.

On the other hand, I am not necessarily in favor of entrusting our tickets to a closed-source system.

An option would be to move our development to Gitlab, which is built on open-source software and allows projects to be exported with everything attached to it. An automated import for Github projects is available, which moves not only the code but also tickets and PRs (I have successfully moved one of my own Github projects to Gitlab in this manner). I have also seen solutions to import Trac tickets into a Gitlab project, though we would have to see if that path also works for consolidating two ticket systems into one.

The one thing which would need some work is CI: As a transitional solution, AFAIK we can set up an automated push from Gitlab to Github—every commit that is pushed to Gitlab would be propagated to Github automatically, and trigger CircleCI. This would only work for the main project but not for forks. On the long run, Gitlab has its own CI, functionally very similar to CircleCI, so we could even do our CI on the same platform.

Somewhat related to #425, which is about the wiki. Both can be tackled separately, but for both I would suggest moving to Gitlab.

**Comment by jkoan** [comment]
Gitlab Sync already set up: https://gitlab.com/navit-gps/navit

**Comment by mvglasow** [comment]
As far as I can see, it is currently configured to pull changes from Github, but changes made on the Gitlab side will not be propagated back to Gitlab—that feature is available but we would need to set it up.

Also, it appears that tickets can only be imported together with the repo, not into an existing repo, and once the import is complete, there doesn’t seem to be a way to pull in changes made on the Github side after that. So we might need to redo the import, with tickets and merge requests, and then immediately disable these features on Github. (Of course, if I have overlooked something, I’d be happy to know!)

**Comment by hoehnp** [comment]
@jkoan, @aerostitch: i would suggest to close this ticket now. We wont do any more trac migration I assume.
