### ISSUE TITLE
Update NavIt on F-Droid

### ISSUE THREAD

**Issue by Matombo** [navit-gps/navit#792]
The latest version uploaded to the F-Droid store is 0.5.0-6382 from 2015
Please update that download to the current 0.5.3 release.

**Comment by mvglasow** [comment]
@jkoan anything I can/need to do here? The build recipe is awaiting a [merge request](https://gitlab.com/fdroid/fdroiddata/merge_requests/5289), after that we should have an update on F-Droid as soon as we tag a new release. So the main questions are: when do we want to tag a new release, and what needs to happen before we can do that?

**Comment by jkoan** [comment]
Sorry, no, it was intended to be the reminder about what you already told in the PR, but since this seems to be done this can be closed. Update will happen when we make the release (after manually updating the version information at https://github.com/navit-gps/download-center/blob/master/_data/version.yml.
I will make a Release this Sunday (01.09.2019) if any concerns please share on irc or open a issue with milestone 0.5.4

**Comment by Matombo** [comment]
A gentle push to this issue since 5.4 got released now.

**Comment by jkoan** [comment]
https://f-droid.org/wiki/page/org.navitproject.navit/lastbuild_2001180336 failed due to CXX not found. 
Now i disabled CXX on the android build. 
@mvglasow CXX is not used by android anyway, right?
if this test release (v0.5.4-fdroid.1) is working, i will create a v0.5.5 release for this bugfix.

**Comment by licaon-kter** [comment]
Umm https://f-droid.org/wiki/page/org.navitproject.navit/lastbuild_2002100212

Also, FYI https://gitlab.com/fdroid/fdroiddata/issues/1929

**Comment by jkoan** [comment]
> Umm https://f-droid.org/wiki/page/org.navitproject.navit/lastbuild_2002100212
> 
Already seen, I made a mistake while disable cxx. Already created 0.5.4-fdroid.2. Now waiting for the next checkupdates from fdroid to run
> Also, FYI https://gitlab.com/fdroid/fdroiddata/issues/1929

We don't use qt on Android we already built everything for the Android app our self

**Comment by licaon-kter** [comment]
Still fails: 
[org.navitproject.navit_2002100854.log.gz](https://github.com/navit-gps/navit/files/4191679/org.navitproject.navit_2002100854.log.gz)

**Comment by jkoan** [comment]
> Still fails:
> [org.navitproject.navit_2002100854.log.gz](https://github.com/navit-gps/navit/files/4191679/org.navitproject.navit_2002100854.log.gz)

Thx :)
Could you also send in the two mentioned files? 
>See also "/home/vagrant/build/org.navitproject.navit/CMakeFiles/CMakeOutput.log".
See also "/home/vagrant/build/org.navitproject.navit/CMakeFiles/CMakeError.log".

**Comment by licaon-kter** [comment]
Sure 
[Cmakeoutputs.zip](https://github.com/navit-gps/navit/files/4192004/Cmakeoutputs.zip)

**Comment by jkoan** [comment]
@licaon-kter i just released v0.5.4-fdroid.3 could you testbuild again?

**Comment by licaon-kter** [comment]
New log: 
[org.navitproject.navit_2002120544.log.gz](https://github.com/navit-gps/navit/files/4197518/org.navitproject.navit_2002120544.log.gz)

**Comment by licaon-kter** [comment]
@jkoan any news?

**Comment by okias** [comment]
@jkoan I plan to use Navit on Linux phones [1], but in meantime would be great to be able install and test recent versions on Android :)

**Comment by licaon-kter** [comment]
New log https://f-droid.org/wiki/index.php?title=org.navitproject.navit/lastbuild_2008082307&oldid=274920

**Comment by jkoan** [comment]
> New log https://f-droid.org/wiki/index.php?title=org.navitproject.navit/lastbuild_2008082307&oldid=274920

Thx for the reminder, but this log doesn't show any actual error... No clue whats going on...

**Comment by licaon-kter** [comment]
Full log: [org.navitproject.navit_2008082307.log.gz](https://github.com/navit-gps/navit/files/5103601/org.navitproject.navit_2008082307.log.gz)

**Comment by mvglasow** [comment]
Details on the latest F-Droid build failure are recorded in #1085, including a detailed analysis of an attempt to reproduce what is going on.

**Comment by mvglasow** [comment]
0.5.6 is now available on F-Droid.
