### ISSUE TITLE
Android build: libnavit.so missing from resulting apk

### ISSUE THREAD

**Issue by lains** [navit-gps/navit#802]
My recent builds for android (using the script `scripts/build_android.sh`) generate an apk that misses libnavit.so.
On a successful build, the apk contains:
unzip -l navit/android/build/outputs/apk/release/android-release-unsigned.apk | grep '\.so.*'
```
   793600  1980-00-00 00:00   lib/armeabi-v7a/libnavit.so
  1203076  1980-00-00 00:00   lib/x86/libnavit.so
```
On recent builds, the apk contains no libnavit.so and the application fails to start in Android, with an error message mentionning that libnavit.so was not found.
It seems this issue was introduced by commit https://github.com/navit-gps/navit/commit/bbff86825991abb7408abf1691118b112c83bed2.
Building succeeds until previous commit https://github.com/navit-gps/navit/commit/b2205d39d2864f4ed7fd3d931b2e6b8f06a6b38b
Or maybe that's just on my build machine, if anyone can give a try...

**Comment by jandegr** [comment]
bbff868 over there seems to contain both libs
https://circleci.com/gh/navit-gps/navit/14377#artifacts/containers/0

**Comment by jandegr** [comment]
but this one contains no lib folder in the apk at all
https://circleci.com/gh/navit-gps/navit/14588#artifacts/containers/0
so I would say it is da3e1e0 instead that causes it

**Comment by jandegr** [comment]
aka 4e5b35a

**Comment by lains** [comment]
@jandegr, yes you're right, it's my mistake.
At bbff868, the shared lib is still included
At 4e5b35a, there is no shared lib, this is easily checked using `unzip -l android-release-unsigned.apk|grep '\.so'`

During compilation, one can spot this quite quickly as one on the last lines during the execution of `scripts/build_android.sh` is:
`[158/158] Linking C shared library ../../../../build/intermediates/cmake/release/obj/armeabi-v7a/libnavit.so
`

I thought the issue was the modification in [navit/CMakeLists.txt](https://github.com/navit-gps/navit/commit/4e5b35a97ea2f2e15b9b5f361ebd3bb9094a4be1#diff-60b4c902ce6303fc9b1194fd0e76c2f3) but reverting only that part of 4e5b35a makes the build fail.

**Comment by lains** [comment]
I tried a few options, but I didn't manage to get libnavit.so back inside the generated apk for Android.

Could someone that is comfortable with cmake have a look?
Maybe @bignaux, given that you are the author of https://github.com/navit-gps/navit/commit/4e5b35a97ea2f2e15b9b5f361ebd3bb9094a4be1 which is where the swirtch over to cmake 3.2 occurred.

**Comment by mvglasow** [comment]
Same here. A bisect tells me 4e5b35a (cmake migration, by @bignaux) was the commit that introduced this behavior.

Just speculating: could dropping the SHARED_LIBNAVIT conditional in navit/CmakeLists.txt have caused this? I tried undoing that portion of the change (reinstating the commented-out lines and commenting out the newly inserted one below), but that gave me all sorts of other strange errors, including compile errors in C code. Unfortunately I don’t know my way around cmake well enough to dig further.

**Comment by mvglasow** [comment]
Adding `'-DANDROID_STL=navit'` to the cmake arguments in `navit/android/build.gradle` (based on https://stackoverflow.com/a/57160242/2703209) did not provide any relief either:

```
  -- Building with CMake V3.6.0-rc2
  CMake Error at /home/michael/tools/android-sdk-linux_86/ndk-bundle/build/cmake/android.toolchain.cmake:405 (message):
    Invalid Android STL: navit.
  Call Stack (most recent call first):
    /home/michael/tools/android-sdk-linux_86/cmake/3.6.4111459/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:98 (include)
    CMakeLists.txt:6 (project)
```

Apparently `libnavit.so` has disappeared from some list of libraries.

The first answer to the SO question (https://stackoverflow.com/a/39628365/2703209) might help with that, but maybe someone with a better knowledge of the build chain can take a look at that.

**Comment by mvglasow** [comment]
I also tried reverting 4e5b35a (on top of the current traffic branch), which did result in a successful build with `libnavit.so` included, but Navit crashed right on startup, reporting stack corruption.

**Comment by mvglasow** [comment]
Here’s the message for the stack corruption, taken on Anbox (Android 7.1.1), right after Navit tries to enable speech:

```
07-30 21:09:18.867   939   939 F libc    : stack corruption detected
07-30 21:09:18.867   939   939 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 939 (itproject.navit)
07-30 21:09:18.867    12    12 W         : debuggerd: handling request: pid=939 uid=10057 gid=10057 tid=939
```

Currently investigating why this is, and when that started… we might be having multiple issues.

**Comment by mvglasow** [comment]
c9ab99b throws a different error (found during bisect), roughly in the same phase of startup:

```
07-30 21:27:55.250  1157  1157 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x11 in tid 1157 (itproject.navit)
07-30 21:27:55.251    12    12 W         : debuggerd: handling request: pid=1157 uid=10057 gid=10057 tid=1157
```

**Comment by mvglasow** [comment]
After skipping all commits with `SIGSEGV`, I get:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
c9ab99b4a6650b9965732a4abe216dcaf7926a9b
18718a8d50c11011c8bcf5bbb1d4153f34d012e1
dbf2bf4bbb6078e42e2e435f31f98a9d6427499a
bfe3e5393b65069e77848b0a3ffc9eaff5f03697
We cannot bisect more!
```

**Comment by mvglasow** [comment]
Right now, reverting 4e5b35a on top of `master` worked. Don’t know what went wrong before…

**Comment by mvglasow** [comment]
I also tried reverting 4e5b35a (on top of the current `traffic` branch), which did result in a successful build with `libnavit.so` included, but Navit crashed right on startup, reporting stack corruption. Taken on Anbox (Android 7.1.1), right after Navit tries to enable speech:

```
07-30 21:09:18.867   939   939 F libc    : stack corruption detected
07-30 21:09:18.867   939   939 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 939 (itproject.navit)
07-30 21:09:18.867    12    12 W         : debuggerd: handling request: pid=939 uid=10057 gid=10057 tid=939
```

Currently investigating why this is, and when that started… we might be having multiple issues.

A bisect of `traffic` gave me:

> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> c9ab99b
> 18718a8
> dbf2bf4
> bfe3e53
> We cannot bisect more!

All of these commits are on `traffic`. Reverting 4e5b35a on top of master worked.

**Comment by lains** [comment]
Thanks for digging this out @mvglasow.
So if I understand we're back at understanding what broke for Android builds in 4e5b35a...
I'm not very comfortable with cmake, so I cannot help much... sorry!

@bignaux, could you help on this issue? I think you are our cmake hero here!

**Comment by pgrandin** [comment]
I am facing an issue with buildroot and I'm wondering if it isn't related. 
Here, `libnavit_core.so` is built in the staging folder but not installed in the target.
The other two libs are also missing in the target folder :
```
< navit/traffic/null/.libs/libtraffic_null.so
< navit/traffic/dummy/.libs/libtraffic_dummy.so
```

**Comment by metalstrolch** [comment]
Hmm, in https://github.com/navit-gps/navit/blob/ab4d8087a349fa580a4fca1053eca44b1813be16/navit/android/CMakeLists.txt#L47 it seems the libnavit.so is copied around prior packaging. Somebody should check if the location it gets copied from changed due to the changes. Unfortunately I don't have any Android setup to check. Is there a guide on how to set up Android build?

**Comment by jandegr** [comment]
my attempt at fixing it, pls anybody help testing.

now includes so for x86, armeabi-v7a and arm64-v8a
