### ISSUE TITLE
Blank map

### ISSUE THREAD

**Issue by gioerre** [navit-gps/navit#809]
Hi, i have installed navit 0.5.3 by repository on raspberry 3b+ with rasbian buster and on pc with debian buster but in both of them the map is blank.
I have loaded bin map, i have disabled sample map and i have enabled my map but it does not work.
When i run navit i get this error:
error:navit:xinclude:Unable to include /usr/share/navit/maps/*.xml

Thanks

**Comment by metalstrolch** [comment]
The error you see is quite normal, as most probably you don't have and don't need these maps/*.xml files for your setup. Usually not an indicator for a problem.

Please check some things:
1. Run navit and check "Settings->Maps" in menu. See if the map you entered is in the list and checked. If not, check your navit.xml mapset entries. Check specially for: active and enabled settings. Note that only one mapset may be enabled.
2. Run navit and check "Settings->Display->Layout. There should be more than one layout usually. If not, check if there is for example navit_layout_car.xml next to your navit.xml. If you copied it over to ~/.navit/navit.xml , then copy navit_layout_*.xml there as well
3. Check how navit is centered. Use Menu "Actions->Town" to search a town that should be in your map. Center to that. The default if untouched is Munich Germany, which is the sample map,  which may not be on your map. Yes this is a silly mistake, but happens quite often.

You're welcome.

**Comment by gioerre** [comment]
Hi @metalstrolch ,
my problem was the third point, I solved

Thanks
