### ISSUE TITLE
Remove "duplicate check" from Codefactor

### ISSUE THREAD

**Issue by metalstrolch** [navit-gps/navit#811]
Is it possible to remove the "duplicate check" from codefactor for "C"? At least on #810 it delivers completely bogus results marking the commits as failures. This is more than annoying.

**Comment by jkoan** [comment]
Is this still relevant, Codefactor is not a merge blocker any more.

**Comment by metalstrolch** [comment]
Closing this as CodeFactor is no Blocker any more,
