### ISSUE TITLE
New icons are shown very big

### ISSUE THREAD

**Issue by naggety** [navit-gps/navit#819]
Some of the POI icons are shown really big in the map. They happen to be the ones that look the newest icons (flat style in blue color).

Opening the svg files with a text editor, I see that they have properties width and height = 200. The ones that are shown at a proper size are 22x22.

I think that they should use a size defined in the code, or in navit.xml or something like this, not the size defined in the .svg itself since this is too error prone.

However, just in the case that you want to fix the .svg files, this is the list of affected files (I hope it's complete, but there may be not)

```
grep -rn ' height=' *.svg | awk '{FS=":"; if($2<25) print}' | awk '{FS="\""; if ($2 == 200) print}'
bowling.svg:12:   height="200"
bridge.svg:12:   height="200"
car_wash.svg:12:   height="200"
communication.svg:12:   height="200"
concert.svg:12:   height="200"
crossing.svg:12:   height="200"
dam.svg:12:   height="200"
danger_area.svg:12:   height="200"
diving.svg:12:   height="200"
drinking_water.svg:12:   height="200"
emergency.svg:12:   height="200"
fish.svg:12:   height="200"
forbidden_area.svg:12:   height="200"
ghost_town.svg:12:   height="200"
government_building.svg:12:   height="200"
gui_heightprofile.svg:1:<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
hotspring.svg:12:   height="200"
```

![navit-big-icons](https://user-images.githubusercontent.com/3511999/61944295-ac7b5180-af9d-11e9-9ac9-3ac4577eb560.png)

**Comment by metalstrolch** [comment]
Yes this is because of the width and height tags in the svg files. You can force the correct size by giving w and h tags to them in navit.xml or the corresponding layout. I'm thinking of adding a default w and default h tag to other tag in config for "all" icons to cater this.
But to quick-fix one could change the width and height tags in the svgs.

**Comment by naggety** [comment]
I've just tried and, in fact, giving w and h tags to the icon in the layout works. But it's a good idea to add a default size for icons without explicit w and h tags.
