### ISSUE TITLE
Switch to cmake 3.2 breaks Android build

### ISSUE THREAD

**Issue by mvglasow** [navit-gps/navit#821]
I tried to build Navit from latest master today and run it on Android, only to find it crashes right on startup because `libnavit.so` cannot be found.

A bisect tells me 4e5b35a (cmake migration, by @bignaux) was the commit that introduced this behavior.

Just speculating: could dropping the `SHARED_LIBNAVIT` conditional in `navit/CmakeLists.txt` have caused this?

**Comment by lains** [comment]
Yes, I confirm the issue. This is the same as #802

**Comment by mvglasow** [comment]
Closing this as a duplicate then.
