### ISSUE TITLE
Navit trunk crash if navit.xml contain lag="1"  and cdf_history="0" 

### ISSUE THREAD

**Issue by gefin** [navit-gps/navit#826]
If navit.xml contain both of this two lines navit crash. 
Tested with linux and Tomtom.
Also tested source file and gpsd

vehicle name="Local GPS" profilename="car" follow="1" enabled="yes" active="1" lag="1"                            source="file:/dev/ttyUSB0" 
and 
tracking cdf_histsize="0"/

With lag="0" all work well.
Without the tracking line all work well.

In bad case the function iso8601_to_secs(time_attr.u.str); is called with a NULL pointer.
The function dont check this...

The bad call of iso8601_to_secs is in navit/track.c line 683.

**Comment by ummerland** [comment]
Experiencing the same issue on Windows with the following config:
<vehicle profilename="car" follow="1" enabled="yes" active="1" lag="1" source="serial:COM5 baud=9600 parity=N data=8 stop=1" name="Local GPS">

The removal of tracking, cdf_histsize="4" do not seem to solve the issue here

**Comment by gefin** [comment]
removing cdf_histsize="4" in not enough.
After removing complete <tracking .... part it worked.

**Comment by ummerland** [comment]
Yes you are right. However for me it does not crash, but it stops receiving GPS data.

I have just taken a look at the surrounding code of https://github.com/navit-gps/navit/blob/3c6b0629e3e8f7aec00e5f3756f2b330c3ad363b/navit/track.c#L683

The variable time_attr is initialized a few lines prior here:
https://github.com/navit-gps/navit/blob/3c6b0629e3e8f7aec00e5f3756f2b330c3ad363b/navit/track.c#L621
But it does not get set to a value before line 683, where it is put into the ISO8601 conversion function. So the string is null (or .empty())

**Comment by gefin** [comment]
Yes, i think it ts empty because the line 
vehicle_get_attr(tr->vehicle, attr_position_time_iso8601, &time_attr, NULL));
was removed at https://github.com/navit-gps/navit/commit/03f3aa8637fff3e8e09d3bde21b28654454011fd#diff-3cbc3b1f62b4a7f91ff8ea7691e63e64

**Comment by gefin** [comment]
I added PR #837 to fix this.

**Comment by ummerland** [comment]
Thanks for your PR and your work.
Did you get a chance to test it on your setup?

I tried the circleci build from https://download.navit-project.org but it still refuses to accept `<tracking/>`. It does not crash, but it refuses to take GPS inputs on my machine.

**Comment by gefin** [comment]
yes, i tested with linux, tomtom and android.

Dont use cdf_histsize="4" because this is not supported.
cdf_histsize="0" is OK.

How is your GPS configurated?
May be you can use the debug options or traces to see what goes on.

**Comment by ummerland** [comment]
Ok great.

You were absolutely right about my GPS config.
NMEA is generated by a piece of software i wrote in .NET. It sends $GPGGA, $GPVTG and $GPRMC over com0com to navit.
I took a look at the debug file. It revealed that one of my NMEA checksums was wrong. I had a copy&paste error.

Now `lag` works together with `route_pref`, `tunnel_extrapolation` and `cdf_histsize`. Can´t wait to test it.
Thank you gefin

**Comment by gefin** [comment]
fixed with PR #837
