### ISSUE TITLE
Misconfiguration for CI requirements for pull requests

### ISSUE THREAD

**Issue by metalstrolch** [navit-gps/navit#834]
Currently Pull requests demand two android build targets for merge which aren't even built causing the pull requests to be not merge able.

The missing targets are: build_android_arm and build_android_x86
Current CI config does only build build_android.
This causes the state to stall at "yellow dot" indicating CI activity for good, as the targets will never succede or fail.

Who can fix that?

**Comment by metalstrolch** [comment]
This affects at least #817 #818 #824 and maybe all other.

**Comment by viktorgino** [comment]
The commit where build_android_arm was removed: https://github.com/navit-gps/navit/commit/ff26b80878d2dc9e86e630746cb2e96922697876

**Comment by viktorgino** [comment]
I think the build_android_arm and build_android_x86 status checks need to be disabled in the project settings: https://circleci.com/docs/2.0/enable-checks/#github-checks-waiting-for-status-in-github

**Comment by metalstrolch** [comment]
Most probably. Needs to be done by somebody having the proper rights on CI for Navit organisation. I don't.

**Comment by metalstrolch** [comment]
We could opt in fake adding the targets in the meantime. Shall we?

**Comment by viktorgino** [comment]
@metalstrolch I think that would work as a workaround
@pgrandin can you try to disable the build_android_arm and build_android_x86 status checks in the project setting here on GH?

**Comment by pgrandin** [comment]
I did disable the two older android builds and also made CodeFactor optional. Thanks for the report @metalstrolch
