### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by mvglasow** [navit-gps/navit#840]
Android build fails with the following error on Ubuntu 18.04 (all patches applied):

```
  In file included from ~/src/navit/navit/vehicle/gpsd_dbus/vehicle_gpsd_dbus.c:22:
  In file included from /usr/include/glib-2.0/glib.h:30:
  In file included from /usr/include/glib-2.0/glib/galloca.h:32:
  /usr/include/glib-2.0/glib/gtypes.h:423:3: error: '_GStaticAssertCompileTimeAssertion_0' declared as an array with a negative size
    G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /usr/include/glib-2.0/glib/gmacros.h:241:103: note: expanded from macro 'G_STATIC_ASSERT'
  #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                                                                        ^~~~~~~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.
```

Looks like a failed assertion in `vehicle_gpsd_dbus.c`. At that point I am wondering why we are building this at all on Android, where this vehicle implementation is pretty much useless—probably some fault in the toolchain configuration. This error seems to have been introduced quite recently and does not seem to occur on CircleCI. If I can find the time I will dig into this deeper.

**Comment by gefin** [comment]
view PR #827.
there is the description of the problem with a working solution.
The problem is the usage of hist libs instead from toolkit.

**Comment by mvglasow** [comment]
Doesn’t work for me (added these lines right after the other exports); I still get the same error.

**Comment by gefin** [comment]
I have the information about from PR #833

**Comment by mvglasow** [comment]
Reading the PR again, no more tweaking should be needed as it is already merged. However, it is essential to clean up the build environment, especially removing everything under `navit/android` which is in `.gitignore`.

More precisely, I extended my preexisting Android cleanup script. Essential steps are:

```
rm -rf CMakeFiles locale man/CMakeFiles man/Makefile man/cmake_install.cmake navit/CMakeFiles navit/android/.externalNativeBuild navit/android/assets navit/android/build navit/android/cmake_plugin_settings.txt navit/android/res/drawable-nodpi navit/android/res/raw navit/*/CMakeFiles navit/*/*/CMakeFiles navit/*/Makefile navit/config navit/icons/cmakefiles navit/*/cmake_install.cmake navit/*/*/cmake_install.cmake CMakeCache.txt CPackConfig.cmake CPackSourceConfig.cmake Makefile cmake_install.cmake cmake_plugin_settings.txt config.h navit.dtd navit/Makefile navit/icons/desktop_icons/navit.desktop navit/binding/dbus/org.navit_project.navit.service navit/builtin.c navit/cmake_install.cmake navit/graphics/qt_qpainter/*.moc_parameters navit/gui/qml/*.moc_parameters navit/icons/cmakelists.txt navit/icons/makefile po/CMakeFiles po/Makefile po/cmake_install.cmake po/navit.pot po/navit_shipped.c po/strings_xml.c po/*.mo po/*.po cmake/* navit/*/*/Makefile navit/icons/*.png
git reset --hard
```

**Note that the last statement will revert any uncommitted changes!**

After doing this, I was able to build from trunk with no further issues.

**Comment by lains** [comment]
> However, it is essential to clean up the build environment, especially removing everything under `navit/android` which is in `.gitignore`.

Yes, indeed. I had the same problem as stated here:
https://github.com/navit-gps/navit/pull/833#issuecomment-522291145
