### ISSUE TITLE
Maptool defaults to 32 bit zip file

### ISSUE THREAD

**Issue by metalstrolch** [navit-gps/navit#845]
Currently the maptool defaults to create 32 bit zip files with an option "-6" to generate 64 bit zip files as well.

Since 32 bit zip files fail badly if they grew larger than 4GiB I recommend making "-6" the default. There is nothing wrong with using 64 bit zip files for content smaller than 4GiB, and it's highly frustrating loosing the result of multiple days map conversions because of this.

**Comment by metalstrolch** [comment]
Fixed in #824

**Comment by jkoan** [comment]
@pgrandin, @mvglasow, @aerostitch,
does anything speaks against this?

**Comment by metalstrolch** [comment]
Yes it should still work on old systems, as even now all maps downloaded from planet extractor are already 64 bit zip files. In fact navit binary is not even affected, only maptool. Only if you process a really small part of the world 4GIB result is enough.
In #824 I added a -3 switch to force 32 bit zipfiles, and kept the now useless -6 switch for compatibility reasons.
And the maptool doesn't run on 32 bit systems for ages because of other reasons.

**Comment by metalstrolch** [comment]
Closing this as #824 got merged into trunk
