### ISSUE TITLE
Missing "polygon with holes" support for android

### ISSUE THREAD

**Issue by metalstrolch** [navit-gps/navit#852]
It is planned to include multipolygon support #824 into navit before 0.5.4 release, which is a good thing indeed.
However for full experience of the then enhanced maps, it would be good to add graphics support for drawing polygons with holes on Android, SDL and Windows CE targets as well.

I added Windows support (except CE) to #824 as it was no big issue to do even with only CI as build environment.

I added Windows CE support in #862

I added SDL support in #861

Despite willing to do so I cannot help much for android, as I don't have access to any Android device to test the result. But I am willing to help pointing out what needs to be done.

**Comment by metalstrolch** [comment]
Added Windows support except CE to #824.

**Comment by jkoan** [comment]
Is there a way to add wince as well? i can do the test on wince

**Comment by metalstrolch** [comment]
Not on the fly and not for me.
Windows CE seems to have a really limited and crippled GDI which doesn't support DrawPath used by me for win32. I fear that WindowsCE will be one of the platforms that doesn't have a native graphics library capable of drawing polygons with holes. So here we may be forced to manually triangulate.

But as not being a Windows dev, and the documentation about WindowsCE (C language specially) is really limited I may be wrong, but it seems I'm done here. I don't have any Device to test either, and the development cycles with only CI as build environment is rather slow.

Hopefully someone with Windows CE knowledge may help out here. Btw. I wonder that this old system is still in productive use.

**Comment by metalstrolch** [comment]
Add SDL with #861
Same attempt suitable for Windows CE.

**Comment by metalstrolch** [comment]
Add Windows CE with #862

**Comment by pgrandin** [comment]
Really nice work @metalstrolch 

We have an experimental openSTF farm available. This could allow you to test android related features. Would you be interested?

**Comment by metalstrolch** [comment]
Thanks for the offer @pgrandin,
but I think this may not make much sense. I'd need to refresh my knowledge on Java, learn about Android graphics API,  and learn some JNI. Additionally I'd need to learn how to build and deploy to Android as I virtually never even used any Android device. And It would require me to set up a development environment as only CI is too slow a development cycle. It worked for Windows because it's just "C" and I were lucky i got it right with few iterations.

Last but not least it would require me to learn coding habits for Android, as #832 convinces me is something I better not make my fingers dirty. I don't like to be blamed for code I write for alien architectures barely knowing the system.

I was still hoping somebody with Android knowledge could at least try to set up the new graphics function. The learning curve seems to be too ineffective for doing this on my own.
- Metalstrolch

**Comment by lains** [comment]
Hello @metalstrolch. I do have a build environment and several target machines for Android if testing is needed.
However, I have to say don't know much about Android graphics nor about navit's graphics subsystem... and I might bring long delays in the loop...

**Comment by pgrandin** [comment]
@metalstrolch i understand your point about having to learn the java part. I'm in the same boat. I'll chime in #832 regarding CodeStyle but wanted to say this anyway : CodeStyle is a tool to help us improve our code. One way to do it is to fix old code style issues (there's sometimes really good fixes that can be uncovered) and another way is to prevent us from adding new issues. 
Codestyle isn't a merge gate. **Codestyle shouldn't be construed as a way to gauge someone's technical expertise.** 

Everybody is contributing with the goal to make Navit better. It's OK if you want to focus on one topic or one architecture. It's also OK if you submit a not perfect pull request to address an issue you've uncovered. Hopefully someone who knows more about that area can help and improve it.

 Your contributions are welcome.

**Comment by metalstrolch** [comment]
Ok, let ranting aside and do something, just to start another ranting.
I've started porting polygons with holes to Android in #889. It seems to semantically and syntactically to compile, but fails for style check once more. Since I cannot test this anyways, I leave dealing for to many or too less spaces before or after "if" in java code up to somebody knowing the tooling / style / habits.
How many style checks are there?
I don't wonder more and more only few people actually enhance Navit if every line you add / change fires a cascade of unrelated style check (spaces around ifs. OMG.) before ci actually presents you the result of the work you did. And looking at the compiler output it seems everybody is blinded by CodeFactory not complaining that the really important things (compiler warnings!) are not even cared for anymore. Sorry. But I abandon #889 unless we rethink those style check paranoia.

**Comment by metalstrolch** [comment]
As #889 got merged we can now close this (even if #889 was still buggy) Follow on issue to fix the bug already existing.
