### ISSUE TITLE
Missing clipping for polygons with holes leads to slow rendering performance on Windows CE and SDL

### ISSUE THREAD

**Issue by metalstrolch** [navit-gps/navit#869]
Currently the core is lacking clipping support before handing over polygons that contain holes (attr_hole) to graphics back end. As Windows CE and SDL are rendering by manually raycasting polygons (with or without holes), and do not support clipping as well, rendering performance is poor when the screen shows many small portions of large polygons.

This was reported in #861 by @gefin first.

**Comment by metalstrolch** [comment]
Seems this happens because of two really large polygons with many holes having a quite high node count each:
https://www.openstreetmap.org/relation/2892951
and
https://www.openstreetmap.org/relation/68363
At the location 48°8'24'' N 12°1`50`` E along the B12.

Currently core doesn't implement clipping for polygons with holes. It does for polygons without holes.
And the WindowsCE (and SDL) graphics do not implement clipping as well.
So the polygons are completely raycasted and drawn even if only small portions of them are really on screen.

I'll try two things:
1. Port the "clipping" version of polygon handling in graphics.c to support holes as well. I've left a TODO there anyways.

2. Check  layer geometry on Windows / SDL graphics to only raycast lines which are actually on layer.

**Comment by gefin** [comment]
you are right. The location B12 is fast and smooth drawn with poly_wood removed from layout.
With a active polygon with hole the slowdown begins a screen width away from the polygon. 
Thanks for explain.

**Comment by metalstrolch** [comment]
#870 should fix this.
@gefin: can you give it a try?

**Comment by gefin** [comment]
Tested Build16731 Tomtom730 . Polygons with Holes work very well. The delay is gone. Thanks 
Thursday real drive...

**Comment by metalstrolch** [comment]
Will wait for Thursday before merging #870

**Comment by gefin** [comment]
Build16731 work well while real driving. No lags or other problems.

**Comment by metalstrolch** [comment]
Fixed in #870
