### ISSUE TITLE
Sychronization from launchpad to github is broken since October 2018

### ISSUE THREAD

**Issue by hoehnp** [navit-gps/navit#893]
Launchpad shows under automatic synchronization:
The import has been suspended because it failed 5 or more times in succession.

**Comment by pgrandin** [comment]
Which import?

The translation template (.pot) is the file that matters :
```
  | navit.pot in                                          Navit trunk series | Imported |  
Uploaded by                     KaZeR                     on 2019-10-18 12:14:50 CEST
```

And it shows as being imported : https://translations.launchpad.net/navit/trunk/+imports

**Comment by hoehnp** [comment]
@pgrandin: Seems resolved. Error was showing up here under automatic synchronization:
![bild](https://user-images.githubusercontent.com/8470441/67243694-76445580-f458-11e9-908a-22974f60ee10.png)
