### ISSUE TITLE
Cleanup:Duplicate function search_fix_spaces() in android.c and search.c

### ISSUE THREAD

**Issue by lains** [navit-gps/navit#898]
Code is almost identical:

https://github.com/navit-gps/navit/blob/56f6be45d5ce5f961c1826ef2f06d6678f770eb0/navit/search.c#L138-L164

and 

https://github.com/navit-gps/navit/blob/56f6be45d5ce5f961c1826ef2f06d6678f770eb0/navit/android.c#L683-L710

**Comment by aerostitch** [comment]
Let me know if #917 is the fix you had in mind. I'm open to suggestions about better ways to do that as I'm a novice in C programming.

**Comment by lains** [comment]
Thanks for your work.
