### ISSUE TITLE
Update app icon on Android

### ISSUE THREAD

**Issue by lains** [navit-gps/navit#909]
Android build is using the old icon (prior to #436).
Shall this logo be upgraded?
If so, which one from the catalog:
![image](https://user-images.githubusercontent.com/383502/66711857-17197d80-ed94-11e9-8e4b-6ac22848ef0a.png)

(1 2 3
 4 5 6)

I think 3, 4, 5 and 6 are mode adequate because they include their own background for padding.

**Comment by jkoan** [comment]
I vote for 3 because in my opinion it strikes the eye the most. My second vote would be for 4 because it's shape is square.
what I think would be the worst choice are the black and white variants because they are more or less boring when compared to other app icons

**Comment by mvglasow** [comment]
How about a white icon on an orange square background? This could also be turned into an adaptive icon where background shape is determined by user settings (circle, square, squircle etc.). Background color could be a gradient (as in 3) or solid orange (same as used for the foreground in 4 and 6).

**Comment by lains** [comment]
Here is a mix between 3 (shape) and 4 (colors):
![navit_android_icon](https://user-images.githubusercontent.com/383502/66770761-ad46c400-eeb8-11e9-8ee2-39d477409943.png)

Of course, round corners could be removed completely and get a pure outside square shape, which is what you suggest, @mvglasow, if I understood correctly.

**Comment by mvglasow** [comment]
Looks good! As for adaptive icons, I am not sure about how this is done—still haven’t gotten around to it in any of my projects. We can still use a non-adaptive icon (such as the one above) for now and turn it into an adaptive one later.

**Comment by lains** [comment]
This would look like:
![Screenshot_20191105-065536](https://user-images.githubusercontent.com/383502/68182275-b0a20c80-ff99-11e9-9636-ba47efd275f5.png)
