### ISSUE TITLE
Broken link for Grosser Reiseplaner map type in README.md

### ISSUE THREAD

**Issue by Benjamin-Davies** [navit-gps/navit#914]
In the "Maps" section of the README, the link for "Grosser Reiseplaner and compliant maps" goes to a page on the old wiki that says "There is currently no text in this page."

Version: current trunk at the time of writing, commit a3b20c4

**Comment by tombsar** [comment]
Perhaps this is the correct link? http://wiki.navit-project.org/index.php/Marco_Polo_Grosser_Reiseplaner
