### ISSUE TITLE
Two background map colors

### ISSUE THREAD

**Issue by navitraspi** [navit-gps/navit#949]
Hey.

I am having a problem with a map layout. I am using Raspberry Pi and an „Android-Car” map layout. Some of the background colors are almost white, „creamy” - and that’s what I want, but there are some „squares” on the map that are really big and... turquoise. How can I change that? It’s not the water, cause it’s about a 1/3 of my current country map.

Thanks!

**Comment by navitraspi** [comment]
Anyone? It looks so horrible.

![0FB80A6C-7500-4670-A557-D7F64E0A7BDA](https://user-images.githubusercontent.com/58643610/70425846-3ec65280-1a72-11ea-9a7c-2db94f88eda7.jpeg)
![Uploading 235A5CED-690E-4EDE-84BA-514C304A2FEE.jpeg…]()

**Comment by jkoan** [comment]
Hi @navitraspi,
this erros is due to problems with the map. In this case somewhere a waterpolygon is broken and causes the polygon to cover a really large area.
You can try to replace the map with a new one. Export a different area boundarie or craft your own map with maptool

**Comment by metalstrolch** [comment]
You most probably got hit by a "virtual flooding" as it looks like. You can click on a "flooded" area and use "Actions -> "<coordinates>". It presents you with the list of map items you clicked on. It's hard to miss the flood. I expect there to be "poly_water_tiled" to be present.

If yes: The OSM coastline causing this needs to be fixed. You can select the "poly_water_tiled" and select "Show attrbutes" to get the osmid causing this.

You can crosscheck by removing/changing the coloring for "poly_water_tiled" itemgra in your layout xml file. If the "flooding" changes color with the oceans, then you have it.

-> If I'm right, you need a fixed map, Where did you get it from?

**Comment by navitraspi** [comment]
I got it from the World Extractor, will try to do as you described. Thanks! I will inform if there is no change.

**Comment by navitraspi** [comment]
Changing the „poly_water_tiled” color to default background color worked well, thank you! 
![98E46FE6-808F-4DEF-95D0-E8C487292B63](https://user-images.githubusercontent.com/58643610/70429088-3113cb80-1a78-11ea-985d-040ebc828a45.jpeg)

**Comment by metalstrolch** [comment]
You should keep in mind that you recolored oceans that way as well and the color might still cloak map elements. It's better to remove the itemgra, not drawing oceans and the flooding altogether if not interested in oceans anyways. Have fun.

**Comment by navitraspi** [comment]
Generally there are no oceans around me, but removed the whole itemgra as you proposed. Thank you so much, guys! Navit is a wonderful tool.
