### ISSUE TITLE
navit.xml error with no changes having been made

### ISSUE THREAD

**Issue by gillesonsaltspring** [navit-gps/navit#951]
running on raspbian buster fully updated and upgraded.  using latest version of navit  copied navit.xml to .navit/navit.xml  but made no changes  ...  any help would be appreciated.

error:navit:main_real:Error parsing config file '/home/pi/.navit/navit.xml': Element 'config' within unexpected context 'mapset'. Expected '' at line 10, char 1
 at line 404, char 51

**Comment by jkoan** [comment]
Could you please upload the Navit.xml with the error?

**Comment by jkoan** [comment]
Will close this issue as no navit.xml was provided
