### ISSUE TITLE
Navit android crash near polygon with holes pull

### ISSUE THREAD

**Issue by gefin** [navit-gps/navit#965]
Navit crashes on a LG K9 android 7.1.2

The last working trunk build is  https://circleci.com/gh/navit-gps/navit/19254#artifacts
the first crashing is https://circleci.com/gh/navit-gps/navit/19326#artifacts

so i think the problem is around pull #889 polygon with holes.

**Comment by jkoan** [comment]
Are you able to provide a logcat output of the exception?

**Comment by gefin** [comment]
Sorry, it takes some time. No actual Windows here...

**Comment by gefin** [comment]
Help this?
[navitdebug.txt](https://github.com/navit-gps/navit/files/4087816/navitdebug.txt)

**Comment by metalstrolch** [comment]
The most "speaking" entry inside the trace is:
01-20 21:29:55.939  4524  4524 F DEBUG   : Abort message: 'art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethod called with pending exception java.lang.ArrayIndexOutOfBoundsException: int[] offset=0 length=14 dst.length=1'

Seems were accessing an array out of bounds in JNI. As this seems to be linked to polygons with holes, one should check the corresponding JNI C and Java methods for array operations.

**Comment by metalstrolch** [comment]
As Java complains about the JNI method being called with pending exception, the error must happen  in the draw_polygon_with_holes in navit/graphics/android/graphics_android.c Most probably by accessing some of the data structures requested for JNI. As the "C" ones would just cause a crash, no java exception.

**Comment by metalstrolch** [comment]
Someone wants to try out the result of #973 ? This could have a fix for this issue.

**Comment by gefin** [comment]
I tested https://circleci.com/gh/navit-gps/navit/19662 
No crash, but  no holes in polygons.

**Comment by metalstrolch** [comment]
Ok. Seems we process the polygons with holes at least. Chiemsee does have holes. You can check by looking at the map elements properties. But Herrenchemsee shouldn't be flooded. So either the holes are not properly passed to Java, or what I assume more, the Java code doesn't draw the holes. Let's have a look at the drawing code first.

Unfortunately I still own no Android device and probably never will. So I cannot test this.

**Comment by metalstrolch** [comment]
Did some more fixes in #973. But this won't fix it yet as it only prevents crashing on drawing big polygons.
I added my polygon testing map once more.
1. Use the fake-munich.bin as binfile map
2. Enable landfill polygons in your layout by adding the following itemgra (or checking if it's there)
```
                <itemgra item_types="poly_landfill" order="10-">
                        <polygon color="#999893"/>
                        <text text_size="5"/>
                </itemgra>
```
3. Center to Munich, Germany (lat='48.14272428889' lon='11.56003117749'). Zoom in to find the polygons.

Please post a screenshot of the resulting drawing.

[fake-munich.bin.zip](https://github.com/navit-gps/navit/files/4095991/fake-munich.bin.zip)

**Comment by metalstrolch** [comment]
Hmm I have a theory what's going on. But I won't tell unless another experiment...

Here's a slightly modified version of my fake-munich map. Can you please repeat the experiment mentioned above using the fake-munich-reverse.bin instead and again post the resulting image.

[fake-munich-reverse.zip](https://github.com/navit-gps/navit/files/4102425/fake-munich-reverse.zip)

**Comment by gefin** [comment]
Now i see one additional hole. All other polygons did not change.
![1](https://user-images.githubusercontent.com/18344603/72995033-81f93c80-3df8-11ea-9f7a-9cf78a19addf.png)

**Comment by metalstrolch** [comment]
Not exactly. You see two other holes instead of the one from last time. And this confirms my theory.
It seems that "android.graphics.path" expects that holes in polygons come in opposite direction than the outer polygon.

The good thing is, that I now know that the JNI code does correct. It's "just" the Java part drawing incorrectly.

What I did: I reversed the lines forming the three hole polygons. This causes the one to disappear but shows the two others. The one hole you've seen first time was the only one drawn in different orientation.

To fix this I need to:
- either learn more about android graphics and find a way to not require a polygon direction to properly draw.
- or calculate the polygon direction and reverse the polygons if required.

I think I'll do the latter since I don't have any android device and the rotating can be done in C.

**Comment by metalstrolch** [comment]
OK. Once more with feeling. I Implemented polygon reversing as proposed in last post in #973. As I have no android device this is completely untested and may crash badly.
But still I ask if the "fake-munich" text can be done with that version.

**Comment by gefin** [comment]
No bad crash :-)
I uses "fake-munich.bin
![1](https://user-images.githubusercontent.com/18344603/73080385-0b2a7500-3ec6-11ea-8863-ade5b0d099bd.png)
Now also Chiemsee changed. Herrenchiemsee is ok but Frauenchiemsee is flooded. So I think reversing work well, but detecting the direction sometime fail.
![2](https://user-images.githubusercontent.com/18344603/73080562-4fb61080-3ec6-11ea-8b42-c015cdb1a18a.png)

**Comment by metalstrolch** [comment]
As long as there are versions, there's still hope. Please retry with changes in #973 .
Blind programming going on.

**Comment by gefin** [comment]
Thank you. Now it look very good.
![1](https://user-images.githubusercontent.com/18344603/73117754-977e7b80-3f4a-11ea-9655-338910e95e9b.png)
![2](https://user-images.githubusercontent.com/18344603/73117755-9baa9900-3f4a-11ea-8ba8-d928628b1074.png)

**Comment by metalstrolch** [comment]
Cool. Preparing #973 to merge.

Just for curiosity, could you post a screenshot of Munich Airport or Munich Zoo? I'm curious how the transparency looks on an android device. Because transparency at least seems to work. The nature reserve around Herrenchiemsee is drawn correctly at least.

**Comment by gefin** [comment]
Need a special detail?
![4](https://user-images.githubusercontent.com/18344603/73119037-b7b73600-3f5c-11ea-8a19-cc88a382a270.png)
![5](https://user-images.githubusercontent.com/18344603/73119039-b980f980-3f5c-11ea-84b9-d11a34cd9b5e.png)
